### ISSUE TITLE
java.io.FileNotFoundException: fileToBytes(this, "file.txt") when producer tests are being generated and runned

### ISSUE THREAD

**Issue by yuriikuznetsov** [spring-cloud/spring-cloud-contract#1143]
Bug report:

In contracts repo I have a class **ShouldReturnMetadataObject.groovy**:

```
import org.springframework.cloud.contract.spec.Contract

Contract.make {
    description 'Should return metadata'
    request {
        method 'GET'
        urlPath('/metadata/object') {
            queryParameters {
                parameter "serviceName": $(consumer(nonBlank()), producer("testService"))
                parameter "id": $(consumer(nonBlank()), producer("testId"))
            }
        }
    }

    response {
        status 200
        headers {
            contentType applicationOctetStream()
        }
        body(fileAsBytes("sample.txt"))
    }
}
```

and **sample.txt** in the same directory with content: 

> test content

when I run mvn install on producer service side the **ApiTest.java** is generated:

```
@Test
	public void validate_shouldReturnMetadataObject() throws Exception {
		// given:
			MockMvcRequestSpecification request = given();

		// when:
			ResponseOptions response = given().spec(request)
					.queryParam("serviceName","testService")
					.queryParam("id","testId")
					.get("/metadata/object");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
			assertThat(response.header("Content-Type")).matches("application/octet-stream.*");
		// and:
			assertThat(response.getBody().asByteArray()).isEqualTo(fileToBytes(this, "shouldReturnMetadataObject_response_sample.txt"));
	}
```

and file in the same directory named: **shouldReturnMetadataObject_response_sample.txt** with content: 

> test content

 
but test is failed with exception:

```
[INFO] Running c.META_INF.com_company_contracts.myservice_metadata_service.34430_SNAPSHOT.contracts.src.main.resources.contracts.myservice_metadata_service.rest.ApiTest
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.433 s <<< FAILURE! - in c.META_INF.com_company_contracts.myservice_metadata_service.34430_SNAPSHOT.contracts.src.main.resources.contracts.myservice_metadata_service.rest.ApiTest
[ERROR] validate_shouldReturnMetadataObject(c.META_INF.com_company_contracts.myservice_metadata_service.34430_SNAPSHOT.contracts.src.main.resources.contracts.myservice_metadata_service.rest.ApiTest)  Time elapsed: 0.074 s  <<< ERROR!
java.lang.IllegalStateException: java.io.FileNotFoundException: shouldReturnMetadataObject_response_sample.txt
    at c.META_INF.com_company_contracts.myservice_metadata_service.34430_SNAPSHOT.contracts.src.main.resources.contracts.myservice_metadata_service.rest.ApiTest.validate_shouldReturnMetadataObject(ApiTest.java:73)
Caused by: java.io.FileNotFoundException: shouldReturnMetadataObject_response_sample.txt
    at c.META_INF.com_company_contracts.myservice_metadata_service.34430_SNAPSHOT.contracts.src.main.resources.contracts.myservice_metadata_service.rest.ApiTest.validate_shouldReturnMetadataObject(ApiTest.java:73)
```

but when I run this test manually it is passed.

the maven plugin used with version:

> org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.2.RELEASE

So it looks like when maven plugin runs this test exactly after generating **ApiTest.java** the file **shouldReturnMetadataObject_response_sample.txt** is not generated at that moment.

Thanks in advance!

**Comment by marcingrzejszczak** [comment]
Can you please create a sample that replicates this issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
