### ISSUE TITLE
Error when using optional() and anyOf() together

### ISSUE THREAD

**Issue by wabrit** [spring-cloud/spring-cloud-contract#1215]
I'm using Spring Cloud Contract 2.1.2-RELEASE and have a contract that requires a JSON request body containing an optional field whose value is constrained to be one of a small number of strings.

I thought it would be possible to combine optional() with anyOf() in order to express this e.g.

```
Contract.make {
  ...
  request {
    ...
    body (
      foo: $(consumer(optional(anyOf('WORKS','MIGHTY'.'DESPAIR'))), producer('DESPAIR'))
    )
  }
 ...
```

However this gives the error during the generate test phase:

```
Exception in thread "main" Assertion failed:

assert testSide ==~ Pattern.compile(stubSide.optionalPattern())
       |        |           |       |        |
       DESPAIR false       |       |        (org.springframework.cloud.contract.spec.internal.ClientDslProperty(DslProperty(clientValue:^WORKS$|^MIGHTY$|^DESPAIR$, serverValue:DESPAIR)))?
                            |       (org.springframework.cloud.contract.spec.internal.ClientDslProperty(DslProperty(clientValue:^WORKS$|^MIGHTY$|^DESPAIR$, serverValue:DESPAIR)))?
                            (org.springframework.cloud.contract.spec.internal.ClientDslProperty(DslProperty(clientValue:^WORKS$|^MIGHTY$|^DESPAIR$, serverValue:DESPAIR)))?

        at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:420)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:663)
        at org.springframework.cloud.contract.spec.internal.Common.assertThatSidesMatch(Common.groovy:236)
```

Changing the contract to use `regex('^WORKS$|^MIGHTY$|^DESPAIR$')` instead of `anyOf()` appears to work ok. 

Is this a bug, or have I misunderstood the intended usage?

**Comment by andrejthegreat** [comment]
Hi, I am experiencing the same issue in Spring Cloud Contract 2.1.2-RELEASE. Also seems that more functions are causing problems when combined with `optional()`.

For example  `anyNonEmptyString()` :
``` 
...
body (
      errorDetails: $(optional(anyNonEmptyString()))  
)
...
```

generates this test in producer which ofc always fails

```
...
assertThatJson(parsedJson).field("['errorDetails']").matches("(ServerDslProperty(DslProperty(clientValue:LUOIGPGEDFJQLNEUAVKJ, serverValue:[\\S\\s]+)))?");
...
```
