### ISSUE TITLE
error running spring-cloud-contract-stub-runner-boot with contracts written in kotlin

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-contract#1221]
Once stubs are generated I tried to use `spring-cloud-contract-stub-runner-boot` version `2.2.0.M2` but I got the stacktrace below

Also, there was a warning regarding to `com.fasterxml.jackson.module:jackson-module-kotlin` too

```
java -jar stub-runner.jar --stubrunner.ids="com.example:producer:9876" --stubrunner.stubsMode=LOCAL

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::             (v2.2.0.M5)

2019-09-21 18:59:01.493  INFO 78039 --- [           main] o.s.c.c.s.server.StubRunnerBoot          : Starting StubRunnerBoot v2.2.0.M2 on MACDIGITAL21.local with PID 78039 (/Users/eddu/Desktop/JConfColombia19/spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar started by eddu in /Users/eddu/Desktop/JConfColombia19)
2019-09-21 18:59:01.497  INFO 78039 --- [           main] o.s.c.c.s.server.StubRunnerBoot          : No active profile set, falling back to default profiles: default
2019-09-21 18:59:03.401  INFO 78039 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2019-09-21 18:59:03.424  INFO 78039 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-09-21 18:59:03.425  INFO 78039 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-09-21 18:59:03.599  INFO 78039 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-09-21 18:59:03.600  INFO 78039 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1589 ms
2019-09-21 18:59:03.746  INFO 78039 --- [           main] o.s.c.c.s.AetherStubDownloaderBuilder    : Will download stubs and contracts via Aether
2019-09-21 18:59:03.749  INFO 78039 --- [           main] o.s.c.c.stubrunner.AetherStubDownloader  : Remote repos not passed but the switch to work offline was set. Stubs will be used from your local Maven repository.
2019-09-21 18:59:03.887  INFO 78039 --- [           main] o.s.c.c.stubrunner.AetherStubDownloader  : Desired version is [+] - will try to resolve the latest version
2019-09-21 18:59:03.905  INFO 78039 --- [           main] o.s.c.c.stubrunner.AetherStubDownloader  : Resolved version is [0.0.1-SNAPSHOT]
2019-09-21 18:59:03.923  INFO 78039 --- [           main] o.s.c.c.stubrunner.AetherStubDownloader  : Resolved artifact [com.example:producer:jar:stubs:0.0.1-SNAPSHOT] to /Users/eddu/.m2/repository/com/example/producer/0.0.1-SNAPSHOT/producer-0.0.1-SNAPSHOT-stubs.jar
2019-09-21 18:59:03.924  INFO 78039 --- [           main] o.s.c.c.stubrunner.AetherStubDownloader  : Unpacking stub from JAR [URI: file:/Users/eddu/.m2/repository/com/example/producer/0.0.1-SNAPSHOT/producer-0.0.1-SNAPSHOT-stubs.jar]
2019-09-21 18:59:03.941  INFO 78039 --- [           main] o.s.c.c.stubrunner.AetherStubDownloader  : Unpacked file to [/var/folders/yy/r8r92hyj2nv_rg9k9y04wyxh0000gq/T/contracts-1569110343924-0]
2019-09-21 18:59:04.574  WARN 78039 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpStubsController' defined in URL [jar:file:/Users/eddu/Desktop/JConfColombia19/spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar!/BOOT-INF/lib/spring-cloud-contract-stub-runner-2.2.0.M2.jar!/org/springframework/cloud/contract/stubrunner/server/HttpStubsController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchStubRunner' defined in org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.stubrunner.BatchStubRunner]: Factory method 'batchStubRunner' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
2019-09-21 18:59:04.579  INFO 78039 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-09-21 18:59:04.591 ERROR 78039 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Failed to destroy the filter named [Tomcat WebSocket (JSR356) Filter] of type [org.apache.tomcat.websocket.server.WsFilter]

java.lang.AbstractMethodError: null
	at org.apache.catalina.core.ApplicationFilterConfig.release(ApplicationFilterConfig.java:301) ~[tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.core.StandardContext.filterStop(StandardContext.java:4562) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5385) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_201]
	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_201]
	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:473) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:994) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:466) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.stopTomcat(TomcatWebServer.java:269) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.stop(TomcatWebServer.java:324) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.stopAndReleaseWebServer(ServletWebServerApplicationContext.java:306) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:746) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:396) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1225) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.cloud.contract.stubrunner.server.StubRunnerBoot.main(StubRunnerBoot.java:30) [classes!/:2.2.0.M2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar:2.2.0.M2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar:2.2.0.M2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar:2.2.0.M2]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar:2.2.0.M2]

2019-09-21 18:59:04.603  INFO 78039 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-09-21 18:59:04.606 ERROR 78039 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpStubsController' defined in URL [jar:file:/Users/eddu/Desktop/JConfColombia19/spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar!/BOOT-INF/lib/spring-cloud-contract-stub-runner-2.2.0.M2.jar!/org/springframework/cloud/contract/stubrunner/server/HttpStubsController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchStubRunner' defined in org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.stubrunner.BatchStubRunner]: Factory method 'batchStubRunner' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:779) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1359) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1205) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:877) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:746) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:396) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1225) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214) [spring-boot-2.2.0.M5.jar!/:2.2.0.M5]
	at org.springframework.cloud.contract.stubrunner.server.StubRunnerBoot.main(StubRunnerBoot.java:30) [classes!/:2.2.0.M2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar:2.2.0.M2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar:2.2.0.M2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar:2.2.0.M2]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [spring-cloud-contract-stub-runner-boot-2.2.0.M2.jar:2.2.0.M2]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchStubRunner' defined in org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.stubrunner.BatchStubRunner]: Factory method 'batchStubRunner' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:637) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1339) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1178) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1283) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1203) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:866) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:770) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.stubrunner.BatchStubRunner]: Factory method 'batchStubRunner' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:632) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	... 41 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerApplicationExtensionPointsAndExtensionsFrom(KotlinCoreEnvironment.kt:561) ~[kotlin-compiler-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createApplicationEnvironment(KotlinCoreEnvironment.kt:514) ~[kotlin-compiler-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.getOrCreateApplicationEnvironmentForProduction(KotlinCoreEnvironment.kt:470) ~[kotlin-compiler-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:424) ~[kotlin-compiler-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.scripting.repl.GenericReplChecker.<init>(GenericReplChecker.kt:53) ~[kotlin-scripting-compiler-impl-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.scripting.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:43) ~[kotlin-scripting-compiler-impl-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.scripting.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:40) ~[kotlin-scripting-compiler-impl-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:47) ~[kotlin-script-util-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:38) ~[kotlin-script-util-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[kotlin-stdlib-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplCompiler(KotlinJsr223JvmLocalScriptEngine.kt) ~[kotlin-script-util-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:53) ~[kotlin-script-util-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:38) ~[kotlin-script-util-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[kotlin-stdlib-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getLocalEvaluator(KotlinJsr223JvmLocalScriptEngine.kt) ~[kotlin-script-util-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplEvaluator(KotlinJsr223JvmLocalScriptEngine.kt:55) ~[kotlin-script-util-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.createState(KotlinJsr223JvmLocalScriptEngine.kt:59) ~[kotlin-script-util-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.createState$default(KotlinJsr223JvmScriptEngineBase.kt:46) ~[kotlin-compiler-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.getCurrentState(KotlinJsr223JvmScriptEngineBase.kt:53) ~[kotlin-compiler-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.nextCodeLine(KotlinJsr223JvmScriptEngineBase.kt:44) ~[kotlin-compiler-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:59) ~[kotlin-compiler-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:33) ~[kotlin-compiler-embeddable-1.3.41.jar!/:1.3.41-release-150 (1.3.41)]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249) ~[na:1.8.0_201]
	at org.springframework.cloud.contract.spec.internal.KotlinContractConverter$convertFrom$eval$1.invoke(KotlinContractConverter.kt:50) ~[spring-cloud-contract-spec-kotlin-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.spec.internal.KotlinContractConverter$convertFrom$eval$1.invoke(KotlinContractConverter.kt:31) ~[spring-cloud-contract-spec-kotlin-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.spec.internal.KotlinContractConverter.withUpdatedClassloader(KotlinContractConverter.kt:68) ~[spring-cloud-contract-spec-kotlin-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.spec.internal.KotlinContractConverter.convertFrom(KotlinContractConverter.kt:46) ~[spring-cloud-contract-spec-kotlin-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.verifier.util.ContractScanner$1.visitFile(ContractScanner.groovy:93) ~[spring-cloud-contract-verifier-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.verifier.util.ContractScanner$1.visitFile(ContractScanner.groovy) ~[spring-cloud-contract-verifier-2.2.0.M2.jar!/:2.2.0.M2]
	at java.nio.file.Files.walkFileTree(Files.java:2670) ~[na:1.8.0_201]
	at java.nio.file.Files.walkFileTree(Files.java:2742) ~[na:1.8.0_201]
	at org.springframework.cloud.contract.verifier.util.ContractScanner.collectContractDescriptors(ContractScanner.groovy:77) ~[spring-cloud-contract-verifier-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.StubRepository.contractDescriptors(StubRepository.java:161) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.StubRepository.contracts(StubRepository.java:102) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.StubRepository.<init>(StubRepository.java:76) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.StubRunner.<init>(StubRunner.java:70) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.StubRunnerFactory.createStubRunner(StubRunnerFactory.java:177) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.StubRunnerFactory.createStubRunner(StubRunnerFactory.java:171) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.StubRunnerFactory.createStubsFromServiceConfiguration(StubRunnerFactory.java:90) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.BatchStubRunnerFactory.buildBatchStubRunner(BatchStubRunnerFactory.java:69) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration.batchStubRunner(StubRunnerConfiguration.java:85) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration$$EnhancerBySpringCGLIB$$19fd5875.CGLIB$batchStubRunner$0(<generated>) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration$$EnhancerBySpringCGLIB$$19fd5875$$FastClassBySpringCGLIB$$108ffb95.invoke(<generated>) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.2.0.RC1.jar!/:5.2.0.RC1]
	at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration$$EnhancerBySpringCGLIB$$19fd5875.batchStubRunner(<generated>) ~[spring-cloud-contract-stub-runner-2.2.0.M2.jar!/:2.2.0.M2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.0.RC1.jar!/:5.2.0.RC1]
	... 42 common frames omitted
```

**Comment by marcingrzejszczak** [comment]
hey @eddumelendez is it also a problem with the latest snapshots?

**Comment by eddumelendez** [comment]
@marcingrzejszczak same error with the latest snapshots

**Comment by marcingrzejszczak** [comment]
@eddumelendez any chance for a small sample?

**Comment by eddumelendez** [comment]
sure @marcingrzejszczak you can take a look at `producer` in this [repo](https://github.com/eddumelendez/kotlin-everywhere-gdglima-demo)
