### ISSUE TITLE
spring-cloud-contract-wiremock: WebServiceIOException when run all tests

### ISSUE THREAD

**Issue by izacristina** [spring-cloud/spring-cloud-contract#1288]
**Describe the bug**
I'm using the 2.2.0.RELEASE version of spring-cloud-contract-wiremock with random port

I have a test that calls spring's sendAndReceive to make a SOAP request to localhost and I have a stub for this request. When I run this test alone, it passes, but when I run all tests, this test fail with a WebServiceIOException caused by a NoHttpResponseException while sendAndReceive:

```csharp
org.springframework.ws.client.WebServiceIOException: I/O error: localhost:11230 failed to respond; nested exception is org.apache.http.NoHttpResponseException: localhost:11230 failed to respond
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:561 undefined)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390 undefined)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:378 undefined)
	at br.com.project_name.directory.CustomClient.callToSendAndReceive(CustomClient.java:35 undefined)
	at br.com.project_name.directory.CustomClient.CustomClientIntegrationTest.shouldRequestContractsWithSuccess(CustomClientIntegrationTest.java:40 undefined)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62 undefined)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43 undefined)
	at java.lang.reflect.Method.invoke(Method.java:498 undefined)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50 undefined)
	at org.junit.internalners.model.ReflectiveCallable.run.run(ReflectiveCallable.java:12 undefined)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47 undefined)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17 undefined)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73 undefined)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83 undefined)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26 undefined)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75 undefined)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86 undefined)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84 undefined)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325 undefined)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251 undefined)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97 undefined)
	at org.junitners.ParentRunner$3.run.run(ParentRunner.java:290 undefined)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71 undefined)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288 undefined)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58 undefined)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268 undefined)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26 undefined)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61 undefined)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70 undefined)
	at org.junitners.ParentRunner.run.run(ParentRunner.java:363 undefined)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190 undefined)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114 undefined)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57 undefined)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66 undefined)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51 undefined)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62 undefined)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43 undefined)
	at java.lang.reflect.Method.invoke(Method.java:498 undefined)
	at org.gradle.internal.ReflectionDispatch.dispatch.dispatch(ReflectionDispatch.java:35 undefined)
	at org.gradle.internal.ReflectionDispatch.dispatch.dispatch(ReflectionDispatch.java:24 undefined)
	at org.gradle.internal.ContextClassLoaderDispatch.dispatch.dispatch(ContextClassLoaderDispatch.java:32 undefined)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93 undefined)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108 undefined)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62 undefined)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43 undefined)
	at java.lang.reflect.Method.invoke(Method.java:498 undefined)
	at org.gradle.internal.ReflectionDispatch.dispatch.dispatch(ReflectionDispatch.java:35 undefined)
	at org.gradle.internal.ReflectionDispatch.dispatch.dispatch(ReflectionDispatch.java:24 undefined)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146 undefined)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128 undefined)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404 undefined)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63 undefined)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46 undefined)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149 undefined)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624 undefined)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55 undefined)
	at java.lang.Thread.run(Thread.java:748 undefined)
Caused by: org.apache.http.NoHttpResponseException: localhost:11230 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141 undefined)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56 undefined)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259 undefined)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163 undefined)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165 undefined)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273 undefined)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125 undefined)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272 undefined)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185 undefined)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89 undefined)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110 undefined)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185 undefined)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83 undefined)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108 undefined)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56 undefined)
	at org.springframework.ws.transport.http.HttpComponentsConnection.onSendAfterWrite(HttpComponentsConnection.java:121 undefined)
	at org.springframework.ws.transport.AbstractWebServiceConnection.send(AbstractWebServiceConnection.java:48 undefined)
	at org.springframework.ws.client.core.WebServiceTemplate.sendRequest(WebServiceTemplate.java:658 undefined)
	at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:606 undefined)
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555 undefined)
	... 60 common frames omitted
```

Can you guys help me?

**Comment by marcingrzejszczak** [comment]
Can you show your test please?

**Comment by izacristina** [comment]
I can't show the code but I created a similar test to show:

```java

@Autowired
CustomClient customClient;

public void shouldRequestContractsWithSuccess() {

        stubFor(post(urlPathEqualTo("/some/url/v1"))
                .willReturn(aResponse()
                        .withBodyFile("contracts/response.xml")));

        Map<String, Object> data = newHashMap();
        data.put("id", "");
        CustomRequest request = new CustomRequest("Teste", data);

        Optional<CustomResponseList> result = customClient.callToSendAndReceive(request);

        verify(postRequestedFor(urlPathEqualTo("/some/url/v1")));

        assertThat(result).isPresent();
        assertThat(result.get().getCustomList().get(0).getCode()).isEqualTo("1031000000001");
    }
```

**Comment by marcingrzejszczak** [comment]
Try to do this instead

```
@Autowired
CustomClient customClient;


@Autowired
WireMockServer wireMock;

public void shouldRequestContractsWithSuccess() {

        wireMock.stubFor(post(urlPathEqualTo("/some/url/v1"))
                .willReturn(aResponse()
                        .withBodyFile("contracts/response.xml")));

        Map<String, Object> data = newHashMap();
        data.put("id", "");
        CustomRequest request = new CustomRequest("Teste", data);

        Optional<CustomResponseList> result = customClient.callToSendAndReceive(request);

        wireMock.verify(postRequestedFor(urlPathEqualTo("/some/url/v1")));

        assertThat(result).isPresent();
        assertThat(result.get().getCustomList().get(0).getCode()).isEqualTo("1031000000001");
    }
```

**Comment by izacristina** [comment]
shoud I remove @AutoConfigureWireMock?

**Comment by marcingrzejszczak** [comment]
No, why?

**Comment by izacristina** [comment]
I thought that @AutoConfigureWireMock would provide the WireMockServer. Should I create the bean?

<img width="477" alt="Captura de Tela 2019-12-13 às 12 02 07" src="https://user-images.githubusercontent.com/14032043/70809578-d5f81680-1da0-11ea-8d0a-071c7dc7dc00.png">

**Comment by marcingrzejszczak** [comment]
No, it will create one.

**Comment by izacristina** [comment]
I'm having the same error D:

**Comment by marcingrzejszczak** [comment]
I'm sorry, without a test sample it will be extremely hard to help you. Maybe try removing the `@AutoConfigueWireMock` annotation and manualy control the lifecycle of WireMock? I would like to help you but currenly, without the option to see the code, I'm only guessing what the problem might be.

**Comment by izacristina** [comment]
Using the autowired WireMockServer, a @Before method with wireMock.resetAll() and the version 2.1.1 of spring-cloud-contract-wiremock all tests have passed.

Thank you

**Comment by marcingrzejszczak** [comment]
Don't mention it

**Comment by driversti** [comment]
I faced the same problem using the 2.2.2.RELEASE.
But the difference is that I use Response Templates based on JSON.
I have the following setup

    @TestConfiguration
    class BeanTestConfiguration {

      @Bean("marketClient")
      MarketplaceClient marketClient(
            @Autowired RestTemplateBuilder restTemplateBuilder,
            @Autowired AuthenticationService authenticationService,
            @Autowired CommonHeadersComposer commonHeadersComposer) {
          new MarketplaceClient(format("%s:%s", erepublikHost, wireMockPort),
                authenticationService, restTemplateBuilder, commonHeadersComposer)
      }
    }

============

    @WebMvcTest
    @Import([BeanTestConfiguration])
    @AutoConfigureWebClient
    @AutoConfigureWireMock(port = 0)
    class WebTest extends Specification {
        @Autowired
        MockMvc mockMvc
        @Autowired
        ObjectMapper objectMapper
        @Autowired
        WireMockServer wireMockServer
    }

==================

    class AircraftRawMarketControllerWebTest extends WebTest {

        void setupSpec() {
            wireMockServer.resetAll()
        }

        @Unroll
        def "as a simple user, I want to get the first page of aircraft raw materials prices with #quality quality for #country"() {
            when: "we make a request for aircraft raw materials"
            def response = mockMvc.perform(get("/market/$country.id/aircraft-raw")
                .accept(APPLICATION_JSON))
                .andReturn().response

            then: "we expect to get relevant values"
            response.status == OK.value()
            def marketResponse = objectMapper.readValue(response.contentAsString, MarketplaceResponse)
            with(marketResponse) {
                currency == country.currency
                offers.each { offer ->
                    with(offer) {
                        offer.countryId == country.id
                        offer.industryId == AIRCRAFT_RAW.id
                        offer.quality == quality.value
                    }
                }
            }

            where:
            country | quality
            ROMANIA   | Q1
        }
    }

======================

    {
      "request": {
        "method": "POST",
        "url": "/economy/marketplaceAjax",
        "headers": {
          "Content-Type": {
            "equalTo": "application/x-www-form-urlencoded"
          }
        },
        "bodyPatterns": [
          {
            "equalTo": "countryId=1&industryId=24&quality=1&orderBy=price_asc&currentPage=1&ajaxMarket=1&_token=test_token"
          }
        ]
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "jsonBody": {
          "offers": [
            {
              "id": 66227309,
              "country_id": 1,
              "industry_id": 24,
              "citizen_id": 5275428,
              "amount": 325,
              "price": 286.138614,
              "customization_level": 1,
              "name": "alphazulu",
              "is_for_export": 52,
              "priceWithTaxes": 289
            }
          ],
          "currency": "RON",
          "can_buy": false,
          "pages": 1
        }
      }
    }

but without success. I get the following

    org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:12374/economy/marketplaceAjax": localhost:12374 failed to respond; nested exception is org.apache.http.NoHttpResponseException: localhost:12374 failed to respond
	at com.github.driversti.erepsistant.market.aircraftraw.AircraftRawMarketControllerWebTest.as a simple user, I want to get the first page of aircraft raw materials prices with #quality quality for #country(AircraftRawMarketControllerWebTest.groovy:24)
What I'm doing wrong?

**Comment by OlgaMaciaszek** [comment]
Hi, @driversti, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by driversti** [comment]
Hello, @OlgaMaciaszek .
Unfortunately, I don't know how to reproduce the issue in accordance with your requirement. However, the issue exists in this commit https://github.com/driversti/erepsistant/tree/9c00f50752af7b064a8d636bced838334a219a16/src

**Comment by marcingrzejszczak** [comment]
I can't even click at the commit. Please create a small project that will help us replicate the issue
