### ISSUE TITLE
KafkaStubRunnerSpec fails with NoSuchMethodError

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-contract#1383]
```
2020-04-17 15:42:26.622 DEBUG 14771 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception

java.lang.NoSuchMethodError: org.apache.kafka.common.utils.Exit.addShutdownHook(Ljava/lang/String;Ljava/lang/Runnable;)V
	at org.apache.kafka.test.TestUtils.tempDirectory(TestUtils.java:267) ~[kafka-clients-2.5.0-test.jar:na]
	at org.apache.kafka.test.TestUtils.tempDirectory(TestUtils.java:237) ~[kafka-clients-2.5.0-test.jar:na]
	at org.apache.kafka.test.TestUtils.tempDirectory(TestUtils.java:247) ~[kafka-clients-2.5.0-test.jar:na]
	at kafka.utils.TestUtils$.tempDir(TestUtils.scala:104) ~[kafka_2.12-2.5.0-test.jar:na]
	at kafka.utils.TestUtils.tempDir(TestUtils.scala) ~[kafka_2.12-2.5.0-test.jar:na]
	at org.springframework.kafka.test.EmbeddedKafkaBroker$EmbeddedZookeeper.<init>(EmbeddedKafkaBroker.java:616) ~[spring-kafka-test-2.5.0.BUILD-SNAPSHOT.jar:2.5.0.BUILD-SNAPSHOT]
	at org.springframework.kafka.test.EmbeddedKafkaBroker.afterPropertiesSet(EmbeddedKafkaBroker.java:282) ~[spring-kafka-test-2.5.0.BUILD-SNAPSHOT.jar:2.5.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.6.BUILD-SNAPSHOT.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.6.BUILD-SNAPSHOT.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:407) ~[spring-beans-5.2.6.BUILD-SNAPSHOT.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.kafka.test.context.EmbeddedKafkaContextCustomizer.customizeContext(EmbeddedKafkaContextCustomizer.java:116) ~[spring-kafka-test-2.5.0.BUILD-SNAPSHOT.jar:2.5.0.BUILD-SNAPSHOT]
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextCustomizerAdapter.initialize(SpringBootContextLoader.java:298) ~[spring-boot-test-2.3.0.BUILD-SNAPSHOT.jar:2.3.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626) ~[spring-boot-2.3.0.BUILD-SNAPSHOT.jar:2.3.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370) ~[spring-boot-2.3.0.BUILD-SNAPSHOT.jar:2.3.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.3.0.BUILD-SNAPSHOT.jar:2.3.0.BUILD-SNAPSHOT]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:122) [spring-boot-test-2.3.0.BUILD-SNAPSHOT.jar:2.3.0.BUILD-SNAPSHOT]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99) [spring-test-5.2.6.BUILD-SNAPSHOT.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) [spring-test-5.2.6.BUILD-SNAPSHOT.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123) [spring-test-5.2.6.BUILD-SNAPSHOT.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190) [spring-test-5.2.6.BUILD-SNAPSHOT.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132) [spring-test-5.2.6.BUILD-SNAPSHOT.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244) [spring-test-5.2.6.BUILD-SNAPSHOT.jar:5.2.6.BUILD-SNAPSHOT]
	at org.spockframework.spring.SpringTestContextManager.prepareTestInstance(SpringTestContextManager.java:56) [spock-spring-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.spring.SpringInterceptor.interceptInitializerMethod(SpringInterceptor.java:43) [spock-spring-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:24) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:475) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.runInitializer(BaseSpecRunner.java:341) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.runInitializer(BaseSpecRunner.java:336) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:274) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:266) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:260) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:243) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:235) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:185) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:95) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:81) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:73) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:64) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63) [spock-core-1.3-groovy-2.5.jar:1.3]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115) [junit-4.12.jar:4.12]
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43) [junit-vintage-engine-5.6.1.jar:5.6.1]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:1.8.0_242]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_242]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_242]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_242]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_242]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:1.8.0_242]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_242]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[na:1.8.0_242]
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82) ~[junit-vintage-engine-5.6.1.jar:5.6.1]
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73) ~[junit-vintage-engine-5.6.1.jar:5.6.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248) ~[junit-platform-launcher-1.6.1.jar:1.6.1]
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211) ~[junit-platform-launcher-1.6.1.jar:1.6.1]
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226) ~[junit-platform-launcher-1.6.1.jar:1.6.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199) ~[junit-platform-launcher-1.6.1.jar:1.6.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132) ~[junit-platform-launcher-1.6.1.jar:1.6.1]
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154) ~[surefire-junit-platform-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:127) ~[surefire-junit-platform-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377) ~[surefire-booter-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138) ~[surefire-booter-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465) ~[surefire-booter-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451) ~[surefire-booter-3.0.0-M4.jar:3.0.0-M4]

2020-04-17 15:42:26.624 ERROR 14771 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.apache.kafka.test.TestUtils.tempDirectory(TestUtils.java:267)

The following method did not exist:

    org.apache.kafka.common.utils.Exit.addShutdownHook(Ljava/lang/String;Ljava/lang/Runnable;)V

The method's class, org.apache.kafka.common.utils.Exit, is available from the following locations:

    jar:file:/home/jenkins/.m2/repository/org/apache/kafka/kafka-clients/2.4.1/kafka-clients-2.4.1.jar!/org/apache/kafka/common/utils/Exit.class

It was loaded from the following location:

    file:/home/jenkins/.m2/repository/org/apache/kafka/kafka-clients/2.4.1/kafka-clients-2.4.1.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.kafka.common.utils.Exit
```

**Comment by OlgaMaciaszek** [comment]
Cannot reproduce, possibly a corrupt dependency jar was being pulled by CI. Unignoring that test.
