### ISSUE TITLE
When I generateClientStubs I get an error IllegalArgumentException: json can not be null

### ISSUE THREAD

**Issue by PiotrB-Max** [spring-cloud/spring-cloud-contract#1422]
After update spring up to 2.3.0.RELEASE version and while trying generate client stubs i get this error
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateClientStubs'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
...
Caused by: java.lang.IllegalArgumentException: json can not be null
        at com.jayway.jsonpath.internal.Utils.notNull(Utils.java:316)
        at com.jayway.jsonpath.internal.JsonContext.<init>(JsonContext.java:47)
        at com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:38)
        at com.jayway.jsonpath.JsonPath.parse(JsonPath.java:599)
        at com.jayway.jsonpath.JsonPath$parse.call(Unknown Source)
        at org.springframework.cloud.contract.verifier.dsl.wiremock.BaseWireMockStubStrategy.parseBody(BaseWireMockStubStrategy.groovy:98)
```

My contract looks like this:
```
org.springframework.cloud.contract.spec.Contract.make {
  request {
    method GET()
    url "/foo"
    headers {
      contentType(applicationJson())
    }
  }
  response {
    status 201
    headers {
      contentType(applicationJson())
    }
    body([
      clientId: "1234"
    ])
  }
}
```

Dependencies
org.springframework.boot:spring-boot-starter-web:2.3.0.RELEASE
org.springframework.cloud:spring-cloud-starter-contract-stub-runner:2.2.3.RELEASE
org.springframework.cloud:spring-cloud-starter-contract-verifier:2.2.3.RELEASE

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

Apart from that you have a JSON content type and no body on the request side. Most likely that's the case. However, there shouldn't be such exception so thank you for filing the issue

**Comment by PiotrB-Max** [comment]
Thank you. I've fixed the formatting.

The JSON content typ doesn't matter. There's always a bug

**Comment by marcingrzejszczak** [comment]
Can you create a sample that replicates this? Line 98 of `BaseWireMockStubStrategy` is a comment :grimacing: .

**Comment by PiotrB-Max** [comment]
I created a new project and it worked.
I compared it with my previous project and it turned out that I had to add the following dependency:
```
buildscript {
  ...
  dependencies {
    ...
    classpath 'org.springframework.cloud:spring-cloud-contract-gradle-plugin:2.2.3.RELEASE'
    }
}
```
