### ISSUE TITLE
Problem with SCC YAML to PACT convertation

### ISSUE THREAD

**Issue by Daemon2017** [spring-cloud/spring-cloud-contract#1572]
**Describe the bug**
Versions:
id "org.springframework.cloud.contract" version "2.2.3.RELEASE"
mavenBom "org.springframework.cloud:spring-cloud-contract-dependencies:2.1.3.RELEASE"

Steps "clean test" works perfect, but I'm getting an error, when I'm trying to run step "convertContract":
_Caused by: java.lang.UnsupportedOperationException: use the object(String name) form_

> Exception in thread "main" java.lang.IllegalStateException: java.lang.UnsupportedOperationException: use the object(String name) form
> 	at org.springframework.cloud.contract.verifier.util.ToFileContractsTransformer.storeContractsAsFiles(ToFileContractsTransformer.groovy:103)
> 	at org.springframework.cloud.contract.verifier.util.ToFileContractsTransformer.main(ToFileContractsTransformer.groovy:55)
> Caused by: java.lang.UnsupportedOperationException: use the object(String name) form
> Caused by: java.lang.UnsupportedOperationException: use the object(String name) form
> 
> 	at au.com.dius.pact.consumer.dsl.PactDslJsonBody.object(PactDslJsonBody.java:520)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter.traverse(BodyConverter.groovy:85)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter.access$0(BodyConverter.groovy)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter$_processMap_closure2.doCall(BodyConverter.groovy:151)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
> 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
> 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
> 	at groovy.lang.Closure.call(Closure.java:405)
> 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
> 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122)
> 	at com.sun.proxy.$Proxy12.accept(Unknown Source)
> 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter.processMap(BodyConverter.groovy:133)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter.traverse(BodyConverter.groovy:87)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter.access$0(BodyConverter.groovy)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter$_processCollection_closure1.doCall(BodyConverter.groovy:127)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
> 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
> 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
> 	at groovy.lang.Closure.call(Closure.java:405)
> 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
> 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122)
> 	at com.sun.proxy.$Proxy11.accept(Unknown Source)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter.processCollection(BodyConverter.groovy:109)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter.traverse(BodyConverter.groovy:96)
> 	at org.springframework.cloud.contract.verifier.spec.pact.BodyConverter.toPactBody(BodyConverter.groovy:56)
> 	at org.springframework.cloud.contract.verifier.spec.pact.RequestResponsePactCreator.createPactDslRequestWithPath(RequestResponsePactCreator.groovy:143)
> 	at org.springframework.cloud.contract.verifier.spec.pact.RequestResponsePactCreator.access$3(RequestResponsePactCreator.groovy)
> 	at org.springframework.cloud.contract.verifier.spec.pact.RequestResponsePactCreator$_createFromContract_closure1.doCall(RequestResponsePactCreator.groovy:59)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
> 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
> 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
> 	at groovy.lang.Closure.call(Closure.java:405)
> 	at groovy.lang.Closure.call(Closure.java:421)
> 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330)
> 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315)
> 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356)
> 	at org.springframework.cloud.contract.verifier.spec.pact.RequestResponsePactCreator.createFromContract(RequestResponsePactCreator.groovy:55)
> 	at org.springframework.cloud.contract.verifier.spec.pact.PactContractConverter.convertTo(PactContractConverter.groovy:77)
> 	at org.springframework.cloud.contract.verifier.spec.pact.PactContractConverter.convertTo(PactContractConverter.groovy)
> 	at org.springframework.cloud.contract.verifier.util.ToFileContractsTransformer.storeContractsAsFiles(ToFileContractsTransformer.groovy:80)
> 	... 1 more

What's wrong? Looks like converter can't transform array of objects in the body's root.

**Sample**
```
description: >
  Sends data gets data
name: Sends data gets data
request:
  method: POST
  url: /getRs
  headers:
    Content-type: application/json
  body:
    - name:
        firstName: 'Grizvold'
        lastName: 'Smith'
      other:
        age: 55
    - name:
        firstName: 'Adria'
        lastName: 'Witch'
      other:
        age: 45
response:
  async: true
  status: 200
  headers:
    Content-Type: application/json
  body:
    - state: 'ok'
      errorCode: '0'
    - state: 'Error! Already exists.'
      errorCode: '001'
```

**Comment by Daemon2017** [comment]
Works fine with v2.2.5 :)
