### ISSUE TITLE
JsonException: Unrecognized field \"size\" (class com.github.tomakehurst.wiremock.stubbing.StubMapping), not marked as ignorable

### ISSUE THREAD

**Issue by sudhirtumati** [spring-cloud/spring-cloud-contract#1583]
I am trying to use `spring-cloud-contract-wiremock` to mock an external API call during my tests. However I get below error when I am trying to run the test

```
Caused by: com.github.tomakehurst.wiremock.common.JsonException: {
  "errors" : [ {
    "code" : 10,
    "source" : {
      "pointer" : "/size"
    },
    "title" : "Error parsing JSON",
    "detail" : "Unrecognized field \"size\" (class com.github.tomakehurst.wiremock.stubbing.StubMapping), not marked as ignorable"
  } ]
}
	at com.github.tomakehurst.wiremock.common.JsonException.fromJackson(JsonException.java:53)
	at com.github.tomakehurst.wiremock.common.Json.read(Json.java:55)
	at com.github.tomakehurst.wiremock.stubbing.StubMapping.buildFrom(StubMapping.java:72)
	at org.springframework.cloud.contract.wiremock.WireMockStubMapping.buildFrom(WireMockStubMapping.java:31)
	at org.springframework.cloud.contract.wiremock.WireMockConfiguration.registerStubs(WireMockConfiguration.java:213)
	at org.springframework.cloud.contract.wiremock.WireMockConfiguration.resetMappings(WireMockConfiguration.java:189)
	at org.springframework.cloud.contract.wiremock.WireMockConfiguration.reRegisterServerWithResetMappings(WireMockConfiguration.java:175)
	at org.springframework.cloud.contract.wiremock.WireMockConfiguration.init(WireMockConfiguration.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 85 more
```

I have below files under classpath
```
src/test/resources/bb_wiremock/mappings/mapping-projects-APP1-repos-MOD1-pull-requests-9-activities-UniXI.json
src/test/resources/bb_wiremock/__files/body-projects-APP1-repos-MOD1-pull-requests-9-activities-UniXI.json
```

**Test class:**
```
@SpringBootTest
@AutoConfigureMockMvc
@AutoConfigureWireMock(port = 0, stubs = "classpath:/bb_wiremock")
@TestPropertySource(properties = {
		"bitbucket.baseUrl=http://localhost:${wiremock.server.port}"
})
class BitbucketEventControllerTests {
...
...
}
```
Related stubs are generated using `wiremock-2.27.1`

Could you please check and advise?

**Comment by sudhirtumati** [comment]
Sample application to demonstrate the issue is available at [https://github.com/sudhirtumati/spring-cloud-contract-issue-1583](https://github.com/sudhirtumati/spring-cloud-contract-issue-1583)

**Comment by marcingrzejszczak** [comment]
I think you should set `@AutoConfigureWireMock(port = 0, stubs = "classpath:/bb_wiremock/mappings")`. If you set `stubs` then we're going all the files (including the `__files`) folder and try to read it as a stub mapping. Obviously that file is not a valid WireMock stub.

**Comment by sudhirtumati** [comment]
@marcingrzejszczak Indeed, the test works fine after changing stub location. Thank you very much for quick response.

**Comment by marcingrzejszczak** [comment]
No problem

**Comment by sudhirtumati** [comment]
Sorry for quickly commenting without testing other scenarios.

After changing the stub location, I get below error

```
org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Server Error: [{
"cause1":"java.io.FileNotFoundException: /home/sudhirtumati/dev/workspace/java/app_referential/src/test/resources/__files/body-projects-APP1-repos-MOD1-pull-requests-9-activities-UniXI.json (No such... (893 bytes)]
```

`__files` directory is available under `src/test/resources/bb_wiremock` folder but it is being searched under `src/test/resources` folder. Is there any way to configure `src/test/resources/bb_wiremock` as base dir?

**Comment by marcingrzejszczak** [comment]
We have a test for that - you can provide both values

```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = WiremockTestsApplication.class,
		properties = "app.baseUrl=http://localhost:${wiremock.server.port}", webEnvironment = WebEnvironment.NONE)
@AutoConfigureWireMock(port = 0, files = "classpath:/root/", stubs = "file:src/test/resources/io.stubs/mappings")
public class AutoConfigureWireMockStubsAndFilesApplicationTests {

	@Autowired
	private Service service;

	@Test
	public void contextLoads() throws Exception {
		assertThat(this.service.go()).isEqualToIgnoringWhitespace("{\"message\":\"Hello Root\"}");
	}

}
```

**Comment by sudhirtumati** [comment]
Thank you again. My test worked fine with below configuration

`@AutoConfigureWireMock(port = 0, files = "classpath:/bb_wiremock", stubs = "classpath:/bb_wiremock/mappings")`

For files `__files` directory shouldn't be included as part of the location but for stubs, `mappings` should be included. Isn't it confusing? WDYT?

**Comment by marcingrzejszczak** [comment]
I don't think so cause `files` and `stubs` concepts are coming from WireMock. `Stubs` mean where the WireMock stubs are. Those stubs can reference files. `files` show the root directory of where those flies are located. From there WireMock will look for `__files`. Of course we can improve the docs / javadocs. Are you interested in sending a PR?

**Comment by sudhirtumati** [comment]
I've just gone thru the documentation. In fact this behavior is clearly explained in [Using Files to Specify the Stub Bodies](https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#features-wiremock-using-files) section of the documentation.

Similar explanation in Javadoc would help others if they run into similar issue. I'll try to submit a PR with javadoc changes.

**Comment by marcingrzejszczak** [comment]
Great! Please file it against the `2.2.x` branch and I'll do the merge to `master` afterwards
