### ISSUE TITLE
Cannot add WireMock metadata using the metadata in Contract

### ISSUE THREAD

**Issue by aosorio1** [spring-cloud/spring-cloud-contract#1598]
**Describe the bug**
Creating a contract like this:
```
Contract.make {            
            metadata(
                    wiremock: [
                            stubMapping: [
                                    metadata: [
                                            foo: "bar"
                                    ]
                            ]
                    ]
            )
        }
}

```
will throw a `NullPointerException`:
```
Exception in thread "main" org.springframework.cloud.contract.verifier.converter.ConversionContractVerifierException: Unable to make conversion of client.groovy
	at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter.processFiles(RecursiveFilesConverter.java:145)
	at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverterApplication.main(RecursiveFilesConverterApplication.java:43)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:497)
	at java.base/java.util.HashMap.putAll(HashMap.java:785)
	at org.springframework.cloud.contract.verifier.wiremock.DefaultWireMockStubPostProcessor.setMetadata(DefaultWireMockStubPostProcessor.java:63)
	at org.springframework.cloud.contract.verifier.wiremock.DefaultWireMockStubPostProcessor.postProcess(DefaultWireMockStubPostProcessor.java:48)
```

PR to fix this problem:
https://github.com/spring-cloud/spring-cloud-contract/pull/1597

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/spring-cloud/spring-cloud-contract/pull/1597
