### ISSUE TITLE
java.lang.NoSuchMethodError: 'void org.codehaus.plexus.util.DirectoryScanner.setFilenameComparator(java.util.Comparator)'

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-contract#1677]
**Describe the bug**

Upgrading from Spring Cloud Contract from 3.0.2 to 3.0.3 and get the error
```

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:184)
	... 30 more
Caused by: java.lang.NoSuchMethodError: 'void org.codehaus.plexus.util.DirectoryScanner.setFilenameComparator(java.util.Comparator)'
	at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.getResources(PlexusIoFileResourceCollection.java:250)
	at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:561)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:221)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:199)
	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:1063)
	at org.springframework.cloud.contract.maven.verifier.GenerateStubsMojo.createStubJar(GenerateStubsMojo.java:147)
	at org.springframework.cloud.contract.maven.verifier.GenerateStubsMojo.execute(GenerateStubsMojo.java:127)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 30 more
	pom.xml	/temp	line 77	Maven Build Problem

```

in a fresh Spring Tools 4 for Eclipse install 4.11.0 (latest as of writing).

The key here is

```
			<plugin> 
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-maven-plugin</artifactId>
				<version>3.0.3</version>
				<extensions>true</extensions>   
					<configuration>
                        <testFramework>JUNIT5</testFramework>
						<testMode>EXPLICIT</testMode>
						<!-- incremental causes contract tests to not run on the build box - do not turn on -->
						<incrementalContractTests>false</incrementalContractTests>
						<incrementalContractStubs>false</incrementalContractStubs>
						<incrementalContractStubsJar>false</incrementalContractStubsJar>
					</configuration>				
			</plugin>
```

and removing `<incrementalContractStubsJar>false</incrementalContractStubsJar>`  stops the error (which I don't want to do )

If i look at the classpath it seems the default plexus-utils of 3.3.0 is being overridden with 3.0.24

**Sample**
Here is my pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.8</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>temp</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>temp</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
		<spring-cloud.version>2020.0.3</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-contract-stub-runner</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-contract-verifier</artifactId>
			<scope>test</scope>
		</dependency>		
			
		
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-contract-maven-plugin</artifactId>
		</dependency>
		        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
						<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-maven-plugin</artifactId>
				<version>3.0.3</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
 
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>  
			<plugin> 
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-maven-plugin</artifactId>
				<version>3.0.3</version>
				<extensions>true</extensions>   
					<configuration>
                                                 <testFramework>JUNIT5</testFramework>
						<testMode>EXPLICIT</testMode>
						<!-- incremental causes contract tests to not run on the build box - do not turn on -->
						<incrementalContractTests>false</incrementalContractTests>
						<incrementalContractStubs>false</incrementalContractStubs>
						<incrementalContractStubsJar>false</incrementalContractStubsJar>
					</configuration>				
			</plugin>
		</plugins>
	</build> 

</project>
```
Thanks

**Comment by davidmelia** [comment]
Apache Maven 3.8.1

**Comment by marcingrzejszczak** [comment]
Interesting. It does ring a bell though. I'll have to take a closer look.

**Comment by davidmelia** [comment]
Thanks - its very annoying in eclipse as you get a pop up every time you build! Ahhhhhh!!!

**Comment by marcingrzejszczak** [comment]
Are you able to setup a small sample we could use to investigate this?

**Comment by davidmelia** [comment]
@marcingrzejszczak  here is an example project https://github.com/davidmelia/spring-cloud-contract-wiremock-issue (Ignore the name)

Having a play it seems to be a problem with the config attribute incrementalContractStubsJar.  When I set to false I get the error which is interesting.
```


            <plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <version>3.0.3</version>
				<extensions>true</extensions> 
				<configuration>
                        <testFramework>JUNIT5</testFramework>
						<testMode>EXPLICIT</testMode>
						<incrementalContractTests>false</incrementalContractTests>
						<incrementalContractStubs>false</incrementalContractStubs>
						<incrementalContractStubsJar>false</incrementalContractStubsJar>     
```

Thanks

**Comment by marcingrzejszczak** [comment]
hey @michaldo does this ring a bell?

**Comment by marcingrzejszczak** [comment]
lol, I mean do you think that it's related to any work that you've been doing?

**Comment by michaldo** [comment]
You mistook me for someone else.

**Comment by michaldo** [comment]
> If i look at the classpath it seems the default plexus-utils of 3.3.0 is being overridden with 3.0.24

It must be **3.3.0**.
I don't have working Eclipse to verify but I suggest check Spring Tools 14, because it uses 3.3.0:
sts-4.14.0.RELEASE/plugins/org.eclipse.m2e.maven.runtime_1.18.3.20220227-1319/jars/plexus-utils-3.3.0.jar

**Comment by marcingrzejszczak** [comment]
@davidmelia can you double check that the problem still persists?

**Comment by davidmelia** [comment]
@marcingrzejszczak I have downloaded the new STS above and can confirm I no longer get the issue.

Thanks

**Comment by marcingrzejszczak** [comment]
Fantastic, thanks everybody!
