### ISSUE TITLE
Data written out of order on socket when `AutoConfigureWireMock` is enabled

### ISSUE THREAD

**Issue by workmanw** [spring-cloud/spring-cloud-contract#1678]
Originally reported here: https://github.com/spring-projects/spring-boot/issues/27143 

There is a theory this could be related to an antivirus software, but I have yet to confirm that for sure. It was discovered that the issue isn't reproducible if `spring-cloud-contract` is removed from the reproduction so it was suggested I open this issue. 

----------

I will start by saying this is an extremely weird issue involving file uploads > 65KB and TestRestTemplate. And since TestRestTemplate and RestTemplate both reply on the Apache HTTP client it's possible this isn't even a Spring issue. 

I have been debugging this for 4 days it's not clear to me why this is happening and I could use some help.

## Reproduction

Git repo containing reproduction: https://github.com/workmanw/spring-test-bug-demo

### Steps

1. Run `mvn clean test` one or more times **on Mac OS Big Sur**
** This is not reproducible on Linux, Docker or Mac OS Catalina.
2. You will see the following error:

```
2021-07-02 21:26:49.921  INFO 25652 --- [o-auto-1-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0x0d0x0a--6hXCZ7NXvctrRhMdQfCslrHNTVm930eH--0x0d0x0aPOST]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

## Explanation

What appears to be happening is that when files over 65K are uploaded this way the contents of the body in the buffer gets shifted around when it's sent over the wire.

The request body should look like this:

```
POST /v1/demo/upload HTTP/1.1
Content-Type: multipart/form-data;charset=UTF-8;boundary=jgV0Bpae6rNX-ZcB2FrJmBOVr8kS3yzAvq
Content-Length: 66203
Host: localhost:61694
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11)
Accept-Encoding: gzip,deflate

--jgV0Bpae6rNX-ZcB2FrJmBOVr8kS3yzAvq
Content-Disposition: form-data; name="file"; filename="SingleFile.txt"
Content-Type: text/plain
Content-Length: 66000

AAAAAAA...<66,000x A>...AAAAAAA
--jgV0Bpae6rNX-ZcB2FrJmBOVr8kS3yzAvq--
```

However with this reproduction, the last portion of the body gets shifted to the beginning of the request. Looks like this:

```
AAAAAAAAAA
--jgV0Bpae6rNX-ZcB2FrJmBOVr8kS3yzAvq--
POST /v1/demo/upload HTTP/1.1
Content-Type: multipart/form-data;charset=UTF-8;boundary=jgV0Bpae6rNX-ZcB2FrJmBOVr8kS3yzAvq
Content-Length: 66203
Host: localhost:61694
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11)
Accept-Encoding: gzip,deflate

--jgV0Bpae6rNX-ZcB2FrJmBOVr8kS3yzAvq
Content-Disposition: form-data; name="file"; filename="SingleFile.txt"
Content-Type: text/plain
Content-Length: 66000

AAAAAAAAAAA...<66,000x A>...
```

The above results in a malformed HTTP request that Tomcat is unable to parse. This results in the `Invalid character found in method name` error observed above.

### Observation

If a breakpoint is added to `Http11InputBuffer::parseRequestLine`, which is on the Tomcat receiving end, this can be observed by watching contents of the byteBuffer as its read from the socket.

![image](https://user-images.githubusercontent.com/825487/124340049-77f87300-db80-11eb-9c2c-cf20735584b7.png)

If a breakpoint is added to `SocketOutputStream::socketWrite`, which is on the test sending end, the contents can be observed as serialized correctly.

**Writing header:**
![image](https://user-images.githubusercontent.com/825487/124340513-bba0ac00-db83-11eb-8d90-773ed0dfb60f.png)

**Writing body:**
![image](https://user-images.githubusercontent.com/825487/124340520-c6f3d780-db83-11eb-9c2d-85cdece5fb81.png)

**Comment by workmanw** [comment]
We got to the root of the issue working with our corporate IT. It turns out that Apple made in 11.13.1 that broke the way a CrowdStrike module interacted with the Apple API. Specially CrowdStrike's Falcon EDR module. I apologize for not having any sources to cite, the only references I was given to the issue were behind private ticket systems :( . We disabled this module on could no longer reproduce the issue.

I'm closing this issue now. I apologize if anyone's time was wasted by this.
