### ISSUE TITLE
Exception verifying contract with umlaut characters on Windows

### ISSUE THREAD

**Issue by broeser** [spring-cloud/spring-cloud-contract#1700]
Hello and thanks for this great project!

I'm using
- Spring Cloud 2020.0.3
- Spring Cloud Contract Maven Plugin 3.0.2
- Spring Boot 2.5.3
- Test Framework is JUnit 5
- Occurs only on Windows machines (confirmed by trying to Windows 10 machines and 1 Linux machine)

I use local contracts in YML format that contain unicode characters (German Umlauts ä, ö, ü).

All files in the project are encoded in UTF-8. In the pom.xml I have `<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

The exception I get is 
`java.lang.RuntimeException: com.fasterxml.jackson.dataformat.yaml.JacksonYAMLParseException: java.io.CharConversionException: Invalid UTF-8 start byte 0xfc (at char #661, byte #-1)`

At that character in the contract, I have an "ü". When I replace it with, e.g. an "u" (and of course adapt my code accordingly so the test doesn't fail), the error goes away.
When I run the same test in a linux docker container ( maven:3.6.3-jdk-11-slim), the exception does not occur.

Stacktrace:

`at org.springframework.cloud.contract.verifier.converter.YamlContractConverter.read(YamlContractConverter.java:98)
	at org.springframework.cloud.contract.verifier.util.ContractVerifierUtil.contract(ContractVerifierUtil.java:137)
	at de.redacted(ContractsTest.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)`

Any hints are appreciated. Thank you!

**Comment by marcingrzejszczak** [comment]
I don't have a Windows box on which I could check it out. Maybe the YAMLs are encoded in a wrong way? https://stackoverflow.com/questions/13830346/jackson-json-parser-invalid-utf-8-start-byte

> The character at column 33 is –, and the reason this would be the byte 0x96 is that the file is physically encoded as Windows-1252. You need to save the file in UTF-8, windows-1252 is not a valid encoding for json. How to do this depends on what text editor you are using.

**Comment by broeser** [comment]
I checked with `file` (in GitShell. I don't use Windows much myself) and get
 `UTF-8 Unicode text, with CRLF line terminators`

I attached a minimal example contract
[example-contract.yml.txt](https://github.com/spring-cloud/spring-cloud-contract/files/7088384/example-contract.yml.txt)
