### ISSUE TITLE
Upgrading to Spring Boot 2.6.0 breaks plugin 

### ISSUE THREAD

**Issue by zfz7** [spring-cloud/spring-cloud-contract#1737]
**Describe the bug**
I recently upgraded to Spring Boot 2.6.0, which caused some issues with one of our contracts. Specifically I was getting the following errors:
```
   java.lang.NoClassDefFoundError: org/mockito/Matchers
        at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.receive(SpringAmqpStubMessages.java:185)
        at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.receive(SpringAmqpStubMessages.java:209)
        at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.receive(SpringAmqpStubMessages.java:67)
        at org.springframework.cloud.contract.verifier.messaging.internal.ContractVerifierMessaging.receive(ContractVerifierMessaging.java:65)
        at mil.sf.section31.relay.strategy.contracts.web.WebTest.validate_publish(WebTest.java:117)

        Caused by:
        java.lang.ClassNotFoundException: org.mockito.Matchers
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
            at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
            at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
            ... 5 more

```

After digging around I realized Spring Boot upgraded their dependency on mockito to mockito:4.X.X.

**My Setup**
Spring Boot 2.6.0
spring-cloud-contract-gradle-plugin 3.0.4
Gradle 7.3

**Fix**
I included Mockito 3.X.X in our dependencies:
`testImplementation("org.mockito:mockito-core:3.12.4")`

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/6fd4280d12a5186eb2a009eb018b8c0943baf85d
