### ISSUE TITLE
Can't get Spring Cloud stubbed properly and think I'm following the documentation correctly

### ISSUE THREAD

**Issue by kabennett** [spring-cloud/spring-cloud-contract#174]
With the following test in place...
```
@RunWith(SpringRunner.class)
@SpringBootTest(classes = { AcmeServiceBootstrap.class })
//@EnableStubRunnerServer
@AutoConfigureStubRunner(ids = {
		"com.acme:security.services-dsl:1.1.0:stubs:6565" }, workOffline = true)
@DirtiesContext
@ActiveProfiles("ci")
public class IntegrationTests {

	@Autowired
	private SupportServiceClient supportServiceClient;

	@Test
	public void test() {
		supportServiceClient.isIPAllowedAccess("127.0.0.1");
	}

}
```
...I am receiving the stack trace below when trying to use Spring Cloud Contract. As you can see, the test is attempting to connect to Consul, which is not running. We don't want to require Consul to be running in our CI environment when running Spring Cloud Contract tests to do our integration testing. After reading the Spring Cloud Contract documentation, I thought the calls to Consul would be stubbed with spring.cloud.consul.enabled set to false. I am not clear what the problem might be here or what I may be missing in my code/configuration. I thought I was following what the documentation stated I needed to do to get my tests working while stubbing out Spring Cloud, but I am not certain.
```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:189)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:131)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.ecwid.consul.transport.TransportException: java.net.ConnectException: Connection refused: connect
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:91)
	at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:50)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:150)
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:429)
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:64)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.create(ConsulPropertySourceLocator.java:135)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:113)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator$$FastClassBySpringCGLIB$$b35ebf8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:74)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:157)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:101)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator$$EnhancerBySpringCGLIB$$5f04802b.locate(<generated>)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:89)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:111)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 25 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:75)
	... 51 more

```

**Comment by marcingrzejszczak** [comment]
You're thinking right, but only partially ;) So we're stubbing any calls made to another application done via load balanced clients. But as you can see in the stack trace, you're trying to use Consul as a property source provider. Try setting

```
spring:
  cloud:
    consul:
      config:
        enabled: false
```

for your tests.

**Comment by kabennett** [comment]
Ah, that makes sense. I was following the documentation at https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html and didn't see a mention of that config needing to be turned off, but that does make sense. Here's another issue I'm encountering now. We use the com.ecwid.consul.v1.ConsulClient class in our code, and as I run my Spring Cloud Contract test, I am now running into the issue of Consul not running as the com.ecwid.consul:consul-api library doesn't use load balanced clients to make HTTP calls to Consul. Do you have any suggestions regarding how best to make our Spring Cloud Contract tests work while using this library and not having to require Consul to be running? Marcin, I appreciate your reply!

**Comment by marcingrzejszczak** [comment]
No problem :) So you're using `consul-api` directly to find the client? That can be problematic since we're stubbing out Ribbon's `ServerList` and our `DiscoveryClient` AFAIR so if you're using any of these it will work OOB. So my suggestion is to use the abstraction to call a service and not to use Consul's API directly. Does it make any sense?

**Comment by kabennett** [comment]
Yeah, makes sense. You're saying to use the load balanced RestTemplate to make calls to Consul (http://localhost:8500), right?

**Comment by marcingrzejszczak** [comment]
You're getting the values of where your applications get registered from Consul. So if you use load balanced Rest Template and let's say you want to call an application called `foo` you'll just do `restTemplate.getForObject("http://foo/some/enpoint"...);` or sth like that. So I'm not talking about calls to Consul but calls to other applications. Now, Spring Cloud Contract can stub the idea of Consul here so you'll just have to map the artifactId (`foo-artifact`) of your stub with the name you're using in rest template (e.g. `foo`) like presented here - http://cloud.spring.io/spring-cloud-contract/1.0.x/spring-cloud-contract.html#_stub_runner_spring_cloud . Then we'll map any these kind of load balanced rest template calls to the started WireMock server for your stub.

**Comment by kabennett** [comment]
Yeah, it's making sense. However, if I don't use consul-api and replace calls made to Consul with RestTemplate calls, the calls will be converted to something like this:

```
ResponseEntity<String> responseEntity = restTemplate.exchange(
				"http://localhost:8500/v1/kv/config/someKey", HttpMethod.GET, HttpEntity.EMPTY,
				String.class);
```
With the case of Consul, there is no service name like 'foo' that's part of the path. I'm just hitting http://localhost:8500 and the /v1/kv/config/someKey resource. So, the question is, can I map an artifactId like you referenced in your last post to a host:port instead of a service name?

**Comment by marcingrzejszczak** [comment]
Wait, wait... So you want to stub out Consul to do what? Make a service call or retrieve configuration? If you want to do the first - use Stub Runner and SPring Cloud Contract. If the latter, use Test Property Sources. Just tell your tests what kind of properties it should pick (http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/context/TestPropertySource.html). If you're retrieving these values not via `@Value` but you do it directly via the Consul's API then my suggestion is to register this object that retrieves the configuration from consul as a bean that you will override in your test. Example

```
class PropertyRetriever {
String getValue(String key) { return callConsulViaTheApi();}
}

@Configuration
class YourPropertyRetrieverConfig {
@Bean PropertyRetriever propertyRetriever() { return new PropertyRetriever(); }
}
```

and in your test you can do

```
class TestPropertyRetriever extends PropertyRetriever {
private final Environment environment;
//constructor injector
String getValue(String key) { return this.environment.getProperty(key);}
}

// either via primary
@Configuration
class YourTestConfig {
@Bean @Primary PropertyRetriever testPropertyRetriever(Environment env) { return new PropertyRetriever(env); }
}

// or you can exclude the prodution configuration for your tests
```

**Comment by kabennett** [comment]
OK, I will try your recommendations. Thank you for your replies, Marcin.

**Comment by marcingrzejszczak** [comment]
No problem :)

**Comment by kabennett** [comment]
Hi, Marcin. I am receiving the following stack trace now:

```
Caused by: java.lang.IllegalStateException: No instances available for securityService
	at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.execute(RibbonLoadBalancerClient.java:90)
	at org.springframework.cloud.client.loadbalancer.RetryLoadBalancerInterceptor$1.doWithRetry(RetryLoadBalancerInterceptor.java:60)
	at org.springframework.cloud.client.loadbalancer.RetryLoadBalancerInterceptor$1.doWithRetry(RetryLoadBalancerInterceptor.java:48)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:157)
	at org.springframework.cloud.client.loadbalancer.RetryLoadBalancerInterceptor.intercept(RetryLoadBalancerInterceptor.java:48)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:85)
	at org.springframework.cloud.sleuth.instrument.web.client.TraceRestTemplateInterceptor.response(TraceRestTemplateInterceptor.java:59)
	at org.springframework.cloud.sleuth.instrument.web.client.TraceRestTemplateInterceptor.intercept(TraceRestTemplateInterceptor.java:53)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:85)
	at org.springframework.cloud.netflix.metrics.MetricsClientHttpRequestInterceptor.intercept(MetricsClientHttpRequestInterceptor.java:68)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:85)
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:69)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:619)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:407)
	at org.springframework.web.client.RestTemplate$$FastClassBySpringCGLIB$$aa4e9ed0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at org.springframework.cloud.netflix.metrics.RestTemplateUrlTemplateCapturingAspect.captureUrlTemplate(RestTemplateUrlTemplateCapturingAspect.java:33)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.springframework.web.client.RestTemplate$$EnhancerBySpringCGLIB$$e767295f.postForEntity(<generated>)
	... 33 more

```

I have the following specified in my test bootstrap.yml:
```
stubrunner:
  idsToServiceIds:
    oauth.service: securityService
```
I have a jar in my local .m2 repo named securitySerivce-stubs.jar.

My code to access the security service through the load balanced RestTemplate:
```
restTemplate.postForEntity(
                                "https://securityService/oauth/token?grant_type=client_credentials", httpEntity,
                                AccessToken.class);
```
And my test annotations include:
```
@RunWith(SpringRunner.class)
@SpringBootTest(classes = { ProxyServiceApplication.class })
@EnableStubRunnerServer
@AutoConfigureStubRunner(ids = {
		"com.acme:oauth.service-dsl:1.0.0:stubs:6565" }, workOffline = true)
@DirtiesContext
@ActiveProfiles("ci")
```
Unless I'm reading the documentation incorrectly, this should be running the Spring Cloud stubs I would think. But from the stack trace, it looks like I'm actually hitting the Netflix Ribbon load balancer.

**Comment by marcingrzejszczak** [comment]
This looks fishy...

stubrunner:
  idsToServiceIds:
    oauth.service: securityService


I wonder if that . is not making things bad - I'll have to debug this. what
if you tried to change the dot into a _ and retry in the meantime?

2016-12-22 22:31 GMT+01:00 Keith Bennett <notifications@github.com>:

**Comment by kabennett** [comment]
Marcin, I figured out what my issues were, and they were issues with my code. I am now running into an issue where I'm receiving a 404 when invoking my stub while testing the client side. I was able to generate the stub just fine and get the producer side tests to pass, but on the client side is where I am receiving the 404. 

Here's my contract:
```
package contracts
import org.springframework.cloud.contract.spec.Contract

Contract.make {
	request {
		method 'POST'
		url('/oauth/token') {
			queryParameters {
				parameter 'grant_type': 'client_credentials'
				parameter 'version': 'alpha'
			}
		}
		headers {
			header 'Authorization' : 'Basic xxxxxxxxxxxxxxxxxxxxxxx=='
		}
	}
	response {
		status 200
		body([
			access_token: $(producer(regex('[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'))),
  			token_type: 'bearer',
  			refresh_token: $(producer(regex('[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'))),
  			expires_in: $(anyNumber()),
  			scope: 'read write delete'
		])
		headers {
			contentType('application/json')
		}
	}
}
```
And here's my client side test:
```
HttpHeaders httpHeaders = new HttpHeaders();
                httpHeaders.add(HttpHeaders.AUTHORIZATION, "Basic xxxxxxxxxxxxxxxxxxxxxxx==");
                httpHeaders.setAccept(Arrays.asList(MediaType.APPLICATION_JSON));
                httpHeaders.setContentType(MediaType.APPLICATION_JSON);
                HttpEntity<HttpHeaders> httpEntity = new HttpEntity<HttpHeaders>(null, httpHeaders);
                ResponseEntity<AccessToken> responseEntity =
                        restTemplate.postForEntity("http://serviceSecurity/oauth/token?grant_type=client_credentials&version=alpha", httpEntity,
                                AccessToken.class);
```
And here's the json file in the mappings directory of my generated stubs jar:
```
{
  "uuid" : "d52b5228-b569-431d-8dt6-ed9b37091278",
  "request" : {
    "url" : "/oauth/token",
    "method" : "POST",
    "headers" : {
      "Authorization" : {
        "equalTo" : "Basic xxxxxxxxxxxxxxxxx=="
      }
    },
    "queryParameters" : {
      "grant_type" : {
        "equalTo" : "client_credentials"
      },
      "version" : {
        "equalTo" : "alpha"
      }
    }
  },
  "response" : {
    "status" : 200,
    "body" : "{\"access_token\":\"63d3dc9b-689a-ad5e-b9c3-eefdc0252fed\",\"token_type\":\"bearer\",\"refresh_token\":\"983fb2d6-c4d5-f70f-88a9-8fc10ba52ca6\",\"expires_in\":\"-1853645568\",\"scope\":\"read\"}",
    "headers" : {
      "Content-Type" : "application/json"
    }
  }
}
```
I have verified that the masked base64 encoded username:password is the same in the groovy contract and the client code. I did have to change the spring.cloud.consul.discovery.scheme to http and ribbon.IsSecure to false to get my tests to work as I was receiving the following error when trying to use https in my restTemplate:
```
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
```
So, now I'm at least able to invoke my stub via http, but I can't figure out why I might be getting the 404. Man, I feel like I'm close to getting my test working, but it's been a learning process for me. I appreciate you taking time to respond to my questions. Love the framework!

**Comment by marcingrzejszczak** [comment]
We're so close :D Do you have in your logs any information from WireMock like `Request not matched, the closest match is...?` . 

BTW can you try to run a WireMock instance and curl a request manually to see if you get the response? That way we'll know whether you're curling sth wrong or whether it's sth with the Java code.

**Comment by kabennett** [comment]
OK, well, I really don't understand what happened, but I did another `mvn clean install` on my producer code to regenerate the stub and the stub finally ran successfully on the client side. Great! However, I realized I had Consul running locally, and when I stopped Consul, my test wouldn't start. So, I figured out that my `src/main/resources/bootstrap.yml` configuration was still being picked up and just to verify that this was so, I set `spring:cloud:consul:config:enabled: false` in my `src/main/resources/bootstrap.yml` file and stopped Consul again. This time, my test passed again. So, for some reason, my test isn't picking up the configurations I have specified in my test properties file.

I have a `src/test/resources/bootstrap-ci.properties` file with the following annotation in my test class:

`@TestPropertySource(locations = "classpath:bootstrap-ci.properties")`

My understanding is that a test bootstrap.yml file can't be picked up by a Spring Boot Test that overrides the properties defined under `src/main/resources`, so this is how I have my test configured.

How can I override the configurations I have specified in my `src/main/resource/bootstrap.yml` file in my test so that I can run my tests over http and turn off Consul?

**Comment by marcingrzejszczak** [comment]
you can do it directly in the `@TestPropertySource` (http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/context/TestPropertySource.html) . If you want to override it in a `bootstrap` file then it's enough to add the `@ActiveProfiles("ci")` and then the `bootstrap-ci.properties` will be picked automatically.

**Comment by kabennett** [comment]
Hmm, I've tried placing my bootstrap-ci.properties as you describe in both src/main/resources and src/test/resources to no avail. I've also tried the @TestPropertySource approach, specifying individual key/value pairs. I can not get the spring.cloud.consul properties overridden for my tests.

**Comment by marcingrzejszczak** [comment]
ping @dsyer @spencergibb @ryanjbaxter ^^ any idea why?

**Comment by dsyer** [comment]
If there is more than one file with the same name in the classpath that will screw you up. Apart from that I'd expect `@ActiveProfiles` to work (and `@TestPropertySource` probably not).

**Comment by kabennett** [comment]
Configs that are normally obtained from Consul are in `src/test/resources/bootstrap-ci.yml` for my Spring Cloud Contract tests. In a nutshell, I don't want to require Consul to be running for any of our integration tests, so I need `spring.cloud.consul.config.enabled: false` to be set, and if I make this change in `src/main/resources/bootstrap.yml`, I can run my tests just fine. Obviously this isn't the right solution, so I need to override this config in my `bootstrap-ci.yml` file, but this same configuration is never picked up from there. I know other configs are being picked up from `boostrap-ci.yml`, because I can comment them out, and I receive the expected `java.lang.IllegalArgumentException: Could not resolve placeholder` exception.

My bootstrap.yml:
```
spring:
  application:
    name: edgeService
  cloud:
    consul:
      config:
        enabled: false
        prefix: config
        profileSeparator: '@@'
        watch:
          enabled: false
      discovery:
        tags: version=@project.version@
      host: localhost
      port: 8500
  main:
    banner-mode: 'off'
```
My bootstrap-ci.yml:
```
spring:
  application:
    name: edgeService
  cloud:
    consul:
      discovery:
        scheme: http
      enabled: false
      config:
        enabled: false
... (other app-specific configs removed)
stubrunner:
  ids: com.acme:security.service:1.0.0:stubs
  idsToServiceIds:
    security.service: securityService
```

**Comment by marcingrzejszczak** [comment]
Merry Christmas :) It would be much easier if you posted this as a sample that we could check. Do you think that it could be possible?

But apart from the bootstrapping thing is Spring Cloud Contract working properly?

**Comment by kabennett** [comment]
Merry Christmas to you as well! Yes, I can put a sample together, but it
will be a few days with the holidays. Yes, besides the bootstrapping issue,
Spring Cloud Contract is working great. Thanks!

**Comment by kabennett** [comment]
[demo.zip](https://github.com/spring-cloud/spring-cloud-contract/files/675697/demo.zip)

This demo assumes you have Consul running locally and demonstrates the issue I explained previously, that I haven't been able to override the `spring.cloud.consul.config.enabled` value to `false` for the purposes of running our Spring Cloud Contract tests. The demo has this value initially set to `false`, so you should be able to run a `mvn clean install` on both projects to exercise Spring Cloud Contract Verifier and Spring Cloud Contract Stub Runner successfully. Of course, these values are normally set to `true`. So, the thing I've tried to get working is to have `spring.cloud.consul.config.enabled` set to `true` and override this value in `bootstrap-ci.yml` so that I can run our CI tests without Consul running. The only solution I've been able to get working that could be acceptable going forward is to set this value to `false` in `bootstrap.yml` and in our service startup scripts provide a Java argument to override the value to `true`. Let me know if you need any more details. Thanks!

**Comment by marcingrzejszczak** [comment]
Hi!

I'm analyzing your sample and I have a couple of thoughts that maybe don't answer your question directly but might make the problem disappear ;)

# PRODUCER

## Stream binder

Consul uses Stream as a binder. You're missing a test binder

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
```

That way your app won't try to connect to a real consul when you add 

```
spring:
  cloud:
    consul:
      enabled: false
```

Also I had to add a property in my tests so that the `GreetingProducerApplicationTests` successfully starts the context.

```
producerConfig: foo
```

## Speeding up contract tests

The controller should have constructor based dependency injection

```
@RestController
@RequestMapping("producer")
public class GreetingProducerController {

	private final GreetingProducerService service;

	public GreetingProducerController(GreetingProducerService service) {
		this.service = service;
	}

	@RequestMapping(value = "greeting/{name}", method = RequestMethod.GET, produces = { MediaType.APPLICATION_XML_VALUE,
			MediaType.APPLICATION_JSON_VALUE })

	public ResponseEntity<GreetingWrapper> getGreeting(@PathVariable String name) {
		GreetingWrapper wrapper = new GreetingWrapper();
		wrapper.setGreeting(service.generateGreeting(name));
		return new ResponseEntity<GreetingWrapper>(wrapper, HttpStatus.OK);
	}

}
```

and then you don't have to start the whole setup in your base class . Check this out:

```
@Ignore
public class ContractVerifierBase {

	@Before
	public void setUp() throws Exception {
		RestAssuredMockMvc.standaloneSetup(new GreetingProducerController(new GreetingProducerService() {
			@Override public String generateGreeting(String name) {
				return "Hello, dude!";
			}
		}));
	}
}
```

then your generated test doesn't even need a Spring Context!

```

public class ContractVerifierTest extends ContractVerifierBase {

	@Test
	public void validate_shouldReturnHelloDude() throws Exception {
		// given:
			MockMvcRequestSpecification request = given()
					.header("Accept", "application/json");

		// when:
			ResponseOptions response = given().spec(request)
					.get("/producer/greeting/dude");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
			assertThat(response.header("Content-Type")).matches("application/json.*");
		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("greeting").isEqualTo("Hello, dude!");
	}

}
```
# Consumer side

If you put in your `bootstrap-ci.yml`

```
stubrunner:
  ids: com.example:demo-producerx:+:stubs
  idsToServiceIds:
    demo-producer: greetingProducer
clientConfig: aValue
spring:
  cloud:
    consul:
      enabled: false
      config:
        enabled: false
```

*BUT* it works only if the property for config is set to false. Ping @dsyer @snicoll @philwebb @spencergibb  - how is it possible to disable a PropertySourceLocator that is registered in `org.springframework.cloud.bootstrap.BootstrapConfiguration` ? Cause the funny thing is that in the autoconfiguration report we can see it twice:

```
ConsulConfigBootstrapConfiguration.ConsulPropertySourceConfiguration:
      Did not match:
         - @ConditionalOnProperty (spring.cloud.consul.config.enabled) found different value in property 'spring.cloud.consul.config.enabled' (OnPropertyCondition)
         - Ancestor org.springframework.cloud.consul.config.ConsulConfigBootstrapConfiguration did not match (ConditionEvaluationReport.AncestorsMatchedCondition)
```

And then the second autoconfig

```
ConsulConfigBootstrapConfiguration.ConsulPropertySourceConfiguration matched:
      - @ConditionalOnProperty (spring.cloud.consul.config.enabled) matched (OnPropertyCondition)
```

# Minor hints...

...that you can completely disregard ;)

- `@SpringBootApplication` gives you `@ComponentScan` - no need to use it
- Why do you have 1 interface and 1 impl? I'd use only the class 
- I'd put all classes in a single package and make all of them package scoped

Recapping - I guess we can close it here and continue this discussion either in Consul or Spring Boot (or maybe Spring Cloud Commons?)

**Comment by marcingrzejszczak** [comment]
Closing this one cause this works and I filed a new bug here - https://github.com/spring-cloud/spring-cloud-commons/issues/156
