### ISSUE TITLE
MetadataUtil throws when merging message properties into AmqpMetadata on Java 17

### ISSUE THREAD

**Issue by adrianhj** [spring-cloud/spring-cloud-contract#1765]
**Describe the bug**

Triggering a stub with an AMQP metadata blocks throw when MetadatUtil attempts to merge the message properties into the AmqpMetadata instance.

It looks like fixes have been applied [previously](https://github.com/spring-cloud/spring-cloud-contract/blob/v3.1.1/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/MetadataUtil.java#L96) however I'm not sure if Jackson Databind has changed behaviour since (my project is running 2.13.2).

The immediate cause I'm seeing is an `InvalidDefinitionException` so it misses the current JDK16+ fallback logic to copying the properties over that checks the immediate exception only:

```
java.lang.IllegalStateException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `java.lang.reflect.Method`: Failed to call `setAccess()` on Field 'parameters' (of class `java.lang.reflect.Executable`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private transient volatile java.lang.reflect.Parameter[] java.lang.reflect.Executable.parameters accessible: module java.base does not "opens java.lang.reflect" to unnamed module @7cd62f43
    at [Source: (byte[])"{"outputMessage":{"messageProperties":{"receivedRoutingKey":"some.key"}}}"; line: 1, column: 1]
	at org.springframework.cloud.contract.verifier.util.MetadataUtil.merge(MetadataUtil.java:117)
	at org.springframework.cloud.contract.verifier.util.MetadataUtil.fromMetadata(MetadataUtil.java:75)
	at org.springframework.cloud.contract.verifier.messaging.amqp.AmqpMetadata.fromMetadata(AmqpMetadata.java:67)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.mergeMessagePropertiesFromMetadata(SpringAmqpStubMessages.java:123)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:139)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:102)
	at org.springframework.cloud.contract.stubrunner.spring.LazyMessageVerifier.send(StubRunnerConfiguration.java:198)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.sendMessage(StubRunnerExecutor.java:252)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.triggerForDsls(StubRunnerExecutor.java:205)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.trigger(StubRunnerExecutor.java:191)
	at org.springframework.cloud.contract.stubrunner.StubRunner.trigger(StubRunner.java:152)
	at org.springframework.cloud.contract.stubrunner.BatchStubRunner.trigger(BatchStubRunner.java:133)
	at ...8x...snip...8x
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `java.lang.reflect.Method`: Failed to call `setAccess()` on Field 'parameters' (of class `java.lang.reflect.Executable`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private transient volatile java.lang.reflect.Parameter[] java.lang.reflect.Executable.parameters accessible: module java.base does not "opens java.lang.reflect" to unnamed module @7cd62f43
 at [Source: (byte[])"{"outputMessage":{"messageProperties":{"receivedRoutingKey":"agreement.created"}}}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadTypeDefinition(DeserializationContext.java:1882)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._handleBadAccess(BeanDeserializerBuilder.java:620)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:537)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder.build(BeanDeserializerBuilder.java:384)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:415)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:632)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:632)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:632)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:642)
	at com.fasterxml.jackson.databind.ObjectReader._findRootDeserializer(ObjectReader.java:2332)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1529)
	at org.springframework.cloud.contract.verifier.util.MetadataUtil.merge(MetadataUtil.java:93)
	... 81 more
Caused by: java.lang.IllegalArgumentException: Failed to call `setAccess()` on Field 'parameters' (of class `java.lang.reflect.Executable`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private transient volatile java.lang.reflect.Parameter[] java.lang.reflect.Executable.parameters accessible: module java.base does not "opens java.lang.reflect" to unnamed module @7cd62f43
	at com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:1009)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.fixAccess(FieldProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:535)
	... 109 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient volatile java.lang.reflect.Parameter[] java.lang.reflect.Executable.parameters accessible: module java.base does not "opens java.lang.reflect" to unnamed module @7cd62f43
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:996)
	... 111 more
```

**Spring Cloud Version**
```
org.springframework.cloud:spring-cloud-starter-contract-verifier:jar:3.1.1
```

**Java Version**
```
$ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```

**Sample**

It looks like [the following commit](https://github.com/spring-cloud/spring-cloud-contract/commit/c3ce9f63268c7e5c93973b2b2bc40fb6ffd10336) is disabling two tests that are exhibiting the same issue I'm seeing under Java 17 so can be replicated by re-enabling these.

Please note however that stack for these seem to be following a slightly different path where the original `java.lang.reflect.InaccessibleObjectException` has been lost as the root cause somewhere inside Jackson Databind so not as straight forward as grabbing root cause and checking its type:

```
java.lang.IllegalStateException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed to call `setAccess()` on Field 'parameters' due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private transient volatile java.lang.reflect.Parameter[] java.lang.reflect.Executable.parameters accessible: module java.base does not "opens java.lang.reflect" to unnamed module @4e9ba398
 at [Source: (byte[])"{"input":{"messageProperties":{"correlationId":"correlationIdValue","consumerQueue":"queue","contentType":"application/json","receivedRoutingKey":"resource.created"}}}"; line: 1, column: 1]
	at org.springframework.cloud.contract.verifier.util.MetadataUtil.merge(MetadataUtil.java:118)
	at org.springframework.cloud.contract.verifier.util.MetadataUtil.fromMetadata(MetadataUtil.java:76)
	at org.springframework.cloud.contract.verifier.messaging.amqp.AmqpMetadata.fromMetadata(AmqpMetadata.java:67)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.mergeMessagePropertiesFromMetadata(SpringAmqpStubMessages.java:123)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:139)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:102)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessagesSpec.should send amqp message with metadata id(SpringAmqpStubMessagesSpec.groovy:92)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed to call `setAccess()` on Field 'parameters' due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private transient volatile java.lang.reflect.Parameter[] java.lang.reflect.Executable.parameters accessible: module java.base does not "opens java.lang.reflect" to unnamed module @4e9ba398
 at [Source: (byte[])"{"input":{"messageProperties":{"correlationId":"correlationIdValue","consumerQueue":"queue","contentType":"application/json","receivedRoutingKey":"resource.created"}}}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:632)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:632)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:632)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:642)
	at com.fasterxml.jackson.databind.ObjectReader._findRootDeserializer(ObjectReader.java:2332)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1529)
	at org.springframework.cloud.contract.verifier.util.MetadataUtil.merge(MetadataUtil.java:94)
	... 6 more
```

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/commit/ce03ee008b671a74f313fc9d4a3ffb6a483810f3

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/pull/1766
