### ISSUE TITLE
Exception occurred while trying to match JSON Path

### ISSUE THREAD

**Issue by bandfernmohn** [spring-cloud/spring-cloud-contract#178]
In tests generated out of contracts with AMQP messages we observe the following error: 
```
2016-12-23 14:32:45,272 ERROR [main] - [com.toomuchcoding.jsonassert.JsonAsserter] [tenant=1234] - Exception occurred while trying to match JSON Path [$[?(@.ratedItemId == '992e46d8-ab05-4a26-a740-6ef7b0daeab3')]]
com.jayway.jsonpath.InvalidPathException: Filter: [?] can not be applied to primitives. Current context is: eyJyYXRlZEl0ZW1JZCI6Ijk5MmU0NmQ4LWFiMDUtNGEyNi1hNzQwLTZlZjdiMGRhZWFiMyIsImV2ZW50VHlwZSI6IkNSRUFURUQifQ==
	at com.jayway.jsonpath.internal.path.PredicatePathToken.evaluate(PredicatePathToken.java:66)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:151)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:158)
	at com.toomuchcoding.jsonassert.JsonAsserter.parseJsonPathAsArray(JsonAsserter.java:205)
	at com.toomuchcoding.jsonassert.JsonAsserter.check(JsonAsserter.java:196)
	at com.toomuchcoding.jsonassert.JsonAsserter.checkBufferedJsonPathString(JsonAsserter.java:213)
	at com.toomuchcoding.jsonassert.JsonAsserter.isEqualTo(JsonAsserter.java:99)
...
```
It looks like the payload in the received message is a byte array but is treated like an object:
```
		// then:
			ContractVerifierMessage response = contractVerifierMessaging.receive("bill-service.rated-item-event.retry-exchange");

DocumentContext parsedJson = JsonPath.parse(contractVerifierObjectMapper.writeValueAsString(response.getPayload()));
```

In `ContractVerifierObjectMapper.writeValueAsString()` `this.objectMapper.writeValueAsString(payload)` is called which is intended to serialize any Java value as a String, not to convert byte arrays to JSON or even objects.

The contract used is
```
Contract.make {

    label 'ratedItem-no-metricid'
    input {
        messageFrom("rated-item-service.rated-item-event.exchange")
        messageHeaders {
            header("X-tenant", "1234")
            header("contentType", "application/json")
        }
        messageBody(
                ratedItemId: "992e46d8-ab05-4a26-a740-6ef7b0daeab3",
                eventType: "CREATED"
        )
    }
    outputMessage {
        sentTo('bill-service.rated-item-event.retry-exchange')
        headers {
            header("X-tenant", "1234")
            header("contentType", "application/json")
        }
        body(
                ratedItemId: "992e46d8-ab05-4a26-a740-6ef7b0daeab3",
                eventType: "CREATED"
        )
    }
}
```

**Comment by marcingrzejszczak** [comment]
A workaround right now is to register your own `ContractVerifierObjectMapper` and write things properly. I'm trying to fix it in Contracts as we speak but until then and till the release you can use the workaround

**Comment by bandfernmohn** [comment]
Thanks! Just tested it and it works perfectly!

**Comment by marcingrzejszczak** [comment]
Awesome :) Thanks!
