### ISSUE TITLE
java.lang.NullPointerException - org.springframework.cloud.contract.verifier.plugin.ContractsCopyTask.throwExceptionWhenFailOnNoContracts(ContractsCopyTask.java:252)

### ISSUE THREAD

**Issue by cer** [spring-cloud/spring-cloud-contract#1830]
```
Execution failed for task ':customer-service-web:copyContracts'.
> java.lang.NullPointerException (no error message)

Caused by: java.lang.NullPointerException
        at org.springframework.cloud.contract.verifier.plugin.ContractsCopyTask.throwExceptionWhenFailOnNoContracts(ContractsCopyTask.java:252)
        at org.springframework.cloud.contract.verifier.plugin.ContractsCopyTask.sync(ContractsCopyTask.java:164)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)

```

https://github.com/spring-cloud/spring-cloud-contract/blob/6de10e34df4b5f378b2a9c809a8d455cb562a2f3/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java#L252

**Comment by cer** [comment]
My contracts were in `resources/` instead of `resources/contracts`
