### ISSUE TITLE
INTERNAL: Received unexpected EOS on empty DATA frame from server

### ISSUE THREAD

**Issue by talipkorkmaz** [spring-cloud/spring-cloud-contract#1858]
When I'm trying to call a stubbed GRPC method, Im taking a response like below.

```
2022-12-22 09:55:52.660 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : [id: 0x3fed1b01, L:/127.0.0.1:51694 - R:localhost/127.0.0.1:5433] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2022-12-22 09:55:52.660 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : [id: 0x3fed1b01, L:/127.0.0.1:51694 - R:localhost/127.0.0.1:5433] INBOUND SETTINGS: ack=true
2022-12-22 09:55:52.667 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : [id: 0x3fed1b01, L:/127.0.0.1:51694 - R:localhost/127.0.0.1:5433] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: localhost:5433, :path: /user.UserContactDetailsService/getContactDetails, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.48.1, grpc-accept-encoding: gzip, grpc-timeout: 2844557u] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2022-12-22 09:55:52.671 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : [id: 0x3fed1b01, L:/127.0.0.1:51694 - R:localhost/127.0.0.1:5433] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=7 bytes=00000000020801
2022-12-22 09:55:52.734  INFO 95520 --- [p1680138169-325] WireMock                                 : Request received:
127.0.0.1 - POST /user.UserContactDetailsService/getContactDetails

content-type: [application/grpc]
te: [trailers]
user-agent: [grpc-java-netty/1.48.1]
grpc-accept-encoding: [gzip]
grpc-timeout: [2844557u]
host: [localhost:5433]



Matched response definition:
{
  "status" : 200,
  "base64Body" : "AAAAADISA2xzYRoDbGZuIgNsbG4qA2xubjIDbHNuOgUxMjM0NUICbGNIKlIKMDEyMzQ1Njc4OQ==",
  "headers" : {
    "Content-Type" : "application/grpc",
    "grpc-encoding" : "identity",
    "grpc-accept-encoding" : "gzip"
  },
  "transformers" : [ "response-template", "spring-cloud-contract" ]
}

Response:
HTTP/1.1 200
Content-Type: [application/grpc]
grpc-encoding: [identity]
grpc-accept-encoding: [gzip]
Matched-Stub-Id: [68601a27-8b6c-4486-92e4-c43bb9c32594]


2022-12-22 09:55:52.737 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : [id: 0x3fed1b01, L:/127.0.0.1:51694 - R:localhost/127.0.0.1:5433] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip, matched-stub-id: 68601a27-8b6c-4486-92e4-c43bb9c32594, vary: Accept-Encoding, User-Agent] padding=0 endStream=false
2022-12-22 09:55:52.740 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : [id: 0x3fed1b01, L:/127.0.0.1:51694 - R:localhost/127.0.0.1:5433] INBOUND DATA: streamId=3 padding=0 endStream=false length=55 bytes=000000003212036c73611a036c666e22036c6c6e2a036c6e6e32036c736e3a05313233343542026c63482a520a30313233343536373839
2022-12-22 09:55:52.740 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : [id: 0x3fed1b01, L:/127.0.0.1:51694 - R:localhost/127.0.0.1:5433] OUTBOUND PING: ack=false bytes=1234
2022-12-22 09:55:52.742 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : [id: 0x3fed1b01, L:/127.0.0.1:51694 - R:localhost/127.0.0.1:5433] INBOUND DATA: streamId=3 padding=0 endStream=true length=0 bytes=
2022-12-22 09:55:52.743 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : [id: 0x3fed1b01, L:/127.0.0.1:51694 - R:localhost/127.0.0.1:5433] INBOUND PING: ack=true bytes=1234
2022-12-22 09:55:52.743 DEBUG 95520 --- [-worker-ELG-1-4] i.g.n.s.i.grpc.netty.NettyClientHandler  : Window: 1048576
2022-12-22 09:55:52.773  INFO 95520 --- [           main] o.s.t.c.transaction.TransactionContext   : Rolled back transaction for test: [DefaultTestContext@559af296 testClass = UserContactDetailsContractIT, testInstance = com.ebay.kleinanzeigen.rec2bservice.adapters.out.grpc.usercontactdetails.UserContactDetailsContractIT@153054d4, testMethod = shouldReturnEmptyUser@UserContactDetailsContractIT, testException = io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server, mergedContextConfiguration = [WebMergedContextConfiguration@5edc3e29 testClass = UserContactDetailsContractIT, locations = '{}', classes = '{class com.ebay.kleinanzeigen.rec2bservice.configuration.integrationtest.IntegrationTestConfig}', contextInitializerClasses = '[class com.ebay.kleinanzeigen.rec2bservice.infrastructure.persistence.MySqlInitializer]', activeProfiles = '{test}', propertySourceLocations = '{classpath:application-test.yml}', propertySourceProperties = '{grpc.client.beerService.address=static://localhost:5433, grpc.client.beerService.negotiationType=PLAIN, org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true, server.port=0}', contextCustomizers = set[[ImportsContextCustomizer@18709cb2 key = [org.springframework.boot.test.autoconfigure.web.servlet.MockMvcAutoConfiguration, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcWebClientAutoConfiguration, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcWebDriverAutoConfiguration, org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration, org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcSecurityConfiguration, org.springframework.boot.test.autoconfigure.web.reactive.WebTestClientAutoConfiguration]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@174721c4, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@47b33e07, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@1859ffda, org.springframework.boot.test.autoconfigure.actuate.metrics.MetricsExportContextCustomizerFactory$DisableMetricExportContextCustomizer@718fd7c1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@4b3fa0b3, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@c8f97a7, org.springframework.boot.test.context.SpringBootTestArgs@1, org.springframework.boot.test.context.SpringBootTestWebEnvironment@4af45442], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> false, 'org.springframework.test.context.event.ApplicationEventsTestExecutionListener.recordApplicationEvents' -> false]]

io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server

	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
```

My understanding is Wiremock is returning the successful response with 200 status code and response body contains the arranged byte array. Because the netty logs show the byte array as INBOUND DATA, the only thing I caught is endStream is false. 
Somehow it's not acceptable by GRPC client.
Could anyone please help with this?

**Comment by aanbrn** [comment]
Trying to solve the same issue on my side, I've had to go deep into Spring Cloud Contract, WireMock and gRPC. Finally, I've prepared [my own implementation](https://github.com/aanbrn/grpc-spring-cloud-contract) of gRPC Verifier and Stub Configurer.

**Comment by marcingrzejszczak** [comment]
@aanbrn if you think that what we currently have is wrong please feel free to file a PR that improves the SCC implementation

**Comment by aanbrn** [comment]
@marcingrzejszczak ok, will do when have time.
