### ISSUE TITLE
WireMockRestTemplateConfiguration setHttpClient compilation error

### ISSUE THREAD

**Issue by themoffster** [spring-cloud/spring-cloud-contract#1859]
**Describe the bug**
I have updated org.springframework.cloud:spring-cloud-starter-contract-stub-runner from 3.1.5 to 4.0.0 and in the WireMockRestTemplateConfiguration class, there is a compilation error since the upgrade.

The createSslHttpClient() method now returns a org.apache.hc.client5.http.classic.HttpClient, but the HttpComponentsClientHttpRequestFactory requires a org.apache.http.client.HttpClient.

![Screenshot from 2023-01-05 09-18-15](https://user-images.githubusercontent.com/14044806/210744750-abe4ff0a-5d33-492c-9bdd-2d8e9314e32b.png)

This results in the following exception when running tests: 
```
Caused by: java.lang.NoSuchMethodError: 'void org.springframework.http.client.HttpComponentsClientHttpRequestFactory.setHttpClient(org.apache.hc.client5.http.classic.HttpClient)'
	at org.springframework.cloud.contract.wiremock.WireMockRestTemplateConfiguration$1.customize(WireMockRestTemplateConfiguration.java:54)
	at org.springframework.boot.web.client.RestTemplateBuilder.configure(RestTemplateBuilder.java:634)
	at org.springframework.boot.web.client.RestTemplateBuilder.build(RestTemplateBuilder.java:589)
	at uk.gov.ros.client.AbstractClient.<init>(AbstractClient.java:33)
	at uk.gov.ros.customer.amendments.client.lrarchive.LRArchiveClient.<init>(LRArchiveClient.java:25)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
```

**Comment by themoffster** [comment]
This can be closed, I've realised when creating a sample project that is is related to the spring boot 3 upgrade.
My example screenshot above is from a service running latest spring boot 2 - with spring boot 3 it's a non-issue.
This will be resolved when I upgrade our service to latest spring boot.
