### ISSUE TITLE
AutoConfigureWiremock with a pre-defined custom port always defaults to port 8080

### ISSUE THREAD

**Issue by igdianov** [spring-cloud/spring-cloud-contract#2035]
**Describe the bug**

AutoConfigureWiremock with a pre-defined custom port always defaults to port 8080 because of this change: https://github.com/spring-cloud/spring-cloud-contract/commit/a15db490f169412e50fc3140d95d8a70108465d5

Spring Cloud Version: 4.1.0-M2

**Sample**

```
@SpringBootTest
@AutoConfigureWireMock(port = 8888)
public class WiremockImportApplicationTests {

	@Autowired
	private WireMockServer wireMockServer;

	@Test
	public void contextLoads() throws Exception {
		assertThat(this.wireMockServer.port()).isEqualTo(8888);
	}

}
```

```
org.opentest4j.AssertionFailedError: 
expected: 8888
 but was: 8080
Expected :8888
Actual   :8080
<Click to see difference>


	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at com.alfresco.form.runtime.controller.WiremockImportApplicationTests.contextLoads(WiremockImportApplicationTests.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by igdianov** [comment]
@spencergibb Any chance this gets triaged and resolved in the upcoming Spring Boot 3.2 release?

**Comment by spencergibb** [comment]
It's not part of spring boot 3.2, but spring cloud 2023.0, I think it can.

**Comment by igdianov** [comment]
@spencergibb Any chance this gets resolved soon for 2023.0 release?

**Comment by igdianov** [comment]
Any updates on this, please? The PR is ready. Just needs 👍

**Comment by andrea-ligios** [comment]
Hi @spencergibb , this is a low hanging fruit 👍🏻  

We know your backlog is big but we'd really appreciate if you could dedicate this a couple of minutes, thank you in advance 🙏🏻

**Comment by spencergibb** [comment]
@OlgaMaciaszek can you take a look?

**Comment by OlgaMaciaszek** [comment]
Sure, will look tomorrow.

**Comment by OlgaMaciaszek** [comment]
Redirecting to @marcingrzejszczak since he should be back tomorrow.
