### ISSUE TITLE
JSONPath compilation fails when there is an array, attribute that is an array and then attribute on an execute()

### ISSUE THREAD

**Issue by pfrank13** [spring-cloud/spring-cloud-contract#251]
This is happening on the 1.0.4.RELEASE, 1.0.5.BUILD-SNAPSHOT and 1.1.0.BUILD-SNAPSHOT.  Far easier to just see the example code and json than try to explain it in English see below.

Steps to Reproduce
1.  git clone https://github.com/pfrank13/plugin-dependency-scc.git
2. git checkout execute_bug
2.  ./mvnw clean install -Pextending && ./mvnw clean install
3. observe the stack trace

Output
```java
com.jayway.jsonpath.InvalidPathException: Arguments to function: 'get' are not closed properly.
	at com.jayway.jsonpath.internal.path.PathCompiler.parseFunctionParameters(PathCompiler.java:370)
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:211)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145)
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:165)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:139)
	at com.jayway.jsonpath.internal.path.PathCompiler.readArrayToken(PathCompiler.java:541)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:133)
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:231)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145)
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:165)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:139)
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:118)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:54)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:69)
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:149)
	at org.springframework.cloud.contract.verifier.tests.ExampleTest.validate_example(ExampleTest.java:33)
```

Generated test line in and: part of the then
```java
DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
optionalNotNullOrEmptyString(parsedJson.read("$.myArray[0].notABugGeneratedHere"));
optionalNotNullOrEmptyString(parsedJson.read("$.myArray\")[0].get(\"anotherArrayNeededForBug[0].optionalNotEmpty"));
```

Example JSON
```javascript
{
  "myArray": [
    {
      "notABugGeneratedHere": "foo",
      "anotherArrayNeededForBug": [
        {
          "optionalNotEmpty": "12"
        }
      ]
    }
  ]
}
```

Contract DSL:
```groovy
Contract.make {
    request {
        method 'GET'
        urlPath '/foo'
        headers {
            accept(applicationJson())
            contentType(applicationJson())
        }
    }
    response {
        status 200
        body ([
            myArray:[
                            [
                                notABugGeneratedHere: execute('optionalNotNullOrEmptyString($it)'),
                                anotherArrayNeededForBug:[
                                                            [
                                                                optionalNotEmpty: execute('optionalNotNullOrEmptyString($it)')
                                                            ]
                                                         ]
                            ]
                         ]
        ])
        headers {
            contentType(applicationJson())
        }
    }
}
```

As an aside, is it a larger issue that the code being generated is only checking the 0th element in the array?  When not using execute the generated code appears to check all elements in an array.  This is potentially another issue that should be taken care of separately although I'm not sure.

**Comment by marcingrzejszczak** [comment]
Have you turned on the experimental support for order checking in arrays? Or nothing like this has been turned on?

**Comment by marcingrzejszczak** [comment]
In general when you have more complex arrays or the order matters I'd suggest using `test` / `stub` matchers section

**Comment by pfrank13** [comment]
If I do it's not knowingly, if that is in the plugin declaration here's mine
```xml
        <plugin>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-contract-maven-plugin</artifactId>
          <extensions>true</extensions>
          <configuration>
            <packageWithBaseClasses>com.example</packageWithBaseClasses>
            <testMode>EXPLICIT</testMode>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>${project.groupId}</groupId>
              <artifactId>extending_dsl</artifactId>
              <version>${project.version}</version>
            </dependency>
          </dependencies>
        </plugin>
```

**Comment by pfrank13** [comment]
In my case order doesn't matter or anything, just validating that the attributes in the array, if present, aren't empty.  That's the overall validation case.

**Comment by marcingrzejszczak** [comment]
Ok I'll have to take a deeper look into it

**Comment by marcingrzejszczak** [comment]
For a contract

```groovy
[
						myArray:[
								[
										notABugGeneratedHere: $(c("foo"), p(execute('assertThat((String)$it).isEqualTo("foo")'))),
										anotherArrayNeededForBug:[
												[
														optionalNotEmpty: $(c("foo"), p(execute('assertThat((String)$it).isEqualTo("12")')))
												]
										],
										yetAnotherArrayNeededForBug:[
												[
														optionalNotEmpty: $(c("foo"), p(execute('assertThat((String)$it).isEqualTo("22")')))
												]
										]
								],
								[
										anotherArrayNeededForBug2:[
												[
														optionalNotEmpty: $(c("foo"), p(execute('assertThat((String)$it).isEqualTo("122")')))
												]
										]
								],
						]
				]
```

the following test will be generated

```java
// given:
  MockMvcRequestSpecification request = given()
    .header("Accept", "application/json")
    .header("Content-Type", "application/json");

 // when:
  ResponseOptions response = given().spec(request)
    .get("/foo");

 // then:
  assertThat(response.statusCode()).isEqualTo(200);
  assertThat(response.header("Content-Type")).matches("application/json.*");
 // and:
  DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
  assertThatJson(parsedJson).array("myArray").hasSize(2);
  assertThatJson(parsedJson).array("myArray").array("anotherArrayNeededForBug").hasSize(1);
  assertThatJson(parsedJson).array("myArray").array("yetAnotherArrayNeededForBug").hasSize(1);
  assertThatJson(parsedJson).array("myArray").array("anotherArrayNeededForBug2").hasSize(1);
  assertThat((String)parsedJson.read("$.myArray[0].notABugGeneratedHere")).isEqualTo("foo");
  assertThat((String)parsedJson.read("$.myArray[0].anotherArrayNeededForBug[0].optionalNotEmpty")).isEqualTo("12");
  assertThat((String)parsedJson.read("$.myArray[0].yetAnotherArrayNeededForBug[0].optionalNotEmpty")).isEqualTo("22");
  assertThat((String)parsedJson.read("$.myArray[1].anotherArrayNeededForBug2[0].optionalNotEmpty")).isEqualTo("122");

```

looks good and it checks all entries
