### ISSUE TITLE
Spring Cloud Contract with Spring Cloud Stream

### ISSUE THREAD

**Issue by vishukadam** [spring-cloud/spring-cloud-contract#376]
Is it possible to create SpringCloudContract for (SpringCloudStream) Processor project(SpringCloudStream) as producer and consumer?
Processor has both INPUT and OUTPUT to be tested. I have created a contract for Source (producer) and Processor(consumer). It works fine. 
Now I want to make contract between Processor as producer  and Sink as consumer. 
I implemented producer contract on Processor project (along with consumer contract)it failed with NullPointerException unbale to resolve destination "verifications" (jar version:spring-cloud-contract-verifier-1.0.4.RELEASE.jar). This value "verifications "is set in contract groovy file(sentTo  'verifications'). I have also set the application.properties with "spring.cloud.stream.bindings.output.destination = verifications.
I also tried changing name of the destination in groovy and properties file.
Kindly provide a sample link if available.

Thanks,
Kind Regards.

**Comment by marcingrzejszczak** [comment]
A stacktrace would be valuable cause I can only guess what the reasons for the error can be.

Check this sample - https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/producer . It's working fine so ensure that you have all the necessary dependencies in your project.

Also here you have an example of a processor - https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_scenario_2_output_triggered_by_input . But most likely you can change it to 2 separate contracts as described here https://github.com/spring-cloud/spring-cloud-contract/issues/321

**Comment by vishukadam** [comment]
Please find attached log file.
[log.txt](https://github.com/spring-cloud/spring-cloud-contract/files/1194693/log.txt)

**Comment by marcingrzejszczak** [comment]
I think that you're missing `@EnableBinding` or proper channel name. Without a sample it's impossible to help you. Also please first analyze the provided samples.

**Comment by vishukadam** [comment]
Thanks,
I used the "spring-cloud-contract-verifier" and "spring-cloud-starter-contract-verifier" with version "1.2.0.BUILD-SNAPSHOT", it worked fine but affects the consumer contract for stub runner.

In my approach as mentioned earlier I have A(source) where is have implemented producer contract (Pa).
B(processor), so B input is consumer of contract (Pa). I have C(sink), so B output is producer contract (Pb)and C input is consumer of contract(Pb).  A --> B --> C.  I have run the contract independently it works fine. But when it try to create producer and consumer in B, I have problem.
I get the error given below please attached log file.

I have observed that "spring-cloud-starter-contract-stub-runner" refers to "spring-cloud-contract-verifier" and "spring-cloud-starter-contract-verifier" version 1.0.4 hence I get the error:

> Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.contract.verifier.util.ContractVerifierDslConverter.convert(Ljava/io/File;)Lorg/springframework/cloud/contract/spec/Contract;
	at org.springframework.cloud.contract.stubrunner.StubRepository$2.visitFile(StubRepository.java:134) ~[spring-cloud-contract-stub-runner-1.0.4.RELEASE.jar:1.0.4.RELEASE]
	at org.springframework.cloud.contract.stubrunner.StubRepository$2.visitFile(StubRepository.java:127) ~[spring-cloud-contract-stub-runner-1.0.4.RELEASE.jar:1.0.4.RELEASE]
	at java.nio.file.Files.walkFileTree(Files.java:2670) ~[na:1.8.0_121]
	at java.nio.file.Files.walkFileTree(Files.java:2742) ~[na:1.8.0_121]
	at org.springframework.cloud.contract.stubrunner.StubRepository.collectContractDescriptors(StubRepository.java:126) ~[spring-cloud-contract-stub-runner-1.0.4.RELEASE.jar:1.0.4.RELEASE]
	at org.springframework.cloud.contract.stubrunner.StubRepository.contractDescriptors(StubRepository.java:119) ~[spring-cloud-contract-stub-runner-1.0.4.RELEASE.jar:1.0.4.RELEASE]
	at org.springframework.cloud.contract.stubrunner.StubRepository.contracts(StubRepository.java:75) ~[spring-cloud-contract-stub-runner-1.0.4.RELEASE.jar:1.0.4.RELEASE]
	at org.springframework.cloud.contract.stubrunner.StubRepository.<init>(StubRepository.java:55) ~[spring-cloud-contract-stub-runner-1.0.4.RELEASE.jar:1.0.4.RELEASE]
[log.txt](https://github.com/spring-cloud/spring-cloud-contract/files/1196813/log.txt)

Following is the pom.xml

[pom.txt](https://github.com/spring-cloud/spring-cloud-contract/files/1196826/pom.txt)



		`

**Comment by vishukadam** [comment]
Thanks!
My issue resolved.
