### ISSUE TITLE
Spring cloud contract and wiremock

### ISSUE THREAD

**Issue by vilkg** [spring-cloud/spring-cloud-contract#377]
hi. 

Background: I used wiremock for integration testing and I am trying to adopt spring cloud contract. I still have wiremock mappings in my repository and I still use original wiremock functionality, like initializing wiremock server with jUnit WireMockRule rule. 

The problem is, that when I remove original wiremock dependency (artifact wiremock-standalone), my integration tests which uses WireMockRule class  fails to initialize servers. 

`Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/io/NetworkTrafficListener
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory.buildHttpServer(JettyHttpServerFactory.java:31)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:73)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.<init>(WireMockRule.java:42)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.<init>`

When I add back my wiremock dependency, integration tests pass, but contract tests fails with error 

`java.lang.ClassCastException: org.springframework.cloud.contract.verifier.builder.handlebars.HandlebarsJsonPathHelper cannot be cast to wiremock.com.github.jknack.handlebars.Helper`

Any advice?

**Comment by marcingrzejszczak** [comment]
> The problem is, that when I remove original wiremock dependency (artifact wiremock-standalone), my integration tests which uses WireMockRule class fails to initialize servers.

The `wiremock-standalone` seems like a wrong artifact to add BTW.

> Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/io/NetworkTrafficListener at 

looks as if it wanted to use Jetty for some reason. Do you have `spring-cloud-starter-contract-stub-runner` on your classpath? If not then add the starter cause the starter adds `spring-cloud-contract-wiremock` to the classpath which makes use of Spring Boot servlet container and not Jetty. If you want to use Jetty add `spring-cloud-starter-contract-stub-runner-jetty`.

> When I add back my wiremock dependency, integration tests pass, but contract tests fails with error

seems like version mismatch

**Comment by vilkg** [comment]
Thanks for answer. 

Why is wiremock-standalone wrong dependency? It's recommended by wiremock in spring boot apps. 

I do have stub runner. I have tried stub runner jetty and it partially solved the problem - wiremock server is created, but requests fails with 'Software caused connection abort: recv failed' error.

**Comment by marcingrzejszczak** [comment]
Ok I've gone to far with such a statement. `wiremock-standalone` takes in Jetty cause it's a shaded JAR. If you add `spring-cloud-contract-wiremock` dependency then we take care of the server on which WireMock is running. If you include  the `standalone` module you will have jetty on the classpath, whereas we are by default trying to exclude jetty. That's why I said that you could consider adding non-standalone version fo WireMock. Actually the best solution is to let Spring Cloud BOM decide on the versions.

I'd need to see your code and sample to help you more I guess... Is there an option for you to upload the code somewhere?

**Comment by marcingrzejszczak** [comment]
Closing due to inactivity

**Comment by thaiden** [comment]
I am experiencing same issue 
```

java.lang.ClassCastException: org.springframework.cloud.contract.verifier.builder.handlebars.HandlebarsJsonPathHelper cannot be cast to wiremock.com.github.jknack.handlebars.Helper

	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.<init>(ResponseTemplateTransformer.java:51)
	at org.springframework.cloud.contract.stubrunner.provider.wiremock.WireMockHttpServerStub.responseTemplateTransformer(WireMockHttpServerStub.java:50)
	at org.springframework.cloud.contract.stubrunner.provider.wiremock.WireMockHttpServerStub.config(WireMockHttpServerStub.java:44)
	at org.springframework.cloud.contract.stubrunner.provider.wiremock.WireMockHttpServerStub.start(WireMockHttpServerStub.java:84)
	at org.springframework.cloud.contract.stubrunner.StubServer.start(StubServer.java:51)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.startStubServers(StubRunnerExecutor.java:250)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.runStubs(StubRunnerExecutor.java:77)
	at org.springframework.cloud.contract.stubrunner.StubRunner.runStubs(StubRunner.java:70)
	at org.springframework.cloud.contract.stubrunner.BatchStubRunner.runStubs(BatchStubRunner.java:46)
```

**Comment by marcingrzejszczak** [comment]
Can you upload your sample somewhere?

**Comment by thaiden** [comment]
slightly modified sample of source, i cant upload real source
```
@Test
@WebAppConfiguration
@ContextConfiguration(classes = { HydraXApiControllerTest.TestConfig.class})
public class XApiControllerTest extends AbstractTestNGSpringContextTests {

    private WireMockServer wireMockServer;
    
    @Autowired
    private WebApplicationContext wac;
    
    @BeforeClass
    public void beforeClass() {
        wireMockServer = new WireMockServer(wireMockConfig().port(8089));
        wireMockServer.start();
        configureFor(8089);
    }

    @AfterClass
    public void afterClass() {
        try {
            wireMockServer.stop();
        } catch (Exception e) {}
    }

    @BeforeMethod
    public void beforeMethod() {
        mockMvc = MockMvcBuilders.webAppContextSetup(wac).build();
    }

    @Test
    public void wiremockWorksAsExpected() {
        stubFor(get(urlEqualTo("/api/resource/"))
                    .willReturn(aResponse()
                                    .withStatus(HttpStatus.OK.value())
                                    .withHeader("Content-Type", TEXT_PLAIN_VALUE)
                                    .withBody("test")));

        response = restTemplate.getForEntity("http://localhost:8089/api/resource/", String.class);

        assertTrue(response.getBody().toString().contains("test"));
        assertTrue(response.getStatusCode().equals(HttpStatus.OK));

        verify(getRequestedFor(urlMatching("/api/resource/.*")));
    }
    @Configuration
    public static class TestConfig extends WebMvcConfigurationSupport {
        @Bean
        public ConfigProperties configProperties() {
            return new ConfigProperties(new StandardEnvironment(), "Hydra events test");
        }

        @Bean
        public XApiController XApiController() {
            return  spy(new XApiController(configProperties()));
        }
    }
}
```

pom.xml

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-contract-stub-runner</artifactId>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-tomcat</artifactId>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>javax.servlet-api</artifactId>
    <scope>compile</scope>
    </dependency>
<dependency>
....
<dependency>
    <groupId>com.github.tomakehurst</groupId>
    <artifactId>wiremock-standalone</artifactId>
    <version>2.6.0</version>
</dependency>
```

contract test

```java
@ContextConfiguration(classes = { ConsumerConfig.class})
@Test
@WebAppConfiguration
public class ConsumerTest extends AbstractTestNGSpringContextTests {

    private BatchStubRunner stubFinder;
    static {
        System.setProperty("someServiceUrl", "http://localhost:8090/");
        System.setProperty("stubrunner.work-offline", "false");
        System.setProperty("stubrunner.ids", "org.some.package:some-service:+:stubs:8090");
        System.setProperty("stubrunner.repository.root", "http://engci-maven.cisco.com/artifactory/webex-cca-group");
    }
    
    @Inject
    @InjectMocks
    private SomeService someServiceV2;

    @BeforeClass
    void setup() {
        startStubs();

        MockitoAnnotations.initMocks(this);
    }

    public void testGetData() {
        UUID userId = UUID.randomUUID();

        Data someData = someServiceV2.get(userId, mockAuthInfo(userId));

        Assert.assertNotNull(someData);
        Assert.assertEquals(someData.id, id);
    }


    private StubRunnerOptions defaultStubRunnerOptions() {
        StubRunnerOptionsBuilder builder = new StubRunnerOptionsBuilder()
            .withStubRepositoryRoot(System.getProperty("stubrunner.repository.root", ""))
            .withWorkOffline(Boolean.parseBoolean(System.getProperty("stubrunner.work-offline", "false")))
            .withStubsClassifier(System.getProperty("stubrunner.classifier", "stubs"))
            .withStubs(System.getProperty("stubrunner.ids", ""))
            .withUsername(System.getProperty("stubrunner.username"))
            .withPassword(System.getProperty("stubrunner.password"))
            .withStubPerConsumer(Boolean.parseBoolean(System.getProperty("stubrunner.stubsPerConsumer", "false")))
            .withConsumerName(System.getProperty("stubrunner.consumer-name"));
        String proxyHost = System.getProperty("stubrunner.proxy.host");
        if (proxyHost != null) {
            builder.withProxy(proxyHost, Integer.parseInt(System.getProperty("stubrunner.proxy.port")));
        }
        return builder.build();
    }

    protected void startStubs()
    {
        stubFinder = new BatchStubRunnerFactory(defaultStubRunnerOptions()).buildBatchStubRunner();
        stubFinder.runStubs();
    }
}
```

consumer config
```java
@Configuration
public class ConsumerConfig extends WebMvcConfigurationSupport {
    @Bean
    public SomeService someServiceV2() {
        return spy(new SomeService());
    }
}
```

**Comment by marcingrzejszczak** [comment]
I think you shouldn't be using 

```        
wireMockServer = new WireMockServer(wireMockConfig().port(8089));
```

instead use `@AutoConfigureWireMock(port=8089)` and inject the `WireMockServer` as a bean.

**Comment by marcingrzejszczak** [comment]
Ping @vilkg ?

**Comment by shahgopal** [comment]
it still does not work with the same sample, Contract test continue to fail with classCastException

**Comment by marcingrzejszczak** [comment]
@shahgopal can you upload your sample somewhere on github?

**Comment by shahgopal** [comment]
Sure, I will need some time to do the same, will work on it soon!

**Comment by thaiden** [comment]
@marcingrzejszczak with `wireMockServer = new WireMockServer(wireMockConfig().port(8089));` it worked. But i was still puzzled why it didnt work with example I've provided previously.
