### ISSUE TITLE
Looking for stubs at the wrong location even though the running the producer I can see the line 'Installing ...' the artifact at the right location

### ISSUE THREAD

**Issue by swarajroy** [spring-cloud/spring-cloud-contract#379]
An excerpt of the test 

```
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureWireMock(port = 8081)
public class TravelRequestServiceApplicationTests {
@Rule
	public StubRunnerRule rule = new StubRunnerRule()
			.downloadStub("org.agiledev.learnbydoing","approval-service")
			.workOffline(true)
			.withPort(8083);

@Test
	public void test_should_return_all_approvals_using_stubs(){
		String json = "[\"John\",\"Rambo\"]";

		RestTemplate restTemplate = new RestTemplate();
		ResponseEntity<String> entity = restTemplate.getForEntity("http://localhost:8083/approvals", String.class);

		BDDAssertions.then(entity.getStatusCodeValue()).isEqualTo(201);
		BDDAssertions.then(entity.getBody()).isEqualTo(json);
	}

}
```

stack trace

```
java.lang.IllegalArgumentException: For groupId [org.agiledev.learnbydoing] artifactId [approval-service] and classifier [stubs] the version was not resolved! The following exceptions took place [org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata org.agiledev.learnbydoing:approval-service/maven-metadata.xml in local (/Users/swarajroy/IdeaProjects/contract-driven-consumer/travel-request-service/${user.home}/.m2/repository)]

	at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.resolveHighestArtifactVersion(AetherStubDownloader.java:235)
	at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.getVersion(AetherStubDownloader.java:192)
	at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.downloadAndUnpackStubJar(AetherStubDownloader.java:199)
	at org.springframework.cloud.contract.stubrunner.StubRunnerFactory.createStubsFromServiceConfiguration(StubRunnerFactory.java:60)
	at org.springframework.cloud.contract.stubrunner.BatchStubRunnerFactory.buildBatchStubRunner(BatchStubRunnerFactory.java:59)
	at org.springframework.cloud.contract.stubrunner.junit.StubRunnerRule$1.before(StubRunnerRule.java:65)
	at org.springframework.cloud.contract.stubrunner.junit.StubRunnerRule$1.evaluate(StubRunnerRule.java:57)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by marcingrzejszczak** [comment]
Your path is broken. Users/swarajroy/IdeaProjects/contract-driven-consumer/travel-request-service/${user.home}/.m2/repository. You have an unresolved user.home variable inside the path

**Comment by marcingrzejszczak** [comment]
Ping?

**Comment by swarajroy** [comment]
Hi Marcin,

Many thanks,

my maven settings had a placeholder instead of an actual hence the issue. i
fixed that and everything started to work. Magic.

Cheers
Swaraj

**Comment by marcingrzejszczak** [comment]
Glad to hear that!
