### ISSUE TITLE
Exception when jar in .m2 repository

### ISSUE THREAD

**Issue by Orlamooney** [spring-cloud/spring-cloud-contract#380]
Hi, 

I am getting the exception below when running a build( its part of a CI Build with maven.) I was hoping you could help, i was wondering if there is a method for it to use the local jar if found, or else download it or  if there is any method that could be utilised to workaround this issue?

```
build    16-Aug-2017 05:05:14    Caused by: java.lang.IllegalStateException: The artifact was found in the local repository but you have explicitly stated that it should be downloaded from a remote one
build    16-Aug-2017 05:05:14        at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.unpackedJar(AetherStubDownloader.java:156)
build    16-Aug-2017 05:05:14        at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.downloadAndUnpackStubJar(AetherStubDownloader.java:205)
build    16-Aug-2017 05:05:14        at org.springframework.cloud.contract.stubrunner.StubRunnerFactory.createStubsFromServiceConfiguration(StubRunnerFactory.java:60)
build    16-Aug-2017 05:05:14        at org.springframework.cloud.contract.stubrunner.BatchStubRunnerFactory.buildBatchStubRunner(BatchStubRunnerFactory.java:59)
build    16-Aug-2017 05:05:14        at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration.batchStubRunner(StubRunnerConfiguration.java:77)
build    16-Aug-2017 05:05:14        at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration$$EnhancerBySpringCGLIB$$9c177921.CGLIB$batchStubRunner$0(<generated>)
```

Any advice would be appreciated!

**Comment by marcingrzejszczak** [comment]
That's not possible from the code and it's designed like this for a reason (you can read more about this here https://github.com/spring-cloud/spring-cloud-contract/issues/312 ). Briefly, the idea is such that you're saying that you want the stub to be downloaded from a remote repository. However, either there is no such entry or the local, cached one is more suitable (is newer or sth). In this case, it's not a desired situation to take the cached one since you specifically said that you want the stub to be _downloaded_. Your only way to work around this is to run `rm -rf ~/.m2/repository/com/example/foo` to ensure that you will always download a fresh copy of the artifact.

**Comment by marcingrzejszczak** [comment]
Ping @Orlamooney ?

**Comment by marcingrzejszczak** [comment]
Closing due to inactivity

**Comment by icehockeystar** [comment]
that's very weak.

**Comment by marcingrzejszczak** [comment]
What's weak?
