### ISSUE TITLE
Wrong collection assertion method is chosen for SpringCloudContractAssertions

### ISSUE THREAD

**Issue by adamkrol93** [spring-cloud/spring-cloud-contract#381]
We have created Contract with testMatchers according to the documentation. But when tests are generated then wrong assertions are created.
We are using version 1.0.5 because 1.1.2 have to many changes for example added root folder to stubsOutputDir. 

For example we have 
```
import org.springframework.cloud.contract.spec.Contract

Contract.make {
    request {
        method 'GET'
        urlPath(path)
    }
    response {
        status 200
        headers {
            header 'Content-Type': value(test(regex('application/json(;.*)?')), stub('application/json;charset=UTF-8'))
        }
        body(events: [[
                                 operation          : 'EXPORT',
                                 eventId            : '16f1ed75-0bcc-4f0d-a04d-3121798faf99',
                                 status             : 'OK'
                         ], [
                                 operation          : 'INPUT_PROCESSING',
                                 eventId            : '3bb4ac82-6652-462f-b6d1-75e424a0024a',
                                 status             : 'OK'
                         ]
                ]
        )
        testMatchers {
            jsonPath('$.events[0].operation', byRegex('.+'))
            jsonPath('$.events[0].eventId', byRegex('^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})$'))
            jsonPath('$.events[0].status', byRegex('.+'))
        }
    }
}
``` 

and generated test looks like 

```
import com.jayway.jsonpath.DocumentContext
import com.jayway.jsonpath.JsonPath

import static com.jayway.restassured.RestAssured.*
import static com.toomuchcoding.jsonassert.JsonAssertion.assertThatJson

class EventSpec  {

	def validate_listEvents() throws Exception {
		given:
			def request = given()

		when:
			def response = given().spec(request)
					.get(urlPath")

		then:
			response.statusCode == 200
			response.header('Content-Type') ==~ java.util.regex.Pattern.compile('application/json(;.*)?')
		and:
			DocumentContext parsedJson = JsonPath.parse(response.body.asString())
			assertThatJson(parsedJson).array("['events']").contains("['eventId']").isEqualTo("16f1ed75-0bcc-4f0d-a04d-3121798faf99")
			assertThatJson(parsedJson).array("['events']").contains("['operation']").isEqualTo("EXPORT")
			assertThatJson(parsedJson).array("['events']").contains("['operation']").isEqualTo("INPUT_PROCESSING")
			assertThatJson(parsedJson).array("['events']").contains("['eventId']").isEqualTo("3bb4ac82-6652-462f-b6d1-75e424a0024a")
			assertThatJson(parsedJson).array("['events']").contains("['status']").isEqualTo("OK")
		and:
			assertThat(parsedJson.read("\$.events[0].operation", String.class)).matches(".+")
			assertThat(parsedJson.read("\$.events[0].eventId", String.class)).matches("^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})\$")
			assertThat(parsedJson.read("\$.events[0].status", String.class)).matches(".+")
		}
}
```

**Comment by marcingrzejszczak** [comment]
Why is the wrong assertion created?

You wanted

```
 jsonPath('$.events[0].operation', byRegex('.+'))
            jsonPath('$.events[0].eventId', byRegex('^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})$'))
            jsonPath('$.events[0].status', byRegex('.+'))
```

you got

```
assertThat(parsedJson.read("\$.events[0].operation", String.class)).matches(".+")
			assertThat(parsedJson.read("\$.events[0].eventId", String.class)).matches("^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})\$")
			assertThat(parsedJson.read("\$.events[0].status", String.class)).matches(".+")
```

It's exactly the same what you requested.

**Comment by adamkrol93** [comment]
Yes i have this but i have those additional assertions. 

```
assertThatJson(parsedJson).array("['events']").contains("['eventId']").isEqualTo("16f1ed75-0bcc-4f0d-a04d-3121798faf99")
			assertThatJson(parsedJson).array("['events']").contains("['operation']").isEqualTo("EXPORT")
			assertThatJson(parsedJson).array("['events']").contains("['operation']").isEqualTo("INPUT_PROCESSING")
			assertThatJson(parsedJson).array("['events']").contains("['eventId']").isEqualTo("3bb4ac82-6652-462f-b6d1-75e424a0024a")
			assertThatJson(parsedJson).array("['events']").contains("['status']").isEqualTo("OK")
```

Our application is not able to return exactly those events with that id.
And also this is only the piece of it our stub have 20 elements in events array. So it is very hard to provide them from real application.

**Comment by marcingrzejszczak** [comment]
Those assertions are there cause you need to provide also assertions for `$.events[1]` entries. In your case you can actually create a `testMatcher` for the whole `$.events` array and execute `byCommand(...)` where you will provide the coded assertion. That way you will assert precisely what you need. Does it make sense?

**Comment by adamkrol93** [comment]
After adding 
```
jsonPath('$.events', byType {
                minOccurrence(1)
            })
```
I have desired assertions but they are not working.
I do not know if it is connected with this but i have error like this:
```
Condition failed with Exception:

    assertThat(parsedJson.read("\$.events[0].operation", String.class)).matches(".+")
    |          |          |
    |          |          ORDER_ACK
    |          com.jayway.jsonpath.internal.JsonContext@711a4711
    groovy.lang.MissingMethodException: No signature of method: order.EventSpec.assertThat() is applicable for argument types: (java.lang.String) values: [ORDER_ACK]
        at order.EventSpec.validate_listEvents(EventSpec.groovy:27)

        Caused by:
        groovy.lang.MissingMethodException: No signature of method: order.EventSpec.assertThat() is applicable for argument types: (java.lang.String) values: [ORDER_ACK]
            at order.EventSpec.validate_listEvents(EventSpec.groovy:27)

```

**Comment by marcingrzejszczak** [comment]
What the hell is it? :D `order.EventSpec.assertThat()` looks like a bad import. Can you show the whole generated test? Also the configuration of the plugin?

**Comment by adamkrol93** [comment]
Generated Specification:
```
package pwc.v3.mno.order

import com.jayway.jsonpath.DocumentContext
import com.jayway.jsonpath.JsonPath
import pwc.BaseContractSpecification

import static com.jayway.restassured.RestAssured.*
import static com.toomuchcoding.jsonassert.JsonAssertion.assertThatJson

class EventSpec extends BaseContractSpecification {

	def validate_listEvents() throws Exception {
		given:
			def request = given()

		when:
			def response = given().spec(request)
					.get(urlPath)

		then:
			response.statusCode == 200
			response.header('Content-Type') ==~ java.util.regex.Pattern.compile('application/json(;.*)?')
		and:
			DocumentContext parsedJson = JsonPath.parse(response.body.asString())
		and:
			assertThat(parsedJson.read("\$.events[0].operation", String.class)).matches(".+")
			assertThat(parsedJson.read("\$.events[0].eventId", String.class)).matches("^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})\$")
			assertThat(parsedJson.read("\$.events[0].status", String.class)).matches(".+")
			assertThat((Object) parsedJson.read("\$.events")).isInstanceOf(java.util.List.class)
			assertThat(parsedJson.read("\$.events", java.util.Collection.class).size()).isGreaterThanOrEqualTo(1)
	}

}
```

Configuration:

```
contracts {
    targetFramework = TestFramework.SPOCK
    testMode = TestMode.EXPLICIT
    generatedTestSourcesDir = project.file("$project.buildDir/generated-src/test")
    contractsDslDir = file("$project.buildDir/contracts")
    contractsWorkOffline = true
}
```

and another one

```
contracts {
    basePackageForTests = 'pwc'
    baseClassForTests = 'pwc.BaseContractSpecification'
}
```

**Comment by marcingrzejszczak** [comment]
Which version of sc-contract are you using?

**Comment by adamkrol93** [comment]
Written in first post: 1.0.5.RELEASE

**Comment by marcingrzejszczak** [comment]
Yeah, sorry - I think I'm getting blind ;) Can you see if you have the same error in `1.1.3.RELEASE`?

**Comment by adamkrol93** [comment]
The is no 1.1.3.RELEASE. I used 1.1.2.RELEASE. Did not help.

**Comment by marcingrzejszczak** [comment]
That's super strange... Can you try to generate that in Java and not in Spock and see if it's working fine?

**Comment by marcingrzejszczak** [comment]
I think it's a bug in Spring Cloud Contract that the static import `org.springframework.cloud.contract.verifier.assertion.SpringCloudContractAssertions.assertThat` is not added for Spock...  As a workaround you can pass to the gradle configuration the `staticImports` property.

```groovy
contracts {
    basePackageForTests = 'pwc'
    baseClassForTests = 'pwc.BaseContractSpecification'
    staticImports = ["org.springframework.cloud.contract.verifier.assertion.SpringCloudContractAssertions.assertThat"]
}
```

**Comment by adamkrol93** [comment]
After adding staticImports it works now.
But i think that you could add information to docs that if we want to use testMatchers other assertions will be generated unless we add assertion for whole $.events.

**Comment by marcingrzejszczak** [comment]
I was more than sure that I've added it to the docs but actually I can't find it ;) I'll fix the spock issue and update the docs

**Comment by adamkrol93** [comment]
So i think that you can close this issue unless you want to change it to spock issue connected task.

**Comment by adamkrol93** [comment]
BTW. There is also a problem with those assertions
```
Condition failed with Exception:

    assertThat(parsedJson.read("\$.events", java.util.Collection.class)).hasSizeGreaterThanOrEqualTo(1)
    |          |          |                                              |
    |          |          |                                              org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: org.assertj.core.api.ListAssert.hasSizeGreaterThanOrEqualTo() is applicable for argument types: (java.lang.Integer) values: [1]
    |          |          [[operation:ORDER_ACK, eventId:e519c8a7-833f-11e7-8c2a-0fe78575f9a5, status:OK, creationTime:2017-08-17T11:33:30.794Z, transactionId:e519c8a7-833f-11e7-8c2a-0fe78575f9a5, parentTransactionId:e519c8a7-833f-11e7-8c2a-0fe78575f9a6, serviceName:PGS, quantity:1, flowId:2b1ab407-ac45-11e6-8a8d-c50e9760d1b6, type:FINAL, messages:[]]]
    |          com.jayway.jsonpath.internal.JsonContext@65ea9ff4
    org.assertj.core.api.ListAssert@1
        at pwc.v3.mno.order.EventSpec.validate_listEvents(EventSpec.groovy:40)

        Caused by:
        org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: org.assertj.core.api.ListAssert.hasSizeGreaterThanOrEqualTo() is applicable for argument types: (java.lang.Integer) values: [1]
```

**Comment by marcingrzejszczak** [comment]
You have this problem in which version of sc-contract?

**Comment by adamkrol93** [comment]
1.1.2.RELEASE

**Comment by marcingrzejszczak** [comment]
Ping @adamkrol93 ?

**Comment by adamkrol93** [comment]
I think so. We have
```
springContractVersion=1.1.2.RELEASE
```

```
classpath "org.springframework.cloud:spring-cloud-contract-gradle-plugin:$springContractVersion"
```

and

```
"org.springframework.cloud:spring-cloud-starter-contract-verifier:$springContractVersion",
```

**Comment by marcingrzejszczak** [comment]
That is superstrange... Can you ensure that you have the proper `import static` to `SpringCloudContractAssertions.assertThat`  in the generated test?

**Comment by adamkrol93** [comment]
Here are imports in generated tests:
```
import com.jayway.jsonpath.DocumentContext
import com.jayway.jsonpath.JsonPath
import com.oberthur.dps.pwc.BaseProfileWarehouseContractSpecification

import static com.jayway.restassured.RestAssured.*
import static com.toomuchcoding.jsonassert.JsonAssertion.assertThatJson
import static org.springframework.cloud.contract.verifier.assertion.SpringCloudContractAssertions.assertThat
```

**Comment by marcingrzejszczak** [comment]
So that looks fine... Do you still get the same exception? If that's the case I think I'll need a sample project cause I have no idea what's going wrong with this issue

**Comment by marcingrzejszczak** [comment]
Actually, I think I've managed to find the reason for this! I think that something has changed on the AssertJ side. I know how to fix this - I'll fix it today

**Comment by adamkrol93** [comment]
Nice. Looking forward to test it.
