### ISSUE TITLE
Question about private maven repository download contracts jar

### ISSUE THREAD

**Issue by Pastel001** [spring-cloud/spring-cloud-contract#437]
question:
we have a private maven repository,and we deploy upload the contracts jar into it.
on the producer project,i config "contractsRepositoryUrl” so that to down contracts jar from the private maven repository.
but a porblem occur.the contracts jar can down load,but it also try to download "cloud:spring-cloud-contract-maven-plugin" from our private maven repository.
How can i config the producer project pom,i just want to down contracts jar,not the plugin.
Thank you very much.
spring cloud contract version is 1.1.3.RELEASE.
producer pom is like this:
```
<build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>2.4</version>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <version>${spring-cloud-contract.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <baseClassMappings>
                        <baseClassMapping>
                            <contractPackageRegex>.*rest.*vehicle.*</contractPackageRegex>
                            <baseClassFQN>com.example.ExampleBase</baseClassFQN>
                        </baseClassMapping>
                    </baseClassMappings>
                    <!-- We want to use the JAR with contracts with the following coordinates -->
                    <contractDependency>
                        <groupId>com.example</groupId>
                        <artifactId>example-contracts</artifactId>
                    </contractDependency>
                    <!-- The JAR with contracts should be taken from Maven local -->
                    <!--<contractsWorkOffline>true</contractsWorkOffline>-->
                    <!-- The JAR with contracts will get downloaded from an external repo -->
                    <contractsRepositoryUrl>http://10.10.142.182:8082/nexus/content/repositories/Contract-Snapshot</contractsRepositoryUrl>
                    <!-- Base package for generated tests -->
                    <basePackageForTests>hkr</basePackageForTests>
                </configuration>
                <!-- this was added for testing purposes only -->
                <dependencies>
                    <dependency>
                        <groupId>org.springframework.cloud</groupId>
                        <artifactId>spring-cloud-contract-verifier</artifactId>
                        <version>${spring-cloud-contract.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```
mavin install log lis like this:
![default](https://user-images.githubusercontent.com/10250772/31477444-a968b39a-af3e-11e7-8fdc-699387234b5b.png)

**Comment by Pastel001** [comment]
detail log
···
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "coverage-per-test" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.1.3.RELEASE:generateTests (default-generateTests) on project hkr-fe: Execution default-generateTests of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.1.3.RELEASE:generateTests failed: The artifact was found in the local repository but you have explicitly stated that it should be downloaded from a remote one -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.1.3.RELEASE:generateTests (default-generateTests) on project hkr-fe: Execution default-generateTests of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.1.3.RELEASE:generateTests failed: The artifact was found in the local repository but you have explicitly stated that it should be downloaded from a remote one
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-generateTests of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.1.3.RELEASE:generateTests failed: The artifact was found in the local repository but you have explicitly stated that it should be downloaded from a remote one
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalStateException: The artifact was found in the local repository but you have explicitly stated that it should be downloaded from a remote one
	at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.unpackedJar(AetherStubDownloader.java:156)
	at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.downloadAndUnpackStubJar(AetherStubDownloader.java:205)
	at org.springframework.cloud.contract.stubrunner.ContractDownloader.unpackAndDownloadContracts(ContractDownloader.java:97)
	at org.springframework.cloud.contract.stubrunner.ContractDownloader.unpackedDownloadedContracts(ContractDownloader.java:49)
	at org.springframework.cloud.contract.maven.verifier.MavenContractsDownloader.downloadAndUnpackContractsIfRequired(MavenContractsDownloader.java:70)
	at org.springframework.cloud.contract.maven.verifier.GenerateTestsMojo.execute(GenerateTestsMojo.java:192)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
···

**Comment by marcingrzejszczak** [comment]
You have the exception cause you have the Jar already downloaded and it wasn't resolved from nexus. 

You have to have the pom misconfigured cause we're using aether to download the jar from the provided URL. It's not used for downloading the plugin

**Comment by Pastel001** [comment]
why it says i have explicitly stated that the plugin should be downloaded from a remote.
i have just change the way to get contracts jar from local to remote private maven repository.
i dont know which config let it to download from remote.
whick do you think is wrong？the config of pom or the config of private maven repository？

**Comment by Pastel001** [comment]
I have test the contracts jar can successfully download from the remote private nexus maven repository. 
even though the contract is already in the local repository,why it dont to download from the remote repository?

**Comment by marcingrzejszczak** [comment]
Like I mentioned previously. The plugin failed to download the stub JAR from Nexus. It however found the downloaded stub in your local `.m2`. Since you've defined that you want the stub to be downloaded (no `workOffline` flag), then your test should fail.

**Comment by Pastel001** [comment]
so why dont to download the remote private nexus maven repository?
i have test if i delete the stub jar from my local,it can successfully  down it from remote.
so why if  stub jar already in my local,it raise an exception?

**Comment by marcingrzejszczak** [comment]
I've answered your question in my previous comment

**Comment by Pastel001** [comment]
Sorry，I dont understand what is the reason？
But，thanks for your answer.
Thankyou

**Comment by marcingrzejszczak** [comment]
Since this problem has been repeatedly reported, this issue https://github.com/spring-cloud/spring-cloud-contract/issues/545 contains info on the enhancement used to fix this problem
