### ISSUE TITLE
cannot generate client stubs

### ISSUE THREAD

**Issue by hmalewska** [spring-cloud/spring-cloud-contract#438]
Hello,
I've got a problem to generate stubs for my contract. Could you help?

```
15:28:00.755 [DEBUG] [org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter] Will create a stub for contract [org.springframework.cloud.contract.verifier.file.ContractMetadata(.../contracts/validator.groovy, false, 1, null, [Contract(priority:null, request:Request(property:Request$ClientPatternValueDslProperty(), httpMethods:HttpMethods(), method:null, url:Url(queryParameters:null, super:DslProperty(clientValue:/orders/validator, serverValue:/orders/validator)), urlPath:null, headers:Request$RequestHeaders(), body:Body(super:DslProperty(clientValue:[contracts.validator$_run_closure1$_closure2$_closure4@4c3125ff], serverValue:[contracts.validator$_run_closure1$_closure2$_closure4@4c3125ff])), multipart:null, matchers:null), response:Response(Response$ServerPatternValueDslProperty(), null, null, Response$ResponseHeaders(), Body(super:DslProperty(clientValue:[contracts.validator$_run_closure1$_closure3$_closure7@d2ca3a9], serverValue:[contracts.validator$_run_closure1$_closure3$_closure7@d2ca3a9])), false, null), label:null, description:null, name:null, input:null, outputMessage:null, ignored:false)])]
15:28:00.756 [DEBUG] [org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter] Stub Generators [[org.springframework.cloud.contract.verifier.wiremock.DslToWireMockClientConverter@6a16ee0d]] will convert contents of [.../contracts]
15:28:00.815 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
15:28:00.815 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':generateClientStubs'
15:28:00.815 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :generateClientStubs FAILED
15:28:00.815 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :generateClientStubs (Thread[main,5,main]) completed. Took 0.426 secs.
15:28:00.815 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.11 completed (0 in use)
15:28:00.815 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 6.731 secs, idle: 0.004 secs
15:28:00.831 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
15:28:00.831 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
```

**Comment by marcingrzejszczak** [comment]
Can you present the whole stacktrace? Why did it fail?

**Comment by hmalewska** [comment]
Stacktrace:
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateClientStubs'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:256)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:253)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:175)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:244)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:217)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.springframework.cloud.contract.verifier.converter.ConversionContractVerifierException: Unable to make conversion of validator.groovy
        at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1$_closure2.doCall(RecursiveFilesConverter.groovy:105)
        at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1.doCall(RecursiveFilesConverter.groovy:67)
        at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1.call(RecursiveFilesConverter.groovy)
        at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter.processFiles(RecursiveFilesConverter.groovy:66)
        at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$processFiles.call(Unknown Source)
        at org.springframework.cloud.contract.verifier.plugin.GenerateWireMockClientStubsFromDslTask.generate(GenerateWireMockClientStubsFromDslTask.groovy:58)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 62 more
Caused by: java.lang.NullPointerException: Cannot invoke method withHeader() on null object
        at org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockRequestStubStrategy$_appendHeaders_closure7.doCall(WireMockRequestStubStrategy.groovy:144)
        at org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockRequestStubStrategy.appendHeaders(WireMockRequestStubStrategy.groovy:143)
        at org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockRequestStubStrategy.buildClientRequestContent(WireMockRequestStubStrategy.groovy:71)
        at org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockStubStrategy.toWireMockClientStub(WireMockStubStrategy.groovy:61)
        at org.springframework.cloud.contract.verifier.wiremock.DslToWireMockClientConverter.convertASingleContract(DslToWireMockClientConverter.groovy:42)
        at org.springframework.cloud.contract.verifier.wiremock.DslToWireMockClientConverter.convertContents(DslToWireMockClientConverter.groovy:51)
        at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1$_closure2$_closure3.doCall(RecursiveFilesConverter.groovy:91)
        at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1$_closure2.doCall(RecursiveFilesConverter.groovy:90)
        ... 75 more
`

**Comment by hmalewska** [comment]
Probably I already see the issue:
There is
`	String parseBody(GString value, ContentType contentType) {
		Object processedValue = extractValue(value, contentType, { Object o -> o instanceof DslProperty ? o.clientValue : o })
		if (processedValue instanceof GString) {
			return parseBody(processedValue.toString(), contentType)
		}
		return parseBody(processedValue, contentType)
	}
`
in BaseWireMockStubStrategy.groovy
and the issue is "cannot resolve symbol 'clientValue'" 

What do you think?

**Comment by marcingrzejszczak** [comment]
Can you show your contract?

**Comment by hmalewska** [comment]
`Contract.make {
    request {
        method: 'POST'
        url '/orders/validator'
        body([
                {
                    buyerId: "10204761"
                    items: [{
                                id: $(regex('[0-9]{10}')
                                price: null
                            }]
                }
        ])
        headers {
            contentType('application/vnd.allegro.purchase_validator.v2+json')
        }
    }
    response {
        status: 200
        body([
                {
                    id: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                    result: true
                    generalErrors: []
                    itemErrors: []
                }
        ])
        headers {
            contentType('application/vnd.allegro.purchase_validator.v2+json')
        }
    }
}`

**Comment by marcingrzejszczak** [comment]
You've made a lot of mistakes in the contract. This is how it should look like

```groovy
Contract groovyDsl = Contract.make {
				request {
					method 'POST'
					url '/orders/validator'
					body([
							[
								buyerId: "10204761",
								items: [
											id: $(regex('[0-9]{10}')),
													price: null
										]
							]
					])
					headers {
						contentType('application/vnd.allegro.purchase_validator.v2+json')
					}
				}
				response {
					status 200
					body([
							[
								id: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
								result: true,
								generalErrors: [],
								itemErrors: []
							]
					])
					headers {
						contentType('application/vnd.allegro.purchase_validator.v2+json')
					}
				}
			}
```

this is the list of mistakes
- `method` is method not a map. So `method(...)` instead of `method: ...`
- You're mixing Groovy notation of body with JSON one. 
- Assuming that you wanted to do Groovy notation you should do the following 
  -  You're missing `,` at the end od entries, 
  -  `$(regex(...)` is missing a closing `)`. 
  -  The notation `{ }` should be `[]`.

**Comment by hmalewska** [comment]
Thank you! :)

**Comment by marcingrzejszczak** [comment]
Nie ma sprawy ;)
