### ISSUE TITLE
A URL of / causes contract generation to fail

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-contract#465]
If you have a contract with a `url` of `/` contract generation fails when running `./mvnw clean install`

Here is a sample contract
```
Contract.make {
    description("""
Represents a request to the shouldReturnName service

given:
	a request to the shouldReturnName service
when:
	it is a GET
then:
	return Ryan
""")
    request {
        method 'GET'
        url '/'
    }
    response {
        status 200
        body("Ryan")
        headers {
            contentType(textHtml())
        }
    }
}
```
Here is the stacktrace
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at org.springframework.cloud.contract.verifier.builder.TestSideRequestTemplateModel.buildPathsFromUrl(TestSideRequestTemplateModel.groovy:76)
	at org.springframework.cloud.contract.verifier.builder.TestSideRequestTemplateModel.from(TestSideRequestTemplateModel.groovy:55)
	at org.springframework.cloud.contract.verifier.template.HandlebarsTemplateProcessor.transform(HandlebarsTemplateProcessor.groovy:30)
```

**Comment by spencergibb** [comment]
Did you mean for `url '/foo'` to be `url /`?

**Comment by ryanjbaxter** [comment]
Yeah u are right, fixed it
