### ISSUE TITLE
NullPointerException when trying to create producer tests from Pact

### ISSUE THREAD

**Issue by thombergs** [spring-cloud/spring-cloud-contract#509]
I'm trying to auto-create producer tests from a Pact contract using `spring-cloud-contract-spec-pact` and the verifier in version 1.2.2.BUILD-SNAPSHOT (but I reproduced the error in 1.2.1 as well).

Each time the gradle task `generateContractTests` fails with the following stacktrace:

```
...
Caused by: java.lang.NullPointerException: Cannot get property 'name' on null object
        at org.springframework.cloud.contract.verifier.builder.MethodBodyBuilder.checkType(MethodBodyBuilder.groovy:464)
        at org.springframework.cloud.contract.verifier.builder.MethodBodyBuilder.methodForTypeCheck(MethodBodyBuilder.groovy:422)
        at org.springframework.cloud.contract.verifier.builder.MethodBodyBuilder$_addJsonResponseBodyCheck_closure3.doCall(MethodBodyBuilder.groovy:365)
        at org.springframework.cloud.contract.verifier.builder.MethodBodyBuilder.addJsonResponseBodyCheck(MethodBodyBuilder.groovy:359)
        at org.springframework.cloud.contract.verifier.builder.MethodBodyBuilder.validateResponseBodyBlock(MethodBodyBuilder.groovy:320)
...
```

Here's the pact contract I was using:

```json
{
  "consumer": {
    "name": "ui"
  },
  "provider": {
    "name": "userservice"
  },
  "interactions": [
    {
      "description": "a request to POST a person",
      "providerState": "provider accepts a new person",
      "request": {
        "method": "POST",
        "path": "/user-service/users",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "firstName": "Arthur",
          "lastName": "Dent"
        }
      },
      "response": {
        "status": 201,
        "headers": {
          "Content-Type": "application/json;charset=UTF-8"
        },
        "body": {
          "id": 42
        },
        "matchingRules": {
          "$.body": {
            "match": "type"
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
```

**Further analysis:**
I traced the error back to `MethodBodyBuilder.classToCheck()` where the statement

```java
switch (elementFromBody.class) {
```

should probably be replaced with 
```java
switch (elementFromBody.getClass()) {
```

If `elementFromBody` is a `Map` (as in my case), `elementFromBody.class` in Groovy apparently resolves to the element with the key `class` within the map (which is null) instead of the class of the Map itself.

If the statement above is replaced, the test is generated successfully and evens runs successfully.

**Comment by marcingrzejszczak** [comment]
@thombergs thanks for the analysis. Care for a test and a PR? :)

**Comment by thombergs** [comment]
I'm at it :). Have to dig into Groovy...

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/bea0d4f78d44150f7348623b21b4afae51ab50b5 and https://github.com/spring-cloud/spring-cloud-contract/issues/513
