### ISSUE TITLE
Context initialization failed in tests when AutoConfigureStubRunner is used on configuration class

### ISSUE THREAD

**Issue by belon** [spring-cloud/spring-cloud-contract#550]
Spring Boot version: 1.5.10
Stubrunner version: 1.2.3

**Goal:**
Run application with `local` profile which will use stubs instead of consul auto discovery.

**Solution:**
I created config class `StubConfiguration` which will be loaded only for `local` profile:
```
@Profile("local")
@Configuration
@EnableStubRunnerServer
@AutoConfigureStubRunner
class StubConfiguration
```
In `bootstrap.yaml` added for profile `local`:
```
stubrunner:
  ids: com.example:server-api
  idsToServiceIds:
    server-api: server-api-local
  repository-root: 'http://nexus-url.com/content/repositories/public'
  username: 'username'
  password: 'password'
```
Application with profile `local` started up and I am able to do the request which will call `server-api` stub using feign client.

**Problem:**
When I try to run simple integration test:
```
@RunWith(SpringRunner::class)
@ActiveProfiles("local")
@SpringBootTest
class ApplicationTest {
	@Test
	fun contextLoads() {
	}
}
```
it failed with exception:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stubConfiguration' defined in file [/Users/jbela/api/StubConfiguration.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: The @PropertyMapping annotation @AutoConfigureStubRunner cannot be used in combination with the @Component annotation @Configuration
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 24 more
Caused by: java.lang.IllegalStateException: The @PropertyMapping annotation @AutoConfigureStubRunner cannot be used in combination with the @Component annotation @Configuration
	at org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer$PropertyMappingCheckBeanPostProcessor.postProcessBeforeInitialization(PropertyMappingContextCustomizer.java:99)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	... 38 more
```

Exception is clear but why this doesn't work only in test? and how to achieve the goal and fix tests?

**Comment by marcingrzejszczak** [comment]
I don't understand your problem. Just don't put it on a `@Configuration` class.

BTW why do you use `@EnableStubRunnerServer` ? Do you want to start a standalone process of stub runner inside your tests where you already have a stub runner running via `@AutoConfigureStubRunner` ? 

Here you have an example of how I did things in order to run a standalone stub runner boot application that will automatically start stubs - https://github.com/spring-cloud-samples/github-analytics-stub-runner-boot/blob/master/src/main/java/org/springframework/github/GithubAnalyticsStubRunnerBootApplication.java
