### ISSUE TITLE
Support for form param by ignoring order

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-contract#578]
Question

I would like to match the request with form parameters

i.e 

```groovy
  make {
    request {
      method POST()
      urlPath('/oauth/token')
      headers {
        header(authorization(), anyNonBlankString())
        header(contentType(), applicationFormUrlencoded())
        header(accept(), applicationJson())
      }
      body([
          username  : 'user',
          password  : 'password',
          grant_type: 'password'
      ])
    }
    response {
      status 200
      headers {
        header(contentType(), applicationJson())
      }
      body([
          refresh_token: 'RANDOM_REFRESH_TOKEN',
          access_token : 'RANDOM_ACCESS_TOKEN',
          token_type   : 'bearer',
          expires_in   : 3600,
          scope        : ['task'],
          user         : [
              id      : 1,
              username: 'user',
              name    : 'User'
          ]
      ])
    }
```

I want to send 200 response only if the request body contains `username` = `user`, `password` = `password` & `grant_type` = `password`. The order of the arguments need not be guaranteed to be exact, i.e this should be similar to how json matching currently works.

Also, I would like to send a 401 response if any of the arguments does not match the request.

Is there a way to achieve this currently?

**Comment by marcingrzejszczak** [comment]
That's exactly what would happen right now. Have you actually tried to run this?

**Comment by marcingrzejszczak** [comment]
That's a bug. Which version of contract are you using?

**Comment by thekalinga** [comment]
Here is request
```
POST /oauth/token HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic aHR0cGllOg==
Connection: keep-alive
Content-Length: 51
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: localhost:9191
User-Agent: HTTPie/0.9.9

username=user&password=password&grant_type=password
```

> That's a bug. Which version of contract are you using?

http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-contract-stub-runner-boot/2.0.0.M6/spring-cloud-contract-stub-runner-boot-2.0.0.M6.jar

**Comment by thekalinga** [comment]
Plus there are multiple additional issues.

I try to run `./gradlew generateClientStubs` 200 & 401  compile the following contract, it fails to compile

1. When I try to generate client stubs via `./gradlew generateClientStubs`  for 200 & 401 scenarios, build fails

Testcase
```groovy
import static org.springframework.cloud.contract.spec.Contract.make

[
    make {
      request {
        method POST()
        urlPath('/')
        body([
            param1: 'val1'
        ])
      }
      response {
        status 200
      }
    },
    make {
      request {
        method POST()
        urlPath('/')
        body(notMatching([
            param1: 'val1'
        ]))
      }
      response {
        status 401
      }
    }
]
```

2. `anyOf(applicationJson(), applicationJsonUtf8(), allValue())` does not work

Testcase
```groovy
import static org.springframework.cloud.contract.spec.Contract.make

make {
  request {
    method GET()
    urlPath('/')
    headers {
      header(accept(), anyOf(applicationJson(), applicationJsonUtf8(), allValue()))
    }
  }
  response {
    status 200
  }
}
```

try to make a call with the following request

```
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:9191
User-Agent: HTTPie/0.9.9



HTTP/1.1 404 Not Found
Content-Type: text/plain
Server: Jetty(9.2.z-SNAPSHOT)
Transfer-Encoding: chunked

                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
GET                                                        | GET
/                                                          | /
                                                           |
Accept [matches] :                                         | Accept: */*                                         <<<<< Header does not match
^application/json$|^application/json;charset=UTF-8$|^*/*$  |
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

**Comment by marcingrzejszczak** [comment]
Can you show what exactly doesn't compile?

**Comment by thekalinga** [comment]
The first one does not compile, the second one does not match requests

**Comment by marcingrzejszczak** [comment]
I understood *which one*, I asked *what exactly* doesn't compile. Can you paste the compilation issue error?

**Comment by thekalinga** [comment]
Sorry. Here is the log

```
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
:auth-server:copyContracts
:auth-server:generateClientStubs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':auth-server:generateClientStubs'.
> Unable to make conversion of test.groovy

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':auth-server:generateClientStubs'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.springframework.cloud.contract.verifier.converter.ConversionContractVerifierException: Unable to make conversion of test.groovy
	at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1$_closure2.doCall(RecursiveFilesConverter.groovy:107)
	at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1.doCall(RecursiveFilesConverter.groovy:67)
	at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1.call(RecursiveFilesConverter.groovy)
	at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter.processFiles(RecursiveFilesConverter.groovy:66)
	at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$processFiles.call(Unknown Source)
	at org.springframework.cloud.contract.verifier.plugin.GenerateWireMockClientStubsFromDslTask.generate(GenerateWireMockClientStubsFromDslTask.groovy:58)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 30 more
Caused by: java.util.regex.PatternSyntaxException: Illegal repetition
{"param1":"val1"}
	at com.github.tomakehurst.wiremock.matching.AbstractRegexPattern.<init>(AbstractRegexPattern.java:28)
	at com.github.tomakehurst.wiremock.matching.NegativeRegexPattern.<init>(NegativeRegexPattern.java:23)
	at com.github.tomakehurst.wiremock.client.WireMock.notMatching(WireMock.java:222)
	at com.github.tomakehurst.wiremock.client.WireMock$notMatching$2.call(Unknown Source)
	at org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockRequestStubStrategy.convertToValuePattern(WireMockRequestStubStrategy.groovy:213)
	at org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockRequestStubStrategy.appendBody(WireMockRequestStubStrategy.groovy:118)
	at org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockRequestStubStrategy.buildClientRequestContent(WireMockRequestStubStrategy.groovy:76)
	at org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockStubStrategy.toWireMockClientStub(WireMockStubStrategy.groovy:61)
	at org.springframework.cloud.contract.verifier.wiremock.DslToWireMockClientConverter.convertASingleContract(DslToWireMockClientConverter.groovy:36)
	at org.springframework.cloud.contract.verifier.wiremock.DslToWireMockClientConverter.access$0(DslToWireMockClientConverter.groovy)
	at org.springframework.cloud.contract.verifier.wiremock.DslToWireMockClientConverter$_convertContents_closure3.doCall(DslToWireMockClientConverter.groovy:50)
	at org.springframework.cloud.contract.verifier.wiremock.DslToWireMockClientConverter.convertContents(DslToWireMockClientConverter.groovy:48)
	at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1$_closure2$_closure3.doCall(RecursiveFilesConverter.groovy:91)
	at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter$_processFiles_closure1$_closure2.doCall(RecursiveFilesConverter.groovy:90)
	... 48 more


* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 2 executed
```

**Comment by marcingrzejszczak** [comment]
The form parameter is the new feature I've added. 

> anyOf(applicationJson(), applicationJsonUtf8(), allValue()) does not work

It doesn't work cause `anyOf(...)` accepts regular expressions. `applicationJson(), applicationJsonUtf8(), allValue()` are not regular expressions.

>  body(notMatching([param1: 'val1']))

`notMatching` accepts a regular expression. `[param1: 'val1']` is not a regular expression

**Comment by thekalinga** [comment]
> It doesn't work cause anyOf(...) accepts regular expressions. applicationJson(), applicationJsonUtf8(), allValue() are not regular expressions.

Can you rename the method appropriately so that people know this only works with regex

> body(notMatching([param1: 'val1']))

Since this too is the common scenario, do u plan on supporting `notMatching` overload that accepts Map?

**Comment by marcingrzejszczak** [comment]
> Can you rename the method appropriately so that people know this only works with regex

No, the method exactly says what it does

> Since this too is the common scenario, do u plan on supporting notMatching overload that accepts Map?

No. AFAIR WireMock doesn't support it

**Comment by thekalinga** [comment]
> No. AFAIR WireMock doesn't support it

Raised a question in their forum
https://groups.google.com/forum/#!topic/wiremock-user/tmPYeTDzPU0

Thanks
