### ISSUE TITLE
Illegal URI When Trying To Download Stubs From Maven Repo

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-contract#639]
I am moving an app to Finchley RC1 and when I run the contracts I am getting the following error

```
Caused by: java.lang.IllegalArgumentException: Illegal uri [https://oss.sonatype.org/content/repositories/snapshots/]
	at org.springframework.cloud.contract.stubrunner.ClasspathStubProvider$1.relativePathPicker(ClasspathStubProvider.java:139)
	at org.springframework.cloud.contract.stubrunner.ClasspathStubProvider$1.downloadAndUnpackStubJar(ClasspathStubProvider.java:89)
	at org.springframework.cloud.contract.stubrunner.CompositeStubDownloader.downloadAndUnpackStubJar(CompositeStubDownloaderBuilder.java:77)
	at org.springframework.cloud.contract.stubrunner.StubRunnerFactory.createStubsFromServiceConfiguration(StubRunnerFactory.java:60)
	at org.springframework.cloud.contract.stubrunner.BatchStubRunnerFactory.buildBatchStubRunner(BatchStubRunnerFactory.java:59)
	at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration.batchStubRunner(StubRunnerConfiguration.java:78)
	at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration$$EnhancerBySpringCGLIB$$ad2f449b.CGLIB$batchStubRunner$0(<generated>)
	at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration$$EnhancerBySpringCGLIB$$ad2f449b$$FastClassBySpringCGLIB$$14d4050e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration$$EnhancerBySpringCGLIB$$ad2f449b.batchStubRunner(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 74 more
```

Here is my configuration

```
stubrunner:
  idsToServiceIds:
    ocr-participants: participants
  ids: 'com.ryanjbaxter.spring.cloud:ocr-participants:+:stubs'
  repositoryRoot: https://oss.sonatype.org/content/repositories/snapshots/
```

Stubs are located here https://oss.sonatype.org/content/repositories/snapshots/com/ryanjbaxter/spring/cloud/ocr-participants/

It seems weird to me that `ClasspathStubProvider` is running since the stubs are not on the classpath but in a Maven repo.

**Comment by marcingrzejszczak** [comment]
You haven't provided the stubsMode which by default points to class path. You should set stubsMode to REMOTE

**Comment by ryanjbaxter** [comment]
OK I knew it was something stupid I was doing....thanks.

One doc problem, this should be `stubs-mode` not ``stubsMode`
http://cloud.spring.io/spring-cloud-static/Finchley.RC1/single/spring-cloud.html#_spring_cloud_cli

Another question related to this....
So when I specify `REMOTE` and the stubs happen to be installed locally as well the tests fail
`Caused by: java.lang.IllegalStateException: The artifact was found in the local repository but you have explicitly stated that it should be downloaded from a remote one`
Why not just ignore the ones locally and download them?  Why throw the exception?

**Comment by marcingrzejszczak** [comment]
As discussed offline, here (https://cloud.spring.io/spring-cloud-contract/single/spring-cloud-contract.html#_ci_server_setup) we explain how to workaround this issue and the reasons for that issue.

After doing another digging into the problem, obvioulsy we're not the only ones with this issue (http://maven.40175.n5.nabble.com/Resolving-an-Artifact-from-Remote-Repository-instead-of-Local-td5875134.html). A potential workaround is to, when someone sets `stubsMode: REMOTE`, to provide a fake maven local repo location - https://stackoverflow.com/questions/9123004/maven-is-it-possible-to-override-location-of-local-repository-via-the-use-of-co . I'll create a separate issue for that.
