### ISSUE TITLE
Dependency conflict: Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.contract.verifier.config.TestMode

### ISSUE THREAD

**Issue by yuranos** [spring-cloud/spring-cloud-contract#646]
My POM snippet:
```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-dependencies</artifactId>
				<version>2.0.0.BUILD-SNAPSHOT</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
            <plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <version>2.0.0.BUILD-SNAPSHOT</version>
                <!-- Don't forget about this value !! -->
                <extensions>true</extensions>
                <configuration>
                    <baseClassForTests>com.yuranos.documented.api.controllers.BookingControllerImplTest</baseClassForTests>
                </configuration>
```

The error:

> .....	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)

> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.contract.verifier.config.TestMode
> 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
> 	... 58 more
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 4.214 s
> [INFO] Finished at: 2018-05-08T08:30:07+03:00
> [INFO] Final Memory: 43M/842M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.0.0.BUILD-SNAPSHOT:generateTests (default-generateTests) on project raml-based-producer-application: Execution default-generateTests of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.0.0.BUILD-SNAPSHOT:generateTests failed: A required class was missing while executing org.springframework.cloud:spring-cloud-contract-maven-plugin:2.0.0.BUILD-SNAPSHOT:generateTests: Lorg/springframework/cloud/contract/verifier/config/TestMode;

**Comment by yuranos** [comment]
I can also locally reproduce it on spring-cloud-contract-samples/producer_pact

**Comment by yuranos** [comment]
Sorry, @marcingrzejszczak , my .m2 got corrupted. All good now.
