### ISSUE TITLE
@AutoConfigureWireMock doesn't stop Jetty server properly.

### ISSUE THREAD

**Issue by petromir** [spring-cloud/spring-cloud-contract#665]
Using `@AutoConfigureWireMock` in more than one test class with same `wiremock.server.port` causes the following exception:

```java
java.lang.IllegalStateException: Failed to load ApplicationContext
.....
Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.cloud.contract.wiremock.WireMockConfiguration'; nested exception is com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: Address already in use
.....
Caused by: com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: Address already in use
    at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:146)
    at org.springframework.cloud.contract.wiremock.WireMockConfiguration.start(WireMockConfiguration.java:142)
    at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175)
    ... 46 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
    at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:137)
    at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:144)
Caused by: java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at wiremock.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
    at wiremock.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
    at wiremock.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
    at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at wiremock.org.eclipse.jetty.server.Server.doStart(Server.java:366)
    at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:135)
```

Obviously when a second test is started it tries to run a server in the same port, but for some reason the first one hasn't stopped the previous properly.

All tests in https://github.com/spring-cloud-samples/spring-cloud-contract-samples/ which use `@AutoConfigureWireMock`, have Spring's `@DirtiestContext` declared. Unfortunately I couldn't find explicit requirement for this annotation at https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/1.2.4.RELEASE/single/spring-cloud-contract.html#_spring_cloud_contract_wiremock

**Comment by marcingrzejszczak** [comment]
That's a known issue (that's why `@DirtiesContext` is there). If you search for `@DirtiesContext` in the docs you'll get https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/1.2.4.RELEASE/single/spring-cloud-contract.html#_limitations

AFAIR @dsyer was looking into it once and there was no easy way to fix it. I guess we should document it better / investigate it again.

**Comment by petromir** [comment]
@marcingrzejszczak any chance to have it in 1.2.6?

**Comment by marcingrzejszczak** [comment]
As a workaround you can copy the classes and register them manually

**Comment by petromir** [comment]
@marcingrzejszczak Let me try it on Monday. Thanks!

**Comment by marcingrzejszczak** [comment]
I'm insane... It has already been backported - https://github.com/spring-cloud/spring-cloud-contract/commit/c9228969de898b0c4373877dcd56b73134b1f77b

**Comment by petromir** [comment]
Oh sorry, I somehow missed it in branch history. So now we are waiting for 1.2.6 😃

**Comment by KOTLAPRA23** [comment]
Hi Could you please help me here .


I am running wiremock junit test case and getting below exception every time
2020-04-10 20:51:34.541  INFO 84435 --- [    Test worker] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path ''
2020-04-10 20:51:34.822  INFO 84435 --- [    Test worker] org.eclipse.jetty.server.Server          : jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: **7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_221-b11
2020-04-10 20:51:34.853  INFO 84435 --- [    Test worker] o.e.jetty.server.handler.ContextHandler  : Started o.e.j.s.ServletContextHandler@a51c931{/__admin,null,AVAILABLE}
2020-04-10 20:51:34.856  INFO 84435 --- [    Test worker] o.e.jetty.server.handler.ContextHandler  : Started o.e.j.s.ServletContextHandler@3d622400{/,null,AVAILABLE}
2020-04-10 20:51:34.869  INFO 84435 --- [    Test worker] o.e.jetty.server.AbstractConnector       : Started NetworkTrafficServerConnector@709ceff2{HTTP/1.1,[http/1.1]}{0.0.0.0:5000}
2020-04-10 20:51:34.869  INFO 84435 --- [    Test worker] org.eclipse.jetty.server.Server          : Started @80828ms**

2020-04-10 20:53:40.153  INFO 84435 --- [tp780160597-117] o.e.j.s.handler.ContextHandler.ROOT      : RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2020-04-10 20:53:40.301 ERROR 84435 --- [qtp780160597-92] WireMock                                 : Request was not matched as there were no stubs registered:
{
  "url" : "/o/.well-known/openid-configuration",
  "absoluteUrl" : "http://0.0.0.0:5000/o/.well-known/openid-configuration",
  "method" : "GET",
  "clientIp" : "127.0.0.1",
  "headers" : {
    "Cache-Control" : "max-age=0",
    "Accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
    "Upgrade-Insecure-Requests" : "1",
    "Connection" : "keep-alive",
    "User-Agent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
    "Host" : "0.0.0.0:5000",
    "Accept-Encoding" : "gzip, deflate",
    "Accept-Language" : "en-GB,en-US;q=0.9,en;q=0.8"
  },
  "cookies" : { },
  "browserProxyRequest" : false,
  "loggedDate" : 1586548420194,
  "bodyAsBase64" : "",
  "body" : "",
  "scheme" : "http",
  "host" : "0.0.0.0",
  "port" : 5000,
  "loggedDateString" : "2020-04-10T19:53:40Z",
  "queryParams" : { }
}


Caused by: java.io.IOException: Failed to bind to /0.0.0.0:5000
at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.server.Server.doStart(Server.java:385)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:174)
... 67 common frames omitted
Caused by: java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.Net.bind(Net.java:425)
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
... 74 common frames omitted

**Code sample:**

@RunWith(SpringRunner.class)
@SpringBootTest(classes = Application.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DirtiesContext
public abstract class SpringBootIntegrationTest {

    @LocalServerPort
    protected int port;

}


@configuration
@AutoConfigureWireMock(port = 5000)
public abstract class AuthorizationEnabledIntegrationTest extends SpringBootIntegrationTest {

@ClassRule
public static WireMockRule someService = new WireMockRule(options().port(5000).withRootDirectory("src/integrationTest/resources/mappings"));
}

inside mappings folder :
{
  "priority": 1,
  "mappings": [
    {
      "request": {
        "method": "GET",
        "url": "/o/.well-known/openid-configuration"
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "jsonBody": {
          "issuer": "http://0.0.0.0:5000/o",
          "jwks_uri": "http://0.0.0.0:5000/jwks"
        }
      }
    }
  ]
}

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

Also are you sure you're using the latest version?

**Comment by Oluwatobiadeoye** [comment]
Currently experiencing this issue in spring-cloud-contract-wiremock 2.2.5-REALEASE. I have a  project containing couple spring boot at work (unfortunately unable to shared the source code) and when the tests in the modules are run in parallel, this issue appears. 
Is this still an issue that we have to use `@DirtiesContext` as a work around?

**Comment by marcingrzejszczak** [comment]
If you're using random ports then it shouldn't be an issue. If there's one then it's a bug.
