### ISSUE TITLE
Maven plugin is ignoring JGitConfig for pushing stubs

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#678]
This is a test constructor and should be called only in tests `org.springframework.cloud.contract.stubrunner.GitRepo#GitRepo(java.io.File)`. However I'm using it here `ContractProjectUpdater.java:67`. That means that I'm not setting up proper credentials for pushing. I only do that for pull

**Comment by hantsy** [comment]
When switch to **git** protocol instead of https, and got failure.

```
Download dependency is provided - will retrieve contracts from a remote location
[INFO] Cloning repo from [git:git@github.com:hantsy/contracts-git.git] to [E:\Users\hantsy\AppData\Local\Temp\git-contracts1562586833804707535]
[INFO] Successfully connected to an agent
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.641 s
[INFO] Finished at: 2018-07-03T15:11:47+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.0.0.RELEASE:convert (default-convert) on project contract-producer-rest-git: Execution default-convert of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.0.0.RELEASE:convert failed: Exception occurred while cloning repo: org.eclipse.jgit.api.errors.TransportException: git@github.com:hantsy/contracts-git.git: Auth fail -> [Help 1]

```

**Comment by marcingrzejszczak** [comment]
I didn't. 
```
[INFO] --- spring-cloud-contract-maven-plugin:2.0.1.BUILD-SNAPSHOT:pushStubsToScm (default) @ contract-producer-rest-git ---
[INFO] Pushing Stubs to SCM for project [com.example:contract-producer-rest-git:0.0.1-SNAPSHOT]
[INFO] Commited successfully with message [Updating project [com.example:contract-producer-rest-git:0.0.1-SNAPSHOT] with stubs]
[INFO] Trying to push changes, attempt 1/10
[INFO] Successfully connected to an agent
[INFO] Successfully pulled changes from remote for project with contract and stubs
[INFO] Successfully pushed changes with current stubs
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.798 s
[INFO] Finished at: 2018-07-03T09:18:55+02:00
[INFO] ------------------------------------------------------------------------
```

Maybe it's sth related to windows?

**Comment by marcingrzejszczak** [comment]
I think you have a problem with certificates for some reason. Can you try with `2.0.1.BUILD-SNAPSHOT` and pass the credentials?

**Comment by hantsy** [comment]
If possible configure this repository  credentials info  as  maven **server** format in setttings.xml to make it more secret.

And if possible delegate the push command to my local git?

**Comment by marcingrzejszczak** [comment]
but what does Maven's `settings.xml` have to do with git? What you're suggesting is a hack imo

**Comment by hantsy** [comment]
@marcingrzejszczak updated to `2.0.1.BUILD-SNAPSHOT`,  **git** protocol failed, https ok.

**Comment by hantsy** [comment]
> but what does Maven's settings.xml have to do with git? What you're suggesting is a hack imo

I means set username and password in **servers** section of setttings.xml, and this maven plugin refer the id of the server definition, thus it will not expose credentials to public.

**Comment by marcingrzejszczak** [comment]
I see - I guess you can set that requirement as a separate issue. 

As for the Auth fail maybe try this:
https://cloud.spring.io/spring-cloud-release-tools/single/spring-cloud-release-tools.html#_jschexception_auth_fail

> 1.8.1 JSchException: Auth fail
I got such an exception

```
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:spring-cloud/spring-cloud-sleuth.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:160) ~[org.eclipse.jgit-4.6.0.201612231935-r.jar!/:4.6.0.201612231935-r]
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:137) ~[org.eclipse.jgit-4.6.0.201612231935-r.jar!/:4.6.0.201612231935-r]
	at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:322) ~[org.eclipse.jgit-4.6.0.201612231935-r.jar!/:4.6.0.201612231935-r]
	at org.eclipse.jgit.transport.TransportGitSsh.openPush(TransportGitSsh.java:167) ~[org.eclipse.jgit-4.6.0.201612231935-r.jar!/:4.6.0.201612231935-r]
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:160) ~[org.eclipse.jgit-4.6.0.201612231935-r.jar!/:4.6.0.201612231935-r]
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1275) ~[org.eclipse.jgit-4.6.0.201612231935-r.jar!/:4.6.0.201612231935-r]
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:161) ~[org.eclipse.jgit-4.6.0.201612231935-r.jar!/:4.6.0.201612231935-r]
	... 25 common frames omitted
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512) ~[jsch-0.1.53.jar!/:na]
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:117) ~[org.eclipse.jgit-4.6.0.201612231935-r.jar!/:4.6.0.201612231935-r]
	... 31 common frames omitted
```

To fix that just call

```
# to run the agent
$ eval `ssh-agent`
# to store the pass in the agent
$ ssh-add ~/.ssh/id_rsa
```
before running the app

**Comment by hantsy** [comment]
@marcingrzejszczak I will create another issue for it.

**Comment by hantsy** [comment]
@marcingrzejszczak  Unluckily tried this approach in Git bash/Windows 10, got the same failure.

**Comment by marcingrzejszczak** [comment]
I don't have a windows machine to verify this. Maybe you have sth improperly set up with the keys.

**Comment by hantsy** [comment]
@marcingrzejszczak I will try to generate a new key and try it later. Thanks.

**Comment by hantsy** [comment]
@marcingrzejszczak I have tried generating a new rsa key, and added it by ssh-agent and in Github settings, **Git** protocol did not work under my Windows. For me, it is luckily Https works
