### ISSUE TITLE
Consumer side tests failed when set custom destination. 

### ISSUE THREAD

**Issue by hantsy** [spring-cloud/spring-cloud-contract#679]
I have tried to test **Spring cloud stream** based service in my projects.

ENV: Spring Boot 2.0.3, Spring Cloud Contract 2.0.0

I have set custom output destination  `spring.cloud.stream.bindings.output.destination=notification` in application.properties of the producer side project.

The contract definition is like the following:

```groovy
org.springframework.cloud.contract.spec.Contract.make {
    description("""
        send messages by rabbitmq
    """)
    label "notification.event"
    // input to the contract
    input {
        // the contract will be triggered by a method
        triggeredBy('send()')
    }
    outputMessage {
        sentTo "notification"
        body([
            body: "test message",
            type: "MESSAGE"
        ])
        headers {
           header('contentType', applicationJson())
        }
    }
}
```
The generated tests worked well. 

But when I set custom destination in my consumer side as `spring.cloud.stream.bindings.input.destination=notification`, it will cause my consumer test failed.

```java

@RunWith(SpringRunner.class)
@SpringBootTest(properties = "debug=true")
@AutoConfigureStubRunner(
    ids = "com.example:contract-producer-stream:+:stubs:8090",
    stubsMode = StubRunnerProperties.StubsMode.LOCAL
)
@Slf4j
public class NotificationConsumerTest {

    @Autowired
    StubFinder stubFinder;

    @Autowired
    MessageVerifier<Message<?>> messageVerifier;


    @Test
    public void testOnMessageReceived() {
        stubFinder.trigger("notification.event");
        Message<?> message = messageVerifier.receive("notification");
        log.debug("payload::" + message);
        assertNotNull(message.getPayload());
        //assertEquals("test message", this.receiver.getMessage());
    }

}
```
The exception thrown when ran the tests.

```
java.lang.IllegalStateException: java.lang.IllegalArgumentException: Channel [input] was not bound by class org.springframework.cloud.stream.test.binder.TestSupportBinder

	at org.springframework.cloud.contract.verifier.messaging.stream.StreamStubMessages.receive(StreamStubMessages.java:77)
	at org.springframework.cloud.contract.verifier.messaging.stream.StreamStubMessages.receive(StreamStubMessages.java:108)
	at org.springframework.cloud.contract.verifier.messaging.stream.StreamStubMessages.receive(StreamStubMessages.java:35)
	at com.example.demo.NotificationConsumerTest.testOnMessageReceived(NotificationConsumerTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: Channel [input] was not bound by class org.springframework.cloud.stream.test.binder.TestSupportBinder
	at org.springframework.util.Assert.notNull(Assert.java:193)
	at org.springframework.cloud.stream.test.binder.TestSupportBinder$MessageCollectorImpl.forChannel(TestSupportBinder.java:134)
	at org.springframework.cloud.contract.verifier.messaging.stream.StreamStubMessages.receive(StreamStubMessages.java:72)
	... 33 more
```

If I remove the custom destination in my consumer side, it worked. But what I need is sending message to a custom destination in my producer side, and subscribe the message in the same destination in my consumer side.

Check  the codes from my github, [producer side](https://github.com/hantsy/spring-cloud-sample/tree/master/contract-producer-stream) and [consumer side](https://github.com/hantsy/spring-cloud-sample/tree/master/contract-consumer-stream).

**Comment by marcingrzejszczak** [comment]
Apply this patch and it will work

```
Index: contract-consumer-stream/src/test/java/com/example/demo/NotificationConsumerTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- contract-consumer-stream/src/test/java/com/example/demo/NotificationConsumerTest.java	(revision dfd8b26183fc7fddd7be38680f095a3850a8d8b6)
+++ contract-consumer-stream/src/test/java/com/example/demo/NotificationConsumerTest.java	(date 1530604157000)
@@ -9,14 +9,13 @@
 import org.springframework.cloud.contract.stubrunner.StubFinder;
 import org.springframework.cloud.contract.stubrunner.spring.AutoConfigureStubRunner;
 import org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties;
-import org.springframework.cloud.contract.verifier.messaging.MessageVerifier;
 import org.springframework.test.context.junit4.SpringRunner;
-import org.springframework.messaging.Message;
 
 import static org.junit.Assert.assertNotNull;
 
 @RunWith(SpringRunner.class)
-@SpringBootTest(properties = "debug=true")
+@SpringBootTest(classes = ContractConsumerStreamApplication.class,
+		properties = "debug=true")
 @AutoConfigureStubRunner(
     ids = "com.example:contract-producer-stream:+:stubs:8090",
     stubsMode = StubRunnerProperties.StubsMode.LOCAL
@@ -27,17 +26,14 @@
     @Autowired
     StubFinder stubFinder;
 
-    @Autowired
-    MessageVerifier<Message<?>> messageVerifier;
-
+    @Autowired NotificationListener listener;
 
     @Test
     public void testOnMessageReceived() {
         stubFinder.trigger("notification.event");
-        Message<?> message = messageVerifier.receive("notification");
+		String message = listener.getMessage();
         log.debug("payload::" + message);
-        assertNotNull(message.getPayload());
+        assertNotNull(message);
         //assertEquals("test message", this.receiver.getMessage());
     }
-
 }

```

You're using a wrong component to fetch the message and you're missing importing a class that has `@EnableBinding` on it for tests

**Comment by hantsy** [comment]
>You're using a wrong component to fetch the message and you're missing importing a class that has @EnableBinding on it for tests

Oh, is this required??? but Spring Boot loads the Application class by default.

**Comment by hantsy** [comment]
Worked, thanks. @marcingrzejszczak

**Comment by suvra25** [comment]
@marcingrzejszczak @hantsy 
I think the solution worked because Message<?> message = messageVerifier.receive("notification"); part has been removed, because with same code adding ContractConsumerStreamApplication it still fails. Please confirm if code works with verifier.receive part as well.

I am facing similar issue with my test class as well.
