### ISSUE TITLE
Bug: test configuration makes message contract test fail

### ISSUE THREAD

**Issue by arnaud-deprez** [spring-cloud/spring-cloud-contract#685]
**Given** some contract message tests such as https://github.com/arnaud-deprez/spring-cloud-contract-samples/blob/master/consumer/src/test/java/com/example/BeerVerificationListenerTest.java

**When** adding a test configuration (empty or not) such as here https://github.com/arnaud-deprez/spring-cloud-contract-samples/commit/ec7570f2b6f2f80f5639cd93f853b1dc73f8ed2c

**Then** the tests fail with
```
java.lang.AssertionError: 
Expecting:
 <0>
to be greater than:
 <0> 

	at com.example.BeerVerificationListenerTest.should_increase_the_noteligible_counter_when_verification_was_rejected(BeerVerificationListenerTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

The message does not seem to be read anymore.

It is often that we need to override configuration during test, so this bug has a high priority IMO.

I didn't find how to fix it so far, so any help is appreciated.

**Comment by marcingrzejszczak** [comment]
This is super bizarre... Can you compare the autoconfiguration reports and see what the difference is? Is it actually related to contract or stream? Are you using the latest versions of contract?

**Comment by arnaud-deprez** [comment]
Yep I know, super bizarre...

I reported the change in `spring-cloud-contract-samples` from the branch `2.0.x` and it's against `spring-cloud-contract 2.0.0.RELEASE`

**Comment by marcingrzejszczak** [comment]
Branch 2.0.x is actually `master`. I have to remove the `2.0.x` branch

**Comment by arnaud-deprez** [comment]
Ok, I can port this change to master if you prefer, the problem still occurs

**Comment by marcingrzejszczak** [comment]
I know what the problem is. It's not related to Contract it's related to Boot. You're having 2 `application.yml`s . One in `src/main/resources` and the other in `src/test/resources`. It's enough for you to set up `src/test/resources/application-test.yml` (which is a good practice) and add `@ActiveProfiles("test")` on your test and things will work fine.

**Comment by arnaud-deprez** [comment]
Thanks @marcingrzejszczak, I didn't know this. 
Especially because this kind of settings were working fine in spring-boot 1.5.x.
