### ISSUE TITLE
GitStubDownloader does not accept https protocol

### ISSUE THREAD

**Issue by kwikmick** [spring-cloud/spring-cloud-contract#695]
When testing the Git Stub Downloader on a public git repository with an https connection we get an exception.

```java
@AutoConfigureStubRunner(
        stubsMode = StubRunnerProperties.StubsMode.REMOTE,
        repositoryRoot = "git://https://user@bitbucket.hopp.ns.nl:8443/scm/~user/donna-cloud-contract.git",
        ids = "com.example:donna-cloud-producer:1.0.0"
)
```

logs:

```
13:56:32.172 [DEBUG] [TestEventLogger]                                 Caused by:
13:56:32.172 [DEBUG] [TestEventLogger]                                 org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access git://https://user@bitbucket.hopp.ns.nl:8443/scm/~user/donna-cloud-contract.git with type default using the available connector factories: BasicRepositoryConnectorFactory
13:56:32.172 [DEBUG] [TestEventLogger]                                     at shaded.org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:174)
13:56:32.172 [DEBUG] [TestEventLogger]                                     at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
13:56:32.172 [DEBUG] [TestEventLogger]                                     ... 100 more
13:56:32.172 [DEBUG] [TestEventLogger] 
13:56:32.172 [DEBUG] [TestEventLogger]                                         Caused by:
13:56:32.172 [DEBUG] [TestEventLogger]                                         org.eclipse.aether.transfer.NoTransporterException: Cannot access git://https://user@bitbucket.hopp.ns.nl:8443/scm/~user/donna-cloud-contract.git using the registered transporter factories: HttpTransporterFactory, FileTransporterFactory
13:56:32.172 [DEBUG] [TestEventLogger]                                             at shaded.org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:151)
13:56:32.172 [DEBUG] [TestEventLogger]                                             at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:115)
13:56:32.172 [DEBUG] [TestEventLogger]                                             ... 103 more
```

**Comment by marcingrzejszczak** [comment]
Can you provide the full log? I would like to know what Spring Cloud Contract is logging. `HttpTransporterFactory` should take care of `https`.

**Comment by kwikmick** [comment]
[build.log](https://github.com/spring-cloud/spring-cloud-contract/files/2273596/build.log)

**Comment by marcingrzejszczak** [comment]
```
11:30:44.860 [DEBUG] [TestEventLogger]     2018-08-09 11:30:44.860 DEBUG 30432 --- [    Test worker] o.s.c.c.stubrunner.GitRepo$JGitFactory   : No custom credentials provider will be set
11:30:44.861 [DEBUG] [TestEventLogger]     2018-08-09 11:30:44.860  INFO 30432 --- [    Test worker] o.s.cloud.contract.stubrunner.GitRepo    : Cloning repo from [https://bitbucket.hopp.ns.nl:8443/scm/~micky.kwik/donna-cloud-contract.git] to [D:\temp\git-contracts4393946367013114068]
11:30:44.861 [DEBUG] [TestEventLogger]     2018-08-09 11:30:44.862 DEBUG 30432 --- [    Test worker] o.s.cloud.contract.stubrunner.GitRepo    : Project git url [https://bitbucket.hopp.ns.nl:8443/scm/~micky.kwik/donna-cloud-contract.git]
11:30:46.328 [DEBUG] [TestEventLogger]     2018-08-09 11:30:46.328  INFO 30432 --- [    Test worker] o.s.cloud.contract.stubrunner.GitRepo    : Cloned repo to [D:\temp\git-contracts4393946367013114068]
11:30:46.331 [DEBUG] [TestEventLogger]     2018-08-09 11:30:46.331  INFO 30432 --- [    Test worker] o.s.cloud.contract.stubrunner.GitRepo    : Won't check out the same branch. Skipping
11:30:46.331 [DEBUG] [TestEventLogger]     2018-08-09 11:30:46.331 DEBUG 30432 --- [    Test worker] o.s.c.c.stubrunner.GitContractsRepo      : The project hasn't already been cloned. Cloned it to [D:\temp\git-contracts4393946367013114068]
11:30:46.340 [DEBUG] [TestEventLogger]     2018-08-09 11:30:46.340 DEBUG 30432 --- [    Test worker] o.s.c.c.stubrunner.GitStubDownloader     : No matching contracts were found in the repo for [com.example:donna-cloud-producer:1.0.0:stubs]. Returning null
11:30:46.340 [DEBUG] [TestEventLogger]     2018-08-09 11:30:46.340  WARN 30432 --- [    Test worker] o.s.c.c.s.CompositeStubDownloader        : Stub Downloader [org.springframework.cloud.contract.stubrunner.GitStubDownloader] failed to find an entry for [com.example:donna-cloud-producer:1.0.0:stubs]. Will proceed to the next one
```

it managed to clone the repository. I wonder what's there inside `D:\temp\git-contracts4393946367013114068`. You can turn the flag to not to delete the temporary files on exit. Can you then list the files in that repo?

**Comment by kwikmick** [comment]
Contract files still exist in D:\temp\git-contracts4393946367013114068 so cloning was indeed succesful. But strange that StubRunner throws connector exceptions.

**Comment by marcingrzejszczak** [comment]
I know why...

SO the `SCMStubDownloader` failed to retrieve any stubs, so the next one in line is the `AetherStubDownloader`. It tried to use the `git://https://...` URL to fetch the stubs. Since it didn't understand the URL it threw an exception.

**Comment by kwikmick** [comment]
Aha, you're right. The stubs are generated during the build process of the contracts project, so they're not in the source code (only in the jar file). Thanks :-)

**Comment by marcingrzejszczak** [comment]
No problem. So we can close this?

**Comment by kwikmick** [comment]
Yes you can.
