### ISSUE TITLE
Spring cloud contract is not working when locale changes

### ISSUE THREAD

**Issue by pranavskurup** [spring-cloud/spring-cloud-contract#721]
Question
**1**. I am trying to define contract for different languages. When it is English contract works fine, if I change the locale to German contract fails.

Version: 2.0.1.RELEASE
Contract for English:
```
import org.springframework.cloud.contract.spec.Contract
Contract.make {
    description "request should complete with 200 status for english locale"
    request{
        method POST()
        headers {
            contentType(
                    applicationJson()
            )
            header ("accept-language","en")
        }
        url("/api/v1/user/register") {
            body("""
{
  "userName": "janedoeuser",
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@jane.com",
  "dob": 610309800000,
  "termsAccepted": true,
  "password": "3VelQdH9@"
}

""")
        }
    }
    response {
        status 200
        body("""
{
  "userRegistered": true,
  "message": "User registration completed, Please confirm your email address to login."
}
""")

    }
}

```
Above contract is working fine

Contract for German
```
import org.springframework.cloud.contract.spec.Contract
Contract.make {
    description "request should complete with 200 status for german locale"
    request{
        method POST()
        headers {
            contentType(
                    applicationJson()
            )
            header ("accept-language","de")
        }
        url("/api/v1/user/register") {
            body("""
{
  "userName": "janedoeuser",
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@jane.com",
  "dob": 610309800000,
  "termsAccepted": true,
  "password": "3VelQdH9@"
}
            """)
        }
    }
    response {
        status 200
        body(

                """
{
  "userRegistered": true,
  "message": "Benutzerregistrierung abgeschlossen, Bitte bestätigen Sie Ihre E-Mail-Adresse für die Anmeldung."
}
"""
        )

    }
}
```
Above contract fails with following error
```
java.lang.IllegalStateException: Parsed JSON [{"userRegistered":true,"message":"Benutzerregistrierung abgeschlossen, Bitte best�tigen Sie Ihre E-Mail-Adresse f�r die Anmeldung."}] doesn't match the JSON path [$[?(@.['message'] == 'Benutzerregistrierung abgeschlossen, Bitte bestätigen Sie Ihre E-Mail-Adresse für die Anmeldung.')]]
	at com.toomuchcoding.jsonassert.JsonAsserter.check(JsonAsserter.java:228)
	at com.toomuchcoding.jsonassert.JsonAsserter.checkBufferedJsonPathString(JsonAsserter.java:267)
	at com.toomuchcoding.jsonassert.JsonAsserter.isEqualTo(JsonAsserter.java:101)
	at test.dope.hercules.user.service.ContractVerifierTest.validate_testUserAPIContractsV1ValidGermanLocale(ContractVerifierTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```
As per my inference translation of response is not working. Character such as '**ä**' and  '**ü**' are not parsed correctly.

I have added following property in maven pom.xml to ensure it is UTF-8 compatible.
```
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
```

Can anyone help with this issue. 

**2**. Is it possible to use same contract with different response file  based on language(de,en,fr). 
I can use the same contract use loop(Loop through different languages) to execute with different test scenarios.

**Comment by marcingrzejszczak** [comment]
Can you upload a sample somewhere? I've added this test to Spring Cloud Contract and it works fine.

You should use UTF-8. Why don't you want to use it?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
