### ISSUE TITLE
spring-cloud-contract with spring-jms

### ISSUE THREAD

**Issue by czyzniek** [spring-cloud/spring-cloud-contract#741]
Hi,

I was wondering if there is possibility to use your project with plain spring-jms lib? I tried to use yours
https://github.com/spring-cloud/spring-cloud-contract/tree/master/tests/samples-messaging-spring
but unfortunately examples ends with error:
`org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' available`
```
java.lang.IllegalStateException: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' available

	at org.springframework.cloud.contract.verifier.messaging.integration.SpringIntegrationStubMessages.receive(SpringIntegrationStubMessages.java:73)
	at org.springframework.cloud.contract.verifier.messaging.integration.SpringIntegrationStubMessages.receive(SpringIntegrationStubMessages.java:79)
	at org.springframework.cloud.contract.verifier.messaging.integration.SpringIntegrationStubMessages.receive(SpringIntegrationStubMessages.java:34)
	at com.example.SpringApplicationSpec.should work for triggered based messaging(SpringApplicationSpec.groovy:73)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:755)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1213)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1091)
	at org.springframework.cloud.contract.verifier.messaging.integration.SpringIntegrationStubMessages.receive(SpringIntegrationStubMessages.java:68)
	... 3 more
```
Is there a way to integrate spring-cloud-contract with spring-jms?

**Comment by marcingrzejszczak** [comment]
Yes, you can create your own bean of type `MessageVerifier` that will support JMS.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/issues/1141
