### ISSUE TITLE
Errors when testing for failure with default spring handler

### ISSUE THREAD

**Issue by SwEngin** [spring-cloud/spring-cloud-contract#751]
Bug report

So I'm trying to test a failure scenario with the following response in my contract 

```
response{
        status NOT_ACCEPTABLE()
        body([
                status: 406,
                error: "Not Acceptable",
                message: "So Bad!",
                path: "/myservice"
        ])
        headers {
            contentType(applicationJson())
        }
}
```
and I get assertion error for the header and when I remove the headers section. It loads the body empty getting this so fine exception:

```
java.lang.IllegalArgumentException: json string can not be null or empty
	at com.jayway.jsonpath.internal.Utils.notEmpty(Utils.java:386)
	at com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:36)
	at com.jayway.jsonpath.JsonPath.parse(JsonPath.java:599)
	at org.springframework.cloud.contract.verifier.tests.ContractVerifierTest.validate_shouldRejectOrder(ContractVerifierTest.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by marcingrzejszczak** [comment]
Can you post the generated test? And your base class setup together with the controller?

**Comment by SwEngin** [comment]
Generated Test

```
        @Test
	public void validate_shouldRejectOrder() throws Exception {
		// given:
			MockMvcRequestSpecification request = given()
					.header("Content-Type", "application/json")
					.body("{\"lines\":[{\"line\":{\"name\":\"a1\",\"type\":\"a1\"}}]}");

		// when:
			ResponseOptions response = given().spec(request)
					.post("/orders");

		// then:
			assertThat(response.statusCode()).isEqualTo(406);
		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("['status']").isEqualTo(406);
			assertThatJson(parsedJson).field("['path']").isEqualTo("/orders");
			assertThatJson(parsedJson).field("['error']").isEqualTo("Not Acceptable");
			assertThatJson(parsedJson).field("['message']").isEqualTo("So Bad!");
	}
```

Base Class

```
mport io.restassured.module.mockmvc.RestAssuredMockMvc;
import org.junit.Before;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.context.WebApplicationContext;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = MyApplication.class)
public abstract class MyTestBase {

    @Autowired
    WebApplicationContext webApplicationContext;

    @Before
    public void setup() {
        RestAssuredMockMvc.webAppContextSetup(webApplicationContext);
    }
}
```

Controller

```
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@RestController
@RequestMapping("/lines")
public class LineController {

    private final LineService lineService;

    public LineController(LineService lineService) {
        this.lineService = lineService;
    }

    @RequestMapping(method= RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody Confirmation process(@RequestBody @Valid MultipleLines lines) {
        return lineService.doProcess(lines);
    }
}
```

Btw other test cases for success work just fine

**Comment by marcingrzejszczak** [comment]
Can you actually run this as an app and show exactly what the response is? Cause it looks as if your response was missing some data. Also you mentioned that the response body should look like this:

```json
{
"status": 406,
                "error": "Not Acceptable",
                "message": "So Bad!",
                "path": "/myservice"
}
```

where do you set such a response body in case of an exception?

**Comment by SwEngin** [comment]
@marcingrzejszczak actually I did run it and the only thing I omitted is the timestamp. It's the response from internal spring errorhandler only my custom exception. Content-Type header is application/json; charset=utf-8 which should be a match, but I get an assertion error.

Also tried having timestamp field with regex but still, no success.

**Comment by marcingrzejszczak** [comment]
Can you send back the response? Also wiremock responds with a non matched response. Can you show it?

**Comment by SwEngin** [comment]
Full Response

```
{
    "timestamp": "2018-10-17T09:52:37.339+0000",
    "status": 406,
    "error": "Not Acceptable",
    "message": "So Bad!",
    "path": "/lines"
}
```
Actually the assertion error or any error I get is not related to wiremock at all. For example if I have headers section, test results states an assertion error here:

```
assertThat(response.header("Content-Type")).matches("application/json.*");
```
In the test report however, it states that the header is null as well

```
java.lang.AssertionError: 
Expecting actual not to be null
```

**Comment by marcingrzejszczak** [comment]
Can you paste the headers that are sent back?

**Comment by SwEngin** [comment]
Btw I get the correct response printed in the console

**Comment by marcingrzejszczak** [comment]
For some reason you don't return the header of `Content-Type` . I think your controller mapping

```java 
  @RequestMapping(method= RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
```

is missing the `produces=MediaType.APPLICATION_JSON_VALUE` ?

**Comment by SwEngin** [comment]
@marcingrzejszczak added and same. that is not an issue with the success scenarios though

**Comment by marcingrzejszczak** [comment]
I don't really know how to help you cause the test just reuses RestAssured. From the rest assured perspective, you are not passing the header. You haven't provided all the logic you're using. IMO you have done sth wrong with the error catching and processing. But since you haven't provided that logic, it's close to impossible to help you.

**Comment by SwEngin** [comment]
The error is just runtime exception annotated with @ResponseStatus(HttpStatus.NOT_ACCEPTABLE)

**Comment by marcingrzejszczak** [comment]
Please post your sample somewhere. I can't help you like this with just bits of information passed every now and then.

**Comment by SwEngin** [comment]
Here you go https://github.com/SwEngin/spring-contract-problem

**Comment by SwEngin** [comment]
The problem here is that when an exception occurs it's not considered as a response. When I've a custom test handler the test succeeds because I return a ResponseEntity.

**Comment by SwEngin** [comment]
@marcingrzejszczak the problem here is that when an exception occurs it's not considered a response with default spring exception handling. When I have my custom exception handler the test succeeds

**Comment by SwEngin** [comment]
@marcingrzejszczak the problem here is that when an exception occurs it's not considered a response with default spring exception handling. When I have my custom exception handler the test succeeds as a I return a ResponseEntity.

**Comment by marcingrzejszczak** [comment]
I can't find your project anywhere. Is the problem gone?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by SwEngin** [comment]
Sorry it's been a while I didn't notice your reply. Here once more the repo with the problem: https://github.com/SwEngin/spring-contract-problem

**Comment by marcingrzejszczak** [comment]
Everything is fine with Spring Cloud Contract. Your Spring exception handling setup is wrong.

# TestController.java

```java
@RestController
@RequestMapping("/tests")
public class TestController {

    private static final String EXC = "Not Acceptable!";

    @RequestMapping(method= RequestMethod.POST,
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody
    WelcomeMessage welcome(@RequestBody WelcomeMessage msg) {

        if (msg.getMessage().equals("test")) {
            throw new ContractException(EXC);
        }

        return msg;
    }

    @ResponseStatus(HttpStatus.NOT_ACCEPTABLE)
    @ExceptionHandler(ContractException.class)
    ResponseEntity<ContractError> handleBadRequest(HttpServletRequest req, Exception ex) {
        return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE)
                .contentType(MediaType.APPLICATION_JSON)
                .body(new ContractError(HttpStatus.NOT_ACCEPTABLE.value(), ex.getMessage()));
    }
}
```

# ContractError.java

```java
public class ContractError {

    private int status;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy hh:mm:ss")
    private LocalDateTime timestamp;
    private String message;

    private ContractError() {
        timestamp = LocalDateTime.now();
    }

    public ContractError(int status, String message) {
        this();
        this.status = status;
        this.message = message;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ContractError that = (ContractError) o;
        return status == that.status
                && Objects.equals(timestamp, that.timestamp)
                && Objects.equals(message, that.message);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, timestamp, message);
    }

    @Override
    public String toString() {
        return "ContractError{"
                + "status=" + status
                + ", timestamp=" + timestamp
                + ", message='" + message + '\''
                + '}';
    }
}
```

You had no code that would properly resolve the object to a JSON. You can read more about this here: https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc

**Comment by SwEngin** [comment]
@marcingrzejszczak thanks I already said that custom exception handler solved the problem for me but I was just wondering why when I run the app I get correct response but with tests not

**Comment by SwEngin** [comment]
So here is the explanation for this since the exception annotated with @ResponseStatus it's handled by ResponseStatusExceptionResolver and this resolver lacks the body that's why the response has no body and exception handler is required if someone wants to check the response body of the error response.
