### ISSUE TITLE
StubRunnerWireMockTestExecutionListener should not start stub runner without @AutoConfigureStubRunner on test class

### ISSUE THREAD

**Issue by huberchrigu** [spring-cloud/spring-cloud-contract#798]
Bug report for version 2.0.2.
We have multiple `@SpringBootTest`-annotated test classes, some with `@AutoConfigureStubRunner` and some without. Since they all have the same application context, the `StubRunnerWireMockTestExecutionListener` tries to stop and start a stub for every test class, also the ones that are not annotated with `@AutoConfigureStubRunner`. Also the behavior for every single class depends on the order of the test execution, since the `STUBS` map only contains a stub for the application context after the first `@AutoConfigureStubRunner` class was executed.

I would expect that tests without `@AutoConfigureStubRunner` do not try to start any stub runner. We have the [known issue of _java.lang.RuntimeException: java.net.BindException: Address already in use: bind_](https://github.com/spring-cloud/spring-cloud-contract/issues/665) and need to apply the `@DirtiesContext` workaround. With this fix, we could at least get rid of `@DirtiesContext` on all test classes that do not need the stub runner.

**Comment by OlgaMaciaszek** [comment]
@huberchrigu lgtm . Thanks for reporting this.

**Comment by KOTLAPRA23** [comment]
Hi Could you please help me here .

I am running wiremock junit test case and getting below exception every time
2020-04-10 20:51:34.541 INFO 84435 --- [ Test worker] o.s.b.a.e.web.EndpointLinksResolver : Exposing 2 endpoint(s) beneath base path ''
2020-04-10 20:51:34.822 INFO 84435 --- [ Test worker] org.eclipse.jetty.server.Server : jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_221-b11
2020-04-10 20:51:34.853 INFO 84435 --- [ Test worker] o.e.jetty.server.handler.ContextHandler : Started o.e.j.s.ServletContextHandler@a51c931{/__admin,null,AVAILABLE}
2020-04-10 20:51:34.856 INFO 84435 --- [ Test worker] o.e.jetty.server.handler.ContextHandler : Started o.e.j.s.ServletContextHandler@3d622400{/,null,AVAILABLE}
2020-04-10 20:51:34.869 INFO 84435 --- [ Test worker] o.e.jetty.server.AbstractConnector : Started NetworkTrafficServerConnector@709ceff2{HTTP/1.1,[http/1.1]}{0.0.0.0:5000}
2020-04-10 20:51:34.869 INFO 84435 --- [ Test worker] org.eclipse.jetty.server.Server : Started @80828ms

2020-04-10 20:53:40.153 INFO 84435 --- [tp780160597-117] o.e.j.s.handler.ContextHandler.ROOT : RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2020-04-10 20:53:40.301 ERROR 84435 --- [qtp780160597-92] WireMock : Request was not matched as there were no stubs registered:
{
"url" : "/o/.well-known/openid-configuration",
"absoluteUrl" : "http://0.0.0.0:5000/o/.well-known/openid-configuration",
"method" : "GET",
"clientIp" : "127.0.0.1",
"headers" : {
"Cache-Control" : "max-age=0",
"Accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3",
"Upgrade-Insecure-Requests" : "1",
"Connection" : "keep-alive",
"User-Agent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
"Host" : "0.0.0.0:5000",
"Accept-Encoding" : "gzip, deflate",
"Accept-Language" : "en-GB,en-US;q=0.9,en;q=0.8"
},
"cookies" : { },
"browserProxyRequest" : false,
"loggedDate" : 1586548420194,
"bodyAsBase64" : "",
"body" : "",
"scheme" : "http",
"host" : "0.0.0.0",
"port" : 5000,
"loggedDateString" : "2020-04-10T19:53:40Z",
"queryParams" : { }
}

Caused by: java.io.IOException: Failed to bind to /0.0.0.0:5000
at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.server.Server.doStart(Server.java:385)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:174)
... 67 common frames omitted
Caused by: java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.Net.bind(Net.java:425)
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
... 74 common frames omitted

Code sample:

@RunWith(SpringRunner.class)
@SpringBootTest(classes = Application.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DirtiesContext
public abstract class SpringBootIntegrationTest {

@LocalServerPort
protected int port;
}

@configuration
@AutoConfigureWireMock(port = 5000)
public abstract class AuthorizationEnabledIntegrationTest extends SpringBootIntegrationTest {

@ClassRule
public static WireMockRule someService = new WireMockRule(options().port(5000).withRootDirectory("src/integrationTest/resources/mappings"));
}

inside mappings folder :
{
"priority": 1,
"mappings": [
{
"request": {
"method": "GET",
"url": "/o/.well-known/openid-configuration"
},
"response": {
"status": 200,
"headers": {
"Content-Type": "application/json"
},
"jsonBody": {
"issuer": "http://0.0.0.0:5000/o",
"jwks_uri": "http://0.0.0.0:5000/jwks"
}
}
}
]
}

**Comment by OlgaMaciaszek** [comment]
You're using a port where there's already another http process running, hence you get `java.net.BindException: Address already in use`. 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Please do not comment on closed issues with a different problem.

**Comment by marcingrzejszczak** [comment]
Please don't cross post https://github.com/spring-cloud/spring-cloud-contract/issues/665
