### ISSUE TITLE
spring-cloud-contract-maven-plugin fail the build automatically if contract is wrong

### ISSUE THREAD

**Issue by benoitheinrich** [spring-cloud/spring-cloud-contract#801]
Enhancement

I'm using the **spring-cloud-contract-maven-plugin** a lot in my project, and one of the issue I have is that when someone creates a new contract, then if the contract is malformed then no stub and no test get created for that contract, but the maven build still complete like if there was no problem.

It's only after turning on maven debug output on that I'm finally able to find why my contract fail.

It would be really nice if the **spring-cloud-contract-maven-plugin** has an option that can automatically stop the build during the **spring-cloud-contract:convert** goal if a contract is malformed.

```
<configuration>
  <failOnConvertError>true</failOnConvertError>
</configuration>
```

Here is for instance a contract which has an invalid option:
```
description: |
  Some test
request:
  url: /pendingFiles/submit
  queryParameters:
    username: John
  method: POST
  headers:
    Content-Type: application/json

response:
  status: 202
  body:
    status: success
    message: The new configuration is being applied
    files:
    - workbookType: Groovy Script
      username: John
      filename: exitConseling/triggerGraduating.groovy
      uploadedDate: '2018-11-07T16:51:28.000Z'
      success: true
      details: "new script created"

  matchers:
    body:
    - path: $.files[*]
      type: by_command
      value: assertThatSizeIs($it, 3)
    - path: $.files[0].workbookType
      type: by_equality
    - path: $.files[0].username
      type: by_equality
    - path: $.files[0].filename
      type: by_equality
    - path: $.files[0].uploadedDate
      type: by_regex
      predefined: iso_8602_with_offset
```

This will generate the following error in the logs:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.springframework.cloud.contract.verifier.converter.YamlContract$PredefinedRegex` from String "iso_8602_with_offset": value not one of declared Enum instance names: [non_blank, iso_date_time, iso_8601_with_offset, iso_time, iso_date, only_alpha_unicode, url, hostname, any_boolean, uuid, ip_address, any_double, number, non_empty, email]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.springframework.cloud.contract.verifier.converter.YamlContract["response"]->org.springframework.cloud.contract.verifier.converter.YamlContract$Response["matchers"]->org.springframework.cloud.contract.verifier.converter.YamlContract$TestMatchers["body"]->java.util.ArrayList[16]->org.springframework.cloud.contract.verifier.converter.YamlContract$BodyTestMatcher["predefined"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
```

It would be nice that when **failOnConvertError=true** that the maven build stops with the error:
```
[ERROR] spring-cloud-contract:convert: in file "src/test/resources/contracts/test.yaml": 
  Cannot deserialize value of type `org.springframework.cloud.contract.verifier.converter.YamlContract$PredefinedRegex` from String "iso_8602_with_offset": value not one of declared Enum instance names: [non_blank, iso_date_time, iso_8601_with_offset, iso_time, iso_date, only_alpha_unicode, url, hostname, any_boolean, uuid, ip_address, any_double, number, non_empty, email]
    at [Source: src/test/resources/contracts/test.yaml; line: 37, column: 19] 
	
```

Let me know what you think about that ?

Cheers.

**Comment by marcingrzejszczak** [comment]
That's already implemented in 2.1.0

**Comment by marcingrzejszczak** [comment]
That == invalid YAML will fail and break the build

**Comment by benoitheinrich** [comment]
Nice :) 

Is there an ETA on when 2.1.0 will be available in maven repo ?

**Comment by OlgaMaciaszek** [comment]
Release is scheduled on 20th Dec. https://github.com/spring-cloud/spring-cloud-release/milestones

**Comment by benoitheinrich** [comment]
thanks
