### ISSUE TITLE
[spring-cloud-contract-wiremock:2.1.0.RC3]: JUnit5 BeforeAll failed to connect

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [spring-cloud/spring-cloud-contract#843]
Hello,

I recently hit a possible bug, or at least a regression. The following code sample ([full repo](https://github.com/ThanksForAllTheFish/cloud-wiremock)) works until version `2.1.0.RC2`, including version `2.0.2.RELEASE`, but failed to start the test with `wiremock.org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)` with `2.1.0.RC3`.

```
@SpringBootTest
@AutoConfigureWireMock(port = 0)
class AppTest {
	companion object {
		@BeforeAll
		@JvmStatic
		fun init() {
			WireMock.stubFor(
				WireMock.get(WireMock.urlPathMatching("/test"))
					.willReturn(
						WireMock.ok()
					)
			)
		}
	}

	@Test
	fun test() {

	}
}
```

I tried the following matrix of versions:

| BOOT/CLOUD-CONTRACTS   |      2.0.2.RELEASE      |  2.1.0.RC2 | 2.1.0.RC3 |
|----------|:-------------:|:------:|:------:|
| 2.0.6.RELEASE |  X | - | - |
| 2.1.1.RELEASE |   V   |  V | X |

where:

- `X` represents the connection refused failure
- `-` is a combination I did not try
- `V` represents the test running succesully

I am not sure whether this is a bug, given the failure with versions `2.0`, but it definitely worked at some point

**Comment by OlgaMaciaszek** [comment]
Hello @ThanksForAllTheFish could you please verify if this error still occurs on the current snapshot?

**Comment by ThanksForAllTheFish** [comment]
Yes, with Spring Boot `2.1.1` and `spring-cloud-contract-wiremock:2.1.0.BUILD-SNAPSHOT` it fails. The partial stacktrace is 

```
wiremock.org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

	at wiremock.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at wiremock.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at wiremock.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at wiremock.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at wiremock.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at wiremock.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:436)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:417)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:133)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:292)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:287)
	at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:106)
	at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:110)
	at org.t4atf.wiremock.AppTest$Companion.init(AppTest.kt:19)
	at org.t4atf.wiremock.AppTest.init(AppTest.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllMethods$8(ClassTestDescriptor.java:373)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllMethods(ClassTestDescriptor.java:372)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:201)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:74)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at wiremock.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at wiremock.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 49 more
```

Honestly though, I am quite surprised it ever worked in that small time frame; I am no expert, but `@BeforeAll` is on a static method, I am not sure Spring context can be initialized properly.

**Comment by marcingrzejszczak** [comment]
> Honestly though, I am quite surprised it ever worked in that small time frame; I am no expert, but @BeforeAll is on a static method, I am not sure Spring context can be initialized properly.

I agree :)

I've just checked that the static, `@BeforeAll` method is called before the `WireMockConfiguration` is setup. If it worked previously then it worked by chance.
