### ISSUE TITLE
BUG: Regression in 2.1.0 in YAML while referencing request in response assertions

### ISSUE THREAD

**Issue by danhyun** [spring-cloud/spring-cloud-contract#866]
Spring cloud contracts 2.1.0.RELEASE

According to the [documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/2.1.0.RELEASE/single/spring-cloud-contract.html#_referencing_the_request_from_the_response) you're supposed to be able to reference request information from response assertions.

This was working as advertised in 2.0.2.RELEASE however has been broken in 2.1.0.RELEASE

[Sample yaml](https://raw.githubusercontent.com/danhyun/spring-cloud-contract-oopsies/master/src/test/resources/contracts/rest/foo/requestPathBroken_2_1_X.yml)
```yaml
description: used to be able to generate tests with request path in matchers in 2.0.X
request:
  method: POST
  headers:
    content-type: application/json
  url: /foo
  body: >
    [{
      "bar": {
        "baz": true
      }
    }]
response:
  status: 200
  headers:
    content-type: application/json;charset=UTF-8
  body:
    - foo:
        bar:
          baz: true
  matchers:
    body:
      - path: $[*].path
        type: by_regex
        value: "/{{{ request.path.[0] }}}"
```

Example of regression: https://travis-ci.org/danhyun/spring-cloud-contract-oopsies/builds/487121129

This travis build runs test with [`2.0.2.RELEASE` then uses `2.1.0.RELEASE` in a subsequent run](https://github.com/danhyun/spring-cloud-contract-oopsies/blob/9e4af987606cfda29d52bfbb2f400bd886bf3b5d/.travis.yml#L5-L6).

[Output when using `2.1.0.RELEASE`](https://travis-ci.org/danhyun/spring-cloud-contract-oopsies/builds/487121129#L569-L571)
```
* What went wrong:
Execution failed for task ':generateContractTests'.
> Failed to convert file [/home/travis/build/danhyun/spring-cloud-contract-oopsies/build/stubs/META-INF/spring-cloud-contract-oopsies/unspecified/contracts/rest/foo/requestPathBroken_2_1_X.yml]
```

Impact: We are pinning back our usage of spring-cloud-contracts to 2.0.2.RELEASE, there are some useful features in 2.1.0.RELEASE we'd like to use.

**Comment by marcingrzejszczak** [comment]
Can you run the build with debug logs so that we know what's going on?

**Comment by danhyun** [comment]
UI: https://travis-ci.org/danhyun/spring-cloud-contract-oopsies/builds/489797139
RAW LOG: https://api.travis-ci.org/v3/job/489797140/log.txt

If you look at the [travis yaml](https://github.com/danhyun/spring-cloud-contract-oopsies/blob/9e4af987606cfda29d52bfbb2f400bd886bf3b5d/.travis.yml#L5-L6) you can see that I'm only running

```sh
./gradlew clean test
./gradlew clean test -PcontractsVersion=2.1.0.RELEASE
```

So you can clone my repo and run these to reproduce/diagnose/debug.

I've added `-d` for debug flag and `-s` to dump relevant stack traces and executed on Travis for your convenience.

The important markers for `ctrl+f` are:

1. `The command "./gradlew clean test -d -s" exited with 0.`
For the first `./gradlew clean test -d` using `2.0.2.RELEASE`

2. `The command "./gradlew clean test -PcontractsVersion=2.1.0.RELEASE -d -s" exited with 1.` for the failed execution.

Relevant Stack traces:

```23:00:37.153 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IllegalStateException: Failed to convert file [/home/travis/build/danhyun/spring-cloud-contract-oopsies/build/stubs/META-INF/spring-cloud-contract-oopsies/unspecified/contracts/rest/foo/requestPathBroken_2_1_X.yml]
23:00:37.153 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.file.ContractFileScanner.tryConvert(ContractFileScanner.groovy:171)
23:00:37.153 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.file.ContractFileScanner.addContractToTestGeneration(ContractFileScanner.groovy:147)
23:00:37.153 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.file.ContractFileScanner.appendRecursively(ContractFileScanner.groovy:117)
23:00:37.153 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.file.ContractFileScanner.addContractToTestGeneration(ContractFileScanner.groovy:156)
23:00:37.153 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.file.ContractFileScanner.appendRecursively(ContractFileScanner.groovy:117)
23:00:37.154 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.file.ContractFileScanner.addContractToTestGeneration(ContractFileScanner.groovy:156)
23:00:37.154 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.file.ContractFileScanner.appendRecursively(ContractFileScanner.groovy:117)
23:00:37.154 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.file.ContractFileScanner.findContracts(ContractFileScanner.groovy:88)
23:00:37.154 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.TestGenerator.generateTestClasses(TestGenerator.groovy:110)
23:00:37.154 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.TestGenerator.generate(TestGenerator.groovy:91)
23:00:37.154 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.TestGenerator$generate.call(Unknown Source)
23:00:37.154 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.plugin.GenerateServerTestsTask.generate(GenerateServerTestsTask.groovy:73)
23:00:37.155 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
23:00:37.155 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
23:00:37.155 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
23:00:37.155 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
23:00:37.155 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
23:00:37.155 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
23:00:37.155 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 100 more
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IllegalStateException: Exception occurred while processing the file [/home/travis/build/danhyun/spring-cloud-contract-oopsies/build/stubs/META-INF/spring-cloud-contract-oopsies/unspecified/contracts/rest/foo/requestPathBroken_2_1_X.yml]
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts.convertFrom(YamlToContracts.groovy:74)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlContractConverter.convertFrom(YamlContractConverter.groovy:46)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.file.ContractFileScanner.tryConvert(ContractFileScanner.groovy:169)
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 125 more
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.util.regex.PatternSyntaxException: Illegal repetition near index 0
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] /{{{ request.path.[0] }}}
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] ^
23:00:37.156 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java_util_regex_Pattern$compile.call(Unknown Source)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.spec.internal.BodyMatchers.byRegex(BodyMatchers.groovy:79)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts$_processYaml_closure1$_closure5$_closure34$_closure40.doCall(YamlToContracts.groovy:324)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts$_processYaml_closure1$_closure5$_closure34.doCall(YamlToContracts.groovy:303)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts$_processYaml_closure1$_closure5$_closure34.doCall(YamlToContracts.groovy)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.spec.internal.Response.bodyMatchers(Response.groovy:205)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts$_processYaml_closure1$_closure5.doCall(YamlToContracts.groovy:302)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts$_processYaml_closure1$_closure5.doCall(YamlToContracts.groovy)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.spec.Contract.response(Contract.groovy:165)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts$_processYaml_closure1.doCall(YamlToContracts.groovy:260)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts$_processYaml_closure1.doCall(YamlToContracts.groovy)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.spec.Contract.make(Contract.groovy:91)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts.processYaml(YamlToContracts.groovy:85)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.springframework.cloud.contract.verifier.converter.YamlToContracts.convertFrom(YamlToContracts.groovy:61)
23:00:37.157 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 127 more```

**Comment by marcingrzejszczak** [comment]
Ok, now I see what the problem is.

I'm pretty sure that in Finchley there was exactly the same problem, but for Greenwich we're actually throwing an exception when your YAML is not being possible to be converted to our internal representation.

`"/{{{ request.path.[0] }}}"` is not a valid regular expression. Why do you even make it a regex matcher, since it's not a valid regular expression.

```yml
 body:
    - foo:
        bar:
          baz: true
  matchers:
    body:
      - path: $[*].path
        type: by_regex
        value: "/{{{ request.path.[0] }}}"
```

should actually be sth like

```yml
 body:
    - foo:
        bar:
          baz: true
    - path: "/{{{ request.path.[0] }}}"
```

I don't recall ever allowing such hacks as you're trying to do :)

**Comment by marcingrzejszczak** [comment]
Related discussion - https://github.com/spring-cloud/spring-cloud-contract/issues/722

**Comment by tsymbalyuk** [comment]
@marcingrzejszczak Are you telling that handlebars are no more supported in body matchers section?

Cause I can see valid cases where they can be used, for instance asserting the exact element count in the response:
```
matchers:
    body:
      - path: $.items.size()
        type: by_regex
        value: "{{{ request.query.size.[0] }}}"
```
or
```
matchers:
    body:
      - path: $.items.size()
        type: by_command
        value: checkSize($it, {{{ request.query.size.[0] }}})
```

On 2.0.2.RELEASE it resulted in lines in ContractVerifierTest class, correspondingly:
```
assertThat(parsedJson.read("$.items.size()", String.class)).matches("5");
```
and
```
checkSize(parsedJson.read("$.items.size()"), 5);
```
Where 5 is value from `size` query parameter.

In my opinion, the check above aligns nicely with philosophy of verifying 'dynamic' body parameters in body matchers section.
