### ISSUE TITLE
Could not find a suitable constructor exception when running spring-cloud-contract-maven-plugin:1.0.0.RELEASE:generateTests

### ISSUE THREAD

**Issue by poprygun** [spring-cloud/spring-cloud-contract#87]
I am getting the exception below when running spring-cloud-contract-maven-plugin:1.0.0.RELEASE:generateTests / run.  Worked fine with snapshot version of spring-cloud-contract-maven-plugin.

Here is the link to my [pom file](https://github.com/poprygun/eventual-consistency/blob/master/producer-service/pom.xml)

Full exception
```
Sep 27, 2016 10:40:34 AM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: org.springframework.cloud.contract.maven.verifier.RunMojo
com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in org.springframework.cloud.contract.maven.verifier.RunMojo. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at org.springframework.cloud.contract.maven.verifier.RunMojo.class(Unknown Source)
  while locating org.springframework.cloud.contract.maven.verifier.RunMojo

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:991)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:950)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.018s
[INFO] Finished at: Tue Sep 27 10:40:34 EDT 2016
[INFO] Final Memory: 20M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.0.0.RELEASE:run (default-cli) on project producer-service: Execution default-cli of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.0.0.RELEASE:run failed: Unable to load the mojo 'run' (or one of its required components) from the plugin 'org.springframework.cloud:spring-cloud-contract-maven-plugin:1.0.0.RELEASE': com.google.inject.ProvisionException: Guice provision errors:
[ERROR] 
[ERROR] 1) Could not find a suitable constructor in org.springframework.cloud.contract.maven.verifier.RunMojo. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
[ERROR] at org.springframework.cloud.contract.maven.verifier.RunMojo.class(Unknown Source)
[ERROR] while locating org.springframework.cloud.contract.maven.verifier.RunMojo
[ERROR] at ClassRealm[plugin>org.springframework.cloud:spring-cloud-contract-maven-plugin:1.0.0.RELEASE, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.springframework.cloud:spring-cloud-contract-maven-plugin:1.0.0.RELEASE:run)
[ERROR] 
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: org.springframework.cloud:spring-cloud-contract-maven-plugin:1.0.0.RELEASE:run
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

Process finished with exit code 1
```

**Comment by marcingrzejszczak** [comment]
Ping @mariuszs

**Comment by mariuszs** [comment]
Please specify `mvn -version`

**Comment by mariuszs** [comment]
Issue is about `generateTests`, but logs are about:

```Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.0.0.RELEASE:run```

So, this is about `run`?

**Comment by kkrawczy** [comment]
I had the same issue when I was using IntlliJ maven plugin to generate the tests. I didn't have the problem while executing from a command line. The problem was the version of maven. The embedded version in IntelliJ was 3.0.5. When I updated it to the one that I have on my machine (3.3.9), the problem disappeared.
I hope that can help.

**Comment by mariuszs** [comment]
Yes, maven embedded inside IntelliJ is not supported (too old). But it is possible to configure IntellIj to use new maven version.

**Comment by mariuszs** [comment]
Confirmed, this exception is from maven 3.0.5 - unsupported version.

**Comment by marcingrzejszczak** [comment]
We need to add documentation info for that
