### ISSUE TITLE
Bug: Pact to SCC message contract translation numeric types

### ISSUE THREAD

**Issue by schustes** [spring-cloud/spring-cloud-contract#889]
The problem occurs if a pact message contract has numeric matcher fields. For example:

``` 
     "matchingRules": {
        "body": {
          "$.timestamp": {
            "matchers": [
              {
                "match": "number"
              }
            ],
```

Then the MessagingSCContractCreator part with `jsonPath(key, byRegex(number())), jsonPath(key, byRegex(anInteger()))` etc. in lines 108 ff. seems to not create the expected expression (I didn't understand what is going on in these methods). With my limited knowledge, I would guess that a `byType()` matcher could be enough instead of a regex.

Exception: 

```
Exception occurred while trying to store the mapping
java.lang.ClassCastException: org.springframework.cloud.contract.spec.internal.ResponseBodyMatchers cannot be cast to groovy.lang.Closure
        at org.springframework.cloud.contract.verifier.spec.pact.MessagingSCContractCreator$_convertFrom_closure1$_closure2$_closure4$_closure5$_closure7$_closure9.doCall(MessagingSCContractCreator.groovy:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
        at org.springframework.cloud.contract.verifier.spec.pact.MessagingSCContractCreator$_convertFrom_closure1$_closure2$_closure4$_closure5$_closure7.doCall(MessagingSCContractCreator.groovy:85)
```

**Comment by marcingrzejszczak** [comment]
Can you paste the whole Pact JSON please?

**Comment by schustes** [comment]
Sorry, here it is:
``` 
{
  "consumer": {
    "name": "order-manager"
  },
  "provider": {
    "name": "lineitem-worker"
  },
  "messages": [
    {
      "description": "A message sent to order-exchange",
      "metaData": {
        "sentTo": "order-exchange"
      },
      "contents": {
        "lineItemId": "string",
        "orderId": "XXX-XXXXXX-000000-0000C",
        "timestamp": 1550500138678,
        "marketId": "MRKTDE",
        "status": "PROCESSED"
      },
      "providerStates": [
        {
          "name": "statusMessageCreated()"
        }
      ],
      "matchingRules": {
        "body": {
          "$.timestamp": {
            "matchers": [
              {
                "match": "number"
              }
            ],
            "combine": "AND"
          },
          "$.lineItemId": {
            "matchers": [
              {
                "match": "type"
              }
            ],
            "combine": "AND"
          },
          "$.orderId": {
            "matchers": [
              {
                "match": "regex",
                "regex": "[A-Z]{3}-[A-Z]{6}-[0-9]{6}-[0-9A-F]{5}"
              }
            ],
            "combine": "AND"
          },
          "$.marketId": {
            "matchers": [
              {
                "match": "regex",
                "regex": "[A-Z]{6}"
              }
            ],
            "combine": "AND"
          },
          "$.status": {
            "matchers": [
              {
                "match": "regex",
                "regex": "[A-Z,_]*"
              }
            ],
            "combine": "AND"
          }
        }
      }
    }
  ],
  "metadata": {
    "pact-specification": {
      "version": "3.0.0"
    },
    "pact-jvm": {
      "version": "3.5.13"
    }
  }
}
```
