### ISSUE TITLE
Composite Stubs downloader fails if no stub found at a pact-broker and Aether Stubdownloader is executed as next

### ISSUE THREAD

**Issue by schustes** [spring-cloud/spring-cloud-contract#895]
I configured contracts in my gradle build file to have as remote repository a pact-broker:
```
contracts
 {
    contractDependency {
        stringNotation = '${project.group}:order-service:+'
    }
    contractsPath = '*'
    contractsMode = 'REMOTE'

    baseClassForTests = 'com.acme.contracttests.provider.OrderServiceBaseTest'
    contractRepository {
        repositoryUrl = 'pact://https://acme-pact-broker.apps.acme.com:443'
    }
}
```
If I configure the producer before a contract is published, the PactDownloader finds nothing and proceeds to the AetherStubDownloader

```
23:24:34.758 [WARN] [org.springframework.cloud.contract.stubrunner.PactStubDownloader] No pact definitions found for provider [order-service]
23:24:34.758 [WARN] [org.springframework.cloud.contract.stubrunner.CompositeStubDownloader] Stub Downloader [org.springframework.cloud.contract.stubrunner.PactStubDownloader] failed to find an entry for [com.audi.ecacp:order-service:+:stubs]. Will proceed to the next one
```

The AetherStubDownloader fails, because:

```
23:24:34.762 [DEBUG] [org.springframework.cloud.contract.stubrunner.AetherFactories] Local Repository Directory set to [C:\cygwin64\tmp\aether-local7083894330317797616]. Work offline: [false]
23:24:34.763 [DEBUG] [shaded.org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider] Using manager EnhancedLocalRepositoryManager with priority 10.0 for C:\cygwin64\tmp\aether-local7083894330317797616
23:24:34.763 [DEBUG] [org.springframework.cloud.contract.stubrunner.CompositeStubDownloader] Found a matching stub downloader [org.springframework.cloud.contract.stubrunner.AetherStubDownloader]
23:24:34.763 [INFO] [org.springframework.cloud.contract.stubrunner.AetherStubDownloader] Desired version is [+] - will try to resolve the latest version
23:24:34.765 [DEBUG] [shaded.org.eclipse.aether.internal.impl.DefaultTransporterProvider] Could not obtain transporter factory for remote0 (pact://https://xxxxxxxxxxxxxxxx:443, default, releases+snapshots)
org.eclipse.aether.transfer.NoTransporterException: Unsupported transport protocol pact
        at shaded.org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:105)
        at shaded.org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:93)
        at shaded.org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:110)
        at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:115)
        at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
        at shaded.org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
        at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:603)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver$1.execute(DefaultMetadataResolver.java:527)
        at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:382)
        at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:205)
        at shaded.org.apache.maven.repository.internal.DefaultVersionRangeResolver.getVersions(DefaultVersionRangeResolver.java:232)
        at shaded.org.apache.maven.repository.internal.DefaultVersionRangeResolver.resolveVersionRange(DefaultVersionRangeResolver.java:182)
        at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveVersionRange(DefaultRepositorySystem.java:279)
        at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.resolveHighestArtifactVersion(AetherStubDownloader.java:245)
        at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.getVersion(AetherStubDownloader.java:211)
        at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.downloadAndUnpackStubJar(AetherStubDownloader.java:221)
        at org.springframework.cloud.contract.stubrunner.CompositeStubDownloader.downloadAndUnpackStubJar(CompositeStubDownloaderBuilder.java:80)
        at org.springframework.cloud.contract.stubrunner.ContractDownloader.unpackAndDownloadContracts(ContractDownloader.java:170)
        at org.springframework.cloud.contract.stubrunner.ContractDownloader.unpackedDownloadedContracts(ContractDownloader.java:73)
        at org.springframework.cloud.contract.verifier.plugin.GradleContractsDownloader.downloadAndUnpackContractsIfRequired(GradleContractsDownloader.groovy:56)
```

I would find it handy if the CompositeStubDownloader would exit gracefully if no stubs could be downloaded remotely and scc just do nothing. Or if the AetherDownloader checked whether the protocol can be handled or something similar.

**Comment by marcingrzejszczak** [comment]
> I would find it handy if the CompositeStubDownloader would exit gracefully if no stubs could be downloaded remotely and scc just do nothing. Or if the AetherDownloader checked whether the protocol can be handled or something similar.

I don't like the first part, but I actually do like the second. 

However, I wonder if that's a valid scenario if no contracts are fetched. You will have no tests generated and your build might pass.

I think that we could consider adding a switch like `failOnNoContracts` or sth like that. WDYT? 

cc @OlgaMaciaszek

**Comment by schustes** [comment]
The switch is an excellent idea. I acutally searched yesterday whether there is something like this.

In understand that the scenario is not TDD-llike. My scenario is that I set up a new project with a build.gradle file and having the build not failing simply because there is no consumer yet that has published a contract for that service.
